#ifndef MDIR_COMPILER_COMPILECACHE_H
#define MDIR_COMPILER_COMPILECACHE_H

#include "llvm/ADT/STLFunctionalExtras.h"
#include "llvm/ExecutionEngine/ObjectCache.h"
#include "llvm/Support/Error.h"
#include <cstdint>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <string>

namespace llvm {
class TargetMachine;
}

namespace mdir::compiler {

/// What the host code generation of one engine, or of several, cost and
/// what the compile cache saved (D212).
struct CompileStats {
  /// Programs compiled, the time of their MLIR pipelines, and the time
  /// from the creation of their JIT engines to their entries: host code
  /// generation, linking, and on a GPU the loading of the kernels.
  unsigned programs = 0;
  double pipelineSeconds = 0.0;
  double engineSeconds = 0.0;
  /// Objects generated by LLVM, and the time that took.
  unsigned compiled = 0;
  double compileSeconds = 0.0;
  /// Objects taken from the cache, and the time their generation took when
  /// they were stored.
  unsigned hits = 0;
  double savedSeconds = 0.0;
  /// Entries found under the key's name but rejected: a different key, a
  /// wrong length or checksum, or an object LLVM cannot read.
  unsigned rejected = 0;
  /// Entries written, and the entries that could not be written.
  unsigned stored = 0;
  unsigned unstored = 0;
  /// The time spent on keys and on reading entries, hit or miss.
  double lookupSeconds = 0.0;

  /// The GPU modules of the programs (D214) and the wall
  /// time of their serialization. Each module is serialized to PTX, which
  /// LLVM generates or the cache gives, and on a device whose architecture
  /// is known, the PTX to a cubin, which ptxas generates or the cache
  /// gives.
  unsigned gpuModules = 0;
  double gpuSerializeSeconds = 0.0;
  unsigned gpuPtxCompiled = 0;
  unsigned gpuPtxHits = 0;
  unsigned gpuCubinCompiled = 0;
  unsigned gpuCubinHits = 0;
  /// The time the generated PTX and cubins took, summed over the modules,
  /// and the time the hits took when they were stored.
  double gpuCompileSeconds = 0.0;
  double gpuSavedSeconds = 0.0;
  /// The time spent on the keys and reads of GPU entries, hit or miss,
  /// summed over the modules.
  double gpuLookupSeconds = 0.0;
  /// The GPU entries rejected, written, and that could not be written.
  unsigned gpuRejected = 0;
  unsigned gpuStored = 0;
  unsigned gpuUnstored = 0;

  /// The programs compiled with the cache bypassed (`cache=False`,
  /// D217): no entry was read or written for them,
  /// whatever the environment says.
  unsigned bypassed = 0;

  CompileStats &operator+=(const CompileStats &other);
};

/// Where the compile cache lives, as the environment says
/// (D212). `MDIR_COMPILE_CACHE_DIR` names the directory;
/// without it, or with `MDIR_COMPILE_CACHE=off`, there is no cache.
/// `MDIR_COMPILE_CACHE_MAX_MB` bounds its size (2048 MiB by default).
struct CompileCacheConfig {
  std::string directory;
  uint64_t maxBytes = uint64_t(2048) << 20;

  static std::optional<CompileCacheConfig> fromEnvironment();
};

/// What clearCache removed (D217).
struct ClearedCache {
  /// Host objects (`host/*.o`) and GPU entries (`gpu/*.ptx`,
  /// `gpu/*.cubin`) removed, and their bytes.
  uint64_t hostEntries = 0;
  uint64_t gpuEntries = 0;
  uint64_t bytes = 0;
};

/// Removes the entries of this format of the cache at `directory`: the
/// files of the entries' names whose magic tag is this build's, and the
/// temporary files left by processes that died, as evictCache does, and
/// takes their bytes off the total that noteCacheStores keeps. Entries
/// of another format, files of other names, and the temporary files of
/// writers under way are left; so is the directory. Another process may
/// write or read entries meanwhile: a writer renames a complete entry into
/// place and a reader copies the file, so each sees a whole entry or none
/// (D217).
ClearedCache clearCache(llvm::StringRef directory);

/// The entries of every kind of the cache (D212, D214):
/// a magic tag, the full key, the length of the data, a BLAKE3 hash of
/// the data, the time its generation took, and the data.
///
/// Reads the entry at `path` if its key is `key`, its data is intact, and
/// `isValid` (if given) accepts the data; the time its generation took goes
/// to `seconds`. A file that exists but fails a check sets `rejected`.
std::unique_ptr<llvm::MemoryBuffer>
readCacheEntry(llvm::StringRef path, llvm::StringRef key, double &seconds,
               bool &rejected,
               llvm::function_ref<bool(llvm::StringRef)> isValid = nullptr);
/// Writes the entry atomically: a unique temporary file in the same
/// directory, then a rename. `written`, if given, takes the bytes of the
/// entry's file, for noteCacheStores.
llvm::Error writeCacheEntry(llvm::StringRef path, llvm::StringRef key,
                            llvm::StringRef data, double seconds,
                            uint64_t *written = nullptr);
/// The file name of the entry of `key`: a hash of the key and `extension`.
std::string getCacheEntryName(llvm::StringRef key, llvm::StringRef extension);
/// Lists the cache at `directory` and removes the entries used least
/// recently, of every kind (`host/*.o`, `gpu/*.ptx`, `gpu/*.cubin`), until
/// it holds at most `maxBytes`, and temporary files left by processes that
/// died. The listing reads the status of every entry, so stores do not
/// call this; they call noteCacheStores.
void evictCache(llvm::StringRef directory, uint64_t maxBytes);
/// Tells the cache at `directory` that this process stored entries of
/// `bytes` in all, and keeps it within `maxBytes`
/// (D234). The total of the entries is kept in the
/// file `<directory>/size`, which processes update under a lock, so a
/// store costs a fixed number of file operations whatever the directory
/// holds. The directory is listed, and entries evicted as evictCache does,
/// only when the total with these bytes exceeds the bound, when the file
/// holds no total, or when the last listing is a day old; without a usable
/// file (no locks on the file system) every call lists.
void noteCacheStores(llvm::StringRef directory, uint64_t bytes,
                     uint64_t maxBytes);
/// How many times this process listed a cache directory for eviction; for
/// tests.
uint64_t getCacheListingCount();
/// Marks the entry at `path` as used, for the eviction.
void touchCacheEntry(llvm::StringRef path);

/// The part of a key that the target machine and the code generator's
/// options give: the LLVM version, the triple, the CPU and its features,
/// the level of code generation, the code and relocation models, and the
/// data layout. `extra` names settings outside the machine that change the
/// generated code, such as the instruction scheduler.
std::string describeMachine(const llvm::TargetMachine &machine,
                            llvm::StringRef extra);

/// The cache of relocatable host objects of one JIT engine
/// (D212). ORC's compiler asks it for the object of a module
/// before it generates code, and gives it the object it generated.
///
/// An entry is keyed by the content of the LLVM module (a BLAKE3 hash of
/// its bitcode) and the machine's description; the MDIR build is not part
/// of the key, since the object is a function of the module alone. Each
/// entry stores its full key, the length and a BLAKE3 hash of the object,
/// and the time its generation took; an entry whose key, length, or hash
/// differs is a miss and is replaced. Entries are written to a temporary
/// file and renamed, so concurrent processes may share a directory. The
/// directory is bounded: when a store takes its total over the bound, the
/// entries used least recently are removed until it is within it
/// (noteCacheStores).
///
/// Without a directory the cache only measures the time code generation
/// takes. A hit returns a copy of the object; the engine links it into
/// memory of its own, as it does a generated object (D199).
class HostObjectCache final : public llvm::ObjectCache {
public:
  /// Only the module named `module` is cached and timed; the small modules
  /// that ORC makes for initialization name their functions uniquely, so
  /// they would never hit.
  HostObjectCache(std::optional<CompileCacheConfig> config, std::string machine,
                  std::string module);
  ~HostObjectCache() override;

  std::unique_ptr<llvm::MemoryBuffer>
  getObject(const llvm::Module *module) override;
  void notifyObjectCompiled(const llvm::Module *module,
                            llvm::MemoryBufferRef object) override;

  CompileStats getStats() const;

  /// The full key of `module`, and the name of its entry in the directory.
  std::string getKey(const llvm::Module &module) const;
  static std::string getEntryName(llvm::StringRef key);
  /// The directory of the host objects, under the cache's directory.
  static std::string getObjectDirectory(llvm::StringRef directory);

  /// Reads the entry at `path` if its key is `key` and its object is
  /// intact; the time its generation took goes to `seconds`.
  static std::unique_ptr<llvm::MemoryBuffer>
  readEntry(llvm::StringRef path, llvm::StringRef key, double &seconds,
            bool &rejected);
  /// Writes the entry atomically.
  static llvm::Error writeEntry(llvm::StringRef path, llvm::StringRef key,
                                llvm::MemoryBufferRef object, double seconds,
                                uint64_t *written = nullptr);

private:
  struct Pending {
    std::string key;
    double start = 0.0;
  };
  std::optional<CompileCacheConfig> config;
  std::string machine;
  std::string module;
  mutable std::mutex mutex;
  // A module between the request of its object and its compilation: code
  // generation changes the module, so its key is taken before.
  std::map<const llvm::Module *, Pending> pending;
  CompileStats stats;
};

} // namespace mdir::compiler
#endif
