#ifndef MDIR_COMPILER_COMPILECACHE_H
#define MDIR_COMPILER_COMPILECACHE_H

#include "llvm/ExecutionEngine/ObjectCache.h"
#include "llvm/Support/Error.h"
#include <cstdint>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <string>

namespace llvm {
class TargetMachine;
}

namespace mdir::compiler {

/// What the host code generation of one engine, or of several, cost and
/// what the compile cache saved (D[compile-cache]).
struct CompileStats {
  /// Programs compiled, the time of their MLIR pipelines, and the time
  /// from the creation of their JIT engines to their entries: host code
  /// generation, linking, and on a GPU the loading of the kernels.
  unsigned programs = 0;
  double pipelineSeconds = 0.0;
  double engineSeconds = 0.0;
  /// Objects generated by LLVM, and the time that took.
  unsigned compiled = 0;
  double compileSeconds = 0.0;
  /// Objects taken from the cache, and the time their generation took when
  /// they were stored.
  unsigned hits = 0;
  double savedSeconds = 0.0;
  /// Entries found under the key's name but rejected: a different key, a
  /// wrong length or checksum, or an object LLVM cannot read.
  unsigned rejected = 0;
  /// Entries written, and the entries that could not be written.
  unsigned stored = 0;
  unsigned unstored = 0;
  /// The time spent on keys and on reading entries, hit or miss.
  double lookupSeconds = 0.0;

  CompileStats &operator+=(const CompileStats &other);
};

/// Where the compile cache lives, as the environment says
/// (D[compile-cache]). `MDIR_COMPILE_CACHE_DIR` names the directory;
/// without it, or with `MDIR_COMPILE_CACHE=off`, there is no cache.
/// `MDIR_COMPILE_CACHE_MAX_MB` bounds its size (2048 MiB by default).
struct CompileCacheConfig {
  std::string directory;
  uint64_t maxBytes = uint64_t(2048) << 20;

  static std::optional<CompileCacheConfig> fromEnvironment();
};

/// The part of a key that the target machine and the code generator's
/// options give: the LLVM version, the triple, the CPU and its features,
/// the level of code generation, the code and relocation models, and the
/// data layout. `extra` names settings outside the machine that change the
/// generated code, such as the instruction scheduler.
std::string describeMachine(const llvm::TargetMachine &machine,
                            llvm::StringRef extra);

/// The cache of relocatable host objects of one JIT engine
/// (D[compile-cache]). ORC's compiler asks it for the object of a module
/// before it generates code, and gives it the object it generated.
///
/// An entry is keyed by the content of the LLVM module (a BLAKE3 hash of
/// its bitcode) and the machine's description; the MDIR build is not part
/// of the key, since the object is a function of the module alone. Each
/// entry stores its full key, the length and a BLAKE3 hash of the object,
/// and the time its generation took; an entry whose key, length, or hash
/// differs is a miss and is replaced. Entries are written to a temporary
/// file and renamed, so concurrent processes may share a directory. The
/// directory is bounded: after a store, the entries used least recently
/// are removed until it is below its bound.
///
/// Without a directory the cache only measures the time code generation
/// takes. A hit returns a copy of the object; the engine links it into
/// memory of its own, as it does a generated object (D199).
class HostObjectCache final : public llvm::ObjectCache {
public:
  /// Only the module named `module` is cached and timed; the small modules
  /// that ORC makes for initialization name their functions uniquely, so
  /// they would never hit.
  HostObjectCache(std::optional<CompileCacheConfig> config, std::string machine,
                  std::string module);
  ~HostObjectCache() override;

  std::unique_ptr<llvm::MemoryBuffer>
  getObject(const llvm::Module *module) override;
  void notifyObjectCompiled(const llvm::Module *module,
                            llvm::MemoryBufferRef object) override;

  CompileStats getStats() const;

  /// The full key of `module`, and the name of its entry in the directory.
  std::string getKey(const llvm::Module &module) const;
  static std::string getEntryName(llvm::StringRef key);
  /// The directory of the host objects, under the cache's directory.
  static std::string getObjectDirectory(llvm::StringRef directory);

  /// Reads the entry at `path` if its key is `key` and its object is
  /// intact; the time its generation took goes to `seconds`.
  static std::unique_ptr<llvm::MemoryBuffer>
  readEntry(llvm::StringRef path, llvm::StringRef key, double &seconds,
            bool &rejected);
  /// Writes the entry atomically.
  static llvm::Error writeEntry(llvm::StringRef path, llvm::StringRef key,
                                llvm::MemoryBufferRef object, double seconds);
  /// Removes the entries used least recently until the directory holds
  /// at most `maxBytes`, and temporary files left by processes that died.
  static void evict(llvm::StringRef directory, uint64_t maxBytes);

private:
  struct Pending {
    std::string key;
    double start = 0.0;
  };
  std::optional<CompileCacheConfig> config;
  std::string machine;
  std::string module;
  mutable std::mutex mutex;
  // A module between the request of its object and its compilation: code
  // generation changes the module, so its key is taken before.
  std::map<const llvm::Module *, Pending> pending;
  CompileStats stats;
};

} // namespace mdir::compiler
#endif
