// The reciprocal sum of smooth particle mesh Ewald on a device
// [Essmann1995] (docs/pme-m1.md). The keys are those of
// docs/references.md.
//
// Generated by scripts/generate-pme-gpu-template.py. Do not edit.
//
// This is a template. The compiler adds it to a module that has a
// reciprocal sum on a device, where it is specialized like any other code;
// the types of the positions, the charges, and the forces and their
// conversions are those of the template for the host (PME.mlir); the
// splines, the grid, and its transform are in !pme_real, which is the type
// of the forces, while the fractions of the positions and the edges of the
// cell are in f64. The buffers are on the device.
//
// A kernel runs one thread per item, in blocks of 128 threads. The threads
// beyond the last item do nothing. In the deterministic mode the charges
// are added to the grid in fixed point with integer atomics, so that the
// sum does not depend on the order of the threads (D70); by default they
// are added in !pme_real with floating-point atomics (D84). The product
// with the influence function sums
// the energy and the virial of each row of the grid in a thread; the host
// adds the rows up in their order.

!pme_pos = f64
!pme_chg = f64
!pme_frc = f64
// The type in which the splines, the grid, and its transform are computed:
// that of the forces on a device, so f32 in the mixed and single modes.
!pme_real = f64

func.func private @mdrt_gpu_pme_blocks(%count: index) -> index {
  %c127 = arith.constant 127 : index
  %c128 = arith.constant 128 : index
  %padded = arith.addi %count, %c127 : index
  %result = arith.divui %padded, %c128 : index
  return %result : index
}

// Spreads the charges to `grid`, in fixed point, so that the sum does not depend on the order of
// the threads (D70; the deterministic mode, D84).
func.func private @mdrt_gpu_pme_spread(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %box: vector<3xf64>, %grid: memref<?xi64, 1>,
                                       %k1: index, %k2: index, %k3: index, %n: index) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %points = memref.dim %grid, %c0 : memref<?xi64, 1>
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %spread_lanes = arith.constant PME_ORDER : index
  %spread = arith.muli %count, %spread_lanes : index
  %blocks_points = func.call @mdrt_gpu_pme_blocks(%points) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_points, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %points : index
    scf.if %inside {
      %none = arith.constant 0 : i64
      memref.store %none, %grid[%item] : memref<?xi64, 1>
    }
    gpu.terminator
  }
  %blocks_spread = func.call @mdrt_gpu_pme_blocks(%spread) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_spread, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %spread : index
    scf.if %inside {
      %lanes = arith.constant PME_ORDER : index
      %i = arith.divui %item, %lanes : index
      %j3 = arith.remui %item, %lanes : index
      %i0 = arith.constant 0 : index
      %i1 = arith.constant 1 : index
      %i2 = arith.constant 2 : index
      // The order of the splines, a constant of the instance, so that the loops
      // over it unroll and the splines are held in registers.
      %order = arith.constant PME_ORDER : index
      %wx = memref.alloca() : memref<8x!pme_real>
      %wy = memref.alloca() : memref<8x!pme_real>
      %wz = memref.alloca() : memref<8x!pme_real>
      %xs = memref.load %x[%i, %i0] : memref<?x3x!pme_pos, 1>
      %ys = memref.load %x[%i, %i1] : memref<?x3x!pme_pos, 1>
      %zs = memref.load %x[%i, %i2] : memref<?x3x!pme_pos, 1>
      %qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
      %xi = PME_EXTEND_POS %xs : !pme_pos to f64
      %yi = PME_EXTEND_POS %ys : !pme_pos to f64
      %zi = PME_EXTEND_POS %zs : !pme_pos to f64
      %qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real
      %px_s = arith.mulf %xi, %ilx : f64
      %px_fs = math.floor %px_s : f64
      %px_frac = arith.subf %px_s, %px_fs : f64
      %px_ki = arith.index_cast %k1 : index to i64
      %px_kf = arith.sitofp %px_ki : i64 to f64
      %px_u = arith.mulf %px_frac, %px_kf : f64
      %px_fu = math.floor %px_u : f64
      %px_w = arith.subf %px_u, %px_fu : f64
      %px_bi = arith.fptosi %px_fu : f64 to i64
      %px_b = arith.index_cast %px_bi : i64 to index
      %px_bk = arith.addi %px_b, %k1 : index
      %px_bkn = arith.subi %px_bk, %order : index
      %px_c1p = arith.constant 1 : index
      %px_start0 = arith.addi %px_bkn, %px_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %px_start = arith.remui %px_start0, %k1 : index
      %px_wr = PME_F64_TO_REAL %px_w : f64 to !pme_real
      %bx_c0 = arith.constant 0 : index
      %bx_c1 = arith.constant 1 : index
      %bx_c2 = arith.constant 2 : index
      %bx_c3 = arith.constant 3 : index
      %bx_c8 = arith.constant 8 : index
      %bx_zero = arith.constant 0.0 : !pme_real
      %bx_one = arith.constant 1.0 : !pme_real
      scf.for %bx_j = %bx_c0 to %bx_c8 step %bx_c1 {
        memref.store %bx_zero, %wx[%bx_j] : memref<8x!pme_real>
      }
      %bx_omw = arith.subf %bx_one, %px_wr : !pme_real
      memref.store %bx_omw, %wx[%bx_c0] : memref<8x!pme_real>
      memref.store %px_wr, %wx[%bx_c1] : memref<8x!pme_real>
      scf.for %bx_k = %bx_c3 to %order step %bx_c1 {
      %bx_r_km1 = arith.subi %bx_k, %bx_c1 : index
      %bx_r_km2 = arith.subi %bx_k, %bx_c2 : index
      %bx_r_km1i = arith.index_cast %bx_r_km1 : index to i64
      %bx_r_km1f = arith.sitofp %bx_r_km1i : i64 to !pme_real
      %bx_r_div = arith.divf %bx_one, %bx_r_km1f : !pme_real
      %bx_r_ki = arith.index_cast %bx_k : index to i64
      %bx_r_kf = arith.sitofp %bx_r_ki : i64 to !pme_real
      %bx_r_last = memref.load %wx[%bx_r_km2] : memref<8x!pme_real>
      %bx_r_dw = arith.mulf %bx_r_div, %px_wr : !pme_real
      %bx_r_top = arith.mulf %bx_r_dw, %bx_r_last : !pme_real
      memref.store %bx_r_top, %wx[%bx_r_km1] : memref<8x!pme_real>
      scf.for %bx_r_j = %bx_c1 to %bx_r_km1 step %bx_c1 {
        %bx_r_ji = arith.index_cast %bx_r_j : index to i64
        %bx_r_jf = arith.sitofp %bx_r_ji : i64 to !pme_real
        %bx_r_at = arith.subi %bx_r_km1, %bx_r_j : index
        %bx_r_below = arith.subi %bx_r_at, %bx_c1 : index
        %bx_r_lo = memref.load %wx[%bx_r_below] : memref<8x!pme_real>
        %bx_r_hi = memref.load %wx[%bx_r_at] : memref<8x!pme_real>
        %bx_r_wj = arith.addf %px_wr, %bx_r_jf : !pme_real
        %bx_r_kj = arith.subf %bx_r_kf, %bx_r_jf : !pme_real
        %bx_r_kjw = arith.subf %bx_r_kj, %px_wr : !pme_real
        %bx_r_t1 = arith.mulf %bx_r_wj, %bx_r_lo : !pme_real
        %bx_r_t2 = arith.mulf %bx_r_kjw, %bx_r_hi : !pme_real
        %bx_r_sum = arith.addf %bx_r_t1, %bx_r_t2 : !pme_real
        %bx_r_value = arith.mulf %bx_r_div, %bx_r_sum : !pme_real
        memref.store %bx_r_value, %wx[%bx_r_at] : memref<8x!pme_real>
      }
      %bx_r_first = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_r_omw = arith.subf %bx_one, %px_wr : !pme_real
      %bx_r_d0 = arith.mulf %bx_r_div, %bx_r_omw : !pme_real
      %bx_r_bottom = arith.mulf %bx_r_d0, %bx_r_first : !pme_real
      memref.store %bx_r_bottom, %wx[%bx_c0] : memref<8x!pme_real>
      }
      %bx_f_km1 = arith.subi %order, %bx_c1 : index
      %bx_f_km2 = arith.subi %order, %bx_c2 : index
      %bx_f_km1i = arith.index_cast %bx_f_km1 : index to i64
      %bx_f_km1f = arith.sitofp %bx_f_km1i : i64 to !pme_real
      %bx_f_div = arith.divf %bx_one, %bx_f_km1f : !pme_real
      %bx_f_ki = arith.index_cast %order : index to i64
      %bx_f_kf = arith.sitofp %bx_f_ki : i64 to !pme_real
      %bx_f_last = memref.load %wx[%bx_f_km2] : memref<8x!pme_real>
      %bx_f_dw = arith.mulf %bx_f_div, %px_wr : !pme_real
      %bx_f_top = arith.mulf %bx_f_dw, %bx_f_last : !pme_real
      memref.store %bx_f_top, %wx[%bx_f_km1] : memref<8x!pme_real>
      scf.for %bx_f_j = %bx_c1 to %bx_f_km1 step %bx_c1 {
        %bx_f_ji = arith.index_cast %bx_f_j : index to i64
        %bx_f_jf = arith.sitofp %bx_f_ji : i64 to !pme_real
        %bx_f_at = arith.subi %bx_f_km1, %bx_f_j : index
        %bx_f_below = arith.subi %bx_f_at, %bx_c1 : index
        %bx_f_lo = memref.load %wx[%bx_f_below] : memref<8x!pme_real>
        %bx_f_hi = memref.load %wx[%bx_f_at] : memref<8x!pme_real>
        %bx_f_wj = arith.addf %px_wr, %bx_f_jf : !pme_real
        %bx_f_kj = arith.subf %bx_f_kf, %bx_f_jf : !pme_real
        %bx_f_kjw = arith.subf %bx_f_kj, %px_wr : !pme_real
        %bx_f_t1 = arith.mulf %bx_f_wj, %bx_f_lo : !pme_real
        %bx_f_t2 = arith.mulf %bx_f_kjw, %bx_f_hi : !pme_real
        %bx_f_sum = arith.addf %bx_f_t1, %bx_f_t2 : !pme_real
        %bx_f_value = arith.mulf %bx_f_div, %bx_f_sum : !pme_real
        memref.store %bx_f_value, %wx[%bx_f_at] : memref<8x!pme_real>
      }
      %bx_f_first = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_f_omw = arith.subf %bx_one, %px_wr : !pme_real
      %bx_f_d0 = arith.mulf %bx_f_div, %bx_f_omw : !pme_real
      %bx_f_bottom = arith.mulf %bx_f_d0, %bx_f_first : !pme_real
      memref.store %bx_f_bottom, %wx[%bx_c0] : memref<8x!pme_real>
      %py_s = arith.mulf %yi, %ily : f64
      %py_fs = math.floor %py_s : f64
      %py_frac = arith.subf %py_s, %py_fs : f64
      %py_ki = arith.index_cast %k2 : index to i64
      %py_kf = arith.sitofp %py_ki : i64 to f64
      %py_u = arith.mulf %py_frac, %py_kf : f64
      %py_fu = math.floor %py_u : f64
      %py_w = arith.subf %py_u, %py_fu : f64
      %py_bi = arith.fptosi %py_fu : f64 to i64
      %py_b = arith.index_cast %py_bi : i64 to index
      %py_bk = arith.addi %py_b, %k2 : index
      %py_bkn = arith.subi %py_bk, %order : index
      %py_c1p = arith.constant 1 : index
      %py_start0 = arith.addi %py_bkn, %py_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %py_start = arith.remui %py_start0, %k2 : index
      %py_wr = PME_F64_TO_REAL %py_w : f64 to !pme_real
      %by_c0 = arith.constant 0 : index
      %by_c1 = arith.constant 1 : index
      %by_c2 = arith.constant 2 : index
      %by_c3 = arith.constant 3 : index
      %by_c8 = arith.constant 8 : index
      %by_zero = arith.constant 0.0 : !pme_real
      %by_one = arith.constant 1.0 : !pme_real
      scf.for %by_j = %by_c0 to %by_c8 step %by_c1 {
        memref.store %by_zero, %wy[%by_j] : memref<8x!pme_real>
      }
      %by_omw = arith.subf %by_one, %py_wr : !pme_real
      memref.store %by_omw, %wy[%by_c0] : memref<8x!pme_real>
      memref.store %py_wr, %wy[%by_c1] : memref<8x!pme_real>
      scf.for %by_k = %by_c3 to %order step %by_c1 {
      %by_r_km1 = arith.subi %by_k, %by_c1 : index
      %by_r_km2 = arith.subi %by_k, %by_c2 : index
      %by_r_km1i = arith.index_cast %by_r_km1 : index to i64
      %by_r_km1f = arith.sitofp %by_r_km1i : i64 to !pme_real
      %by_r_div = arith.divf %by_one, %by_r_km1f : !pme_real
      %by_r_ki = arith.index_cast %by_k : index to i64
      %by_r_kf = arith.sitofp %by_r_ki : i64 to !pme_real
      %by_r_last = memref.load %wy[%by_r_km2] : memref<8x!pme_real>
      %by_r_dw = arith.mulf %by_r_div, %py_wr : !pme_real
      %by_r_top = arith.mulf %by_r_dw, %by_r_last : !pme_real
      memref.store %by_r_top, %wy[%by_r_km1] : memref<8x!pme_real>
      scf.for %by_r_j = %by_c1 to %by_r_km1 step %by_c1 {
        %by_r_ji = arith.index_cast %by_r_j : index to i64
        %by_r_jf = arith.sitofp %by_r_ji : i64 to !pme_real
        %by_r_at = arith.subi %by_r_km1, %by_r_j : index
        %by_r_below = arith.subi %by_r_at, %by_c1 : index
        %by_r_lo = memref.load %wy[%by_r_below] : memref<8x!pme_real>
        %by_r_hi = memref.load %wy[%by_r_at] : memref<8x!pme_real>
        %by_r_wj = arith.addf %py_wr, %by_r_jf : !pme_real
        %by_r_kj = arith.subf %by_r_kf, %by_r_jf : !pme_real
        %by_r_kjw = arith.subf %by_r_kj, %py_wr : !pme_real
        %by_r_t1 = arith.mulf %by_r_wj, %by_r_lo : !pme_real
        %by_r_t2 = arith.mulf %by_r_kjw, %by_r_hi : !pme_real
        %by_r_sum = arith.addf %by_r_t1, %by_r_t2 : !pme_real
        %by_r_value = arith.mulf %by_r_div, %by_r_sum : !pme_real
        memref.store %by_r_value, %wy[%by_r_at] : memref<8x!pme_real>
      }
      %by_r_first = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_r_omw = arith.subf %by_one, %py_wr : !pme_real
      %by_r_d0 = arith.mulf %by_r_div, %by_r_omw : !pme_real
      %by_r_bottom = arith.mulf %by_r_d0, %by_r_first : !pme_real
      memref.store %by_r_bottom, %wy[%by_c0] : memref<8x!pme_real>
      }
      %by_f_km1 = arith.subi %order, %by_c1 : index
      %by_f_km2 = arith.subi %order, %by_c2 : index
      %by_f_km1i = arith.index_cast %by_f_km1 : index to i64
      %by_f_km1f = arith.sitofp %by_f_km1i : i64 to !pme_real
      %by_f_div = arith.divf %by_one, %by_f_km1f : !pme_real
      %by_f_ki = arith.index_cast %order : index to i64
      %by_f_kf = arith.sitofp %by_f_ki : i64 to !pme_real
      %by_f_last = memref.load %wy[%by_f_km2] : memref<8x!pme_real>
      %by_f_dw = arith.mulf %by_f_div, %py_wr : !pme_real
      %by_f_top = arith.mulf %by_f_dw, %by_f_last : !pme_real
      memref.store %by_f_top, %wy[%by_f_km1] : memref<8x!pme_real>
      scf.for %by_f_j = %by_c1 to %by_f_km1 step %by_c1 {
        %by_f_ji = arith.index_cast %by_f_j : index to i64
        %by_f_jf = arith.sitofp %by_f_ji : i64 to !pme_real
        %by_f_at = arith.subi %by_f_km1, %by_f_j : index
        %by_f_below = arith.subi %by_f_at, %by_c1 : index
        %by_f_lo = memref.load %wy[%by_f_below] : memref<8x!pme_real>
        %by_f_hi = memref.load %wy[%by_f_at] : memref<8x!pme_real>
        %by_f_wj = arith.addf %py_wr, %by_f_jf : !pme_real
        %by_f_kj = arith.subf %by_f_kf, %by_f_jf : !pme_real
        %by_f_kjw = arith.subf %by_f_kj, %py_wr : !pme_real
        %by_f_t1 = arith.mulf %by_f_wj, %by_f_lo : !pme_real
        %by_f_t2 = arith.mulf %by_f_kjw, %by_f_hi : !pme_real
        %by_f_sum = arith.addf %by_f_t1, %by_f_t2 : !pme_real
        %by_f_value = arith.mulf %by_f_div, %by_f_sum : !pme_real
        memref.store %by_f_value, %wy[%by_f_at] : memref<8x!pme_real>
      }
      %by_f_first = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_f_omw = arith.subf %by_one, %py_wr : !pme_real
      %by_f_d0 = arith.mulf %by_f_div, %by_f_omw : !pme_real
      %by_f_bottom = arith.mulf %by_f_d0, %by_f_first : !pme_real
      memref.store %by_f_bottom, %wy[%by_c0] : memref<8x!pme_real>
      %pz_s = arith.mulf %zi, %ilz : f64
      %pz_fs = math.floor %pz_s : f64
      %pz_frac = arith.subf %pz_s, %pz_fs : f64
      %pz_ki = arith.index_cast %k3 : index to i64
      %pz_kf = arith.sitofp %pz_ki : i64 to f64
      %pz_u = arith.mulf %pz_frac, %pz_kf : f64
      %pz_fu = math.floor %pz_u : f64
      %pz_w = arith.subf %pz_u, %pz_fu : f64
      %pz_bi = arith.fptosi %pz_fu : f64 to i64
      %pz_b = arith.index_cast %pz_bi : i64 to index
      %pz_bk = arith.addi %pz_b, %k3 : index
      %pz_bkn = arith.subi %pz_bk, %order : index
      %pz_c1p = arith.constant 1 : index
      %pz_start0 = arith.addi %pz_bkn, %pz_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %pz_start = arith.remui %pz_start0, %k3 : index
      %pz_wr = PME_F64_TO_REAL %pz_w : f64 to !pme_real
      %bz_c0 = arith.constant 0 : index
      %bz_c1 = arith.constant 1 : index
      %bz_c2 = arith.constant 2 : index
      %bz_c3 = arith.constant 3 : index
      %bz_c8 = arith.constant 8 : index
      %bz_zero = arith.constant 0.0 : !pme_real
      %bz_one = arith.constant 1.0 : !pme_real
      scf.for %bz_j = %bz_c0 to %bz_c8 step %bz_c1 {
        memref.store %bz_zero, %wz[%bz_j] : memref<8x!pme_real>
      }
      %bz_omw = arith.subf %bz_one, %pz_wr : !pme_real
      memref.store %bz_omw, %wz[%bz_c0] : memref<8x!pme_real>
      memref.store %pz_wr, %wz[%bz_c1] : memref<8x!pme_real>
      scf.for %bz_k = %bz_c3 to %order step %bz_c1 {
      %bz_r_km1 = arith.subi %bz_k, %bz_c1 : index
      %bz_r_km2 = arith.subi %bz_k, %bz_c2 : index
      %bz_r_km1i = arith.index_cast %bz_r_km1 : index to i64
      %bz_r_km1f = arith.sitofp %bz_r_km1i : i64 to !pme_real
      %bz_r_div = arith.divf %bz_one, %bz_r_km1f : !pme_real
      %bz_r_ki = arith.index_cast %bz_k : index to i64
      %bz_r_kf = arith.sitofp %bz_r_ki : i64 to !pme_real
      %bz_r_last = memref.load %wz[%bz_r_km2] : memref<8x!pme_real>
      %bz_r_dw = arith.mulf %bz_r_div, %pz_wr : !pme_real
      %bz_r_top = arith.mulf %bz_r_dw, %bz_r_last : !pme_real
      memref.store %bz_r_top, %wz[%bz_r_km1] : memref<8x!pme_real>
      scf.for %bz_r_j = %bz_c1 to %bz_r_km1 step %bz_c1 {
        %bz_r_ji = arith.index_cast %bz_r_j : index to i64
        %bz_r_jf = arith.sitofp %bz_r_ji : i64 to !pme_real
        %bz_r_at = arith.subi %bz_r_km1, %bz_r_j : index
        %bz_r_below = arith.subi %bz_r_at, %bz_c1 : index
        %bz_r_lo = memref.load %wz[%bz_r_below] : memref<8x!pme_real>
        %bz_r_hi = memref.load %wz[%bz_r_at] : memref<8x!pme_real>
        %bz_r_wj = arith.addf %pz_wr, %bz_r_jf : !pme_real
        %bz_r_kj = arith.subf %bz_r_kf, %bz_r_jf : !pme_real
        %bz_r_kjw = arith.subf %bz_r_kj, %pz_wr : !pme_real
        %bz_r_t1 = arith.mulf %bz_r_wj, %bz_r_lo : !pme_real
        %bz_r_t2 = arith.mulf %bz_r_kjw, %bz_r_hi : !pme_real
        %bz_r_sum = arith.addf %bz_r_t1, %bz_r_t2 : !pme_real
        %bz_r_value = arith.mulf %bz_r_div, %bz_r_sum : !pme_real
        memref.store %bz_r_value, %wz[%bz_r_at] : memref<8x!pme_real>
      }
      %bz_r_first = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_r_omw = arith.subf %bz_one, %pz_wr : !pme_real
      %bz_r_d0 = arith.mulf %bz_r_div, %bz_r_omw : !pme_real
      %bz_r_bottom = arith.mulf %bz_r_d0, %bz_r_first : !pme_real
      memref.store %bz_r_bottom, %wz[%bz_c0] : memref<8x!pme_real>
      }
      %bz_f_km1 = arith.subi %order, %bz_c1 : index
      %bz_f_km2 = arith.subi %order, %bz_c2 : index
      %bz_f_km1i = arith.index_cast %bz_f_km1 : index to i64
      %bz_f_km1f = arith.sitofp %bz_f_km1i : i64 to !pme_real
      %bz_f_div = arith.divf %bz_one, %bz_f_km1f : !pme_real
      %bz_f_ki = arith.index_cast %order : index to i64
      %bz_f_kf = arith.sitofp %bz_f_ki : i64 to !pme_real
      %bz_f_last = memref.load %wz[%bz_f_km2] : memref<8x!pme_real>
      %bz_f_dw = arith.mulf %bz_f_div, %pz_wr : !pme_real
      %bz_f_top = arith.mulf %bz_f_dw, %bz_f_last : !pme_real
      memref.store %bz_f_top, %wz[%bz_f_km1] : memref<8x!pme_real>
      scf.for %bz_f_j = %bz_c1 to %bz_f_km1 step %bz_c1 {
        %bz_f_ji = arith.index_cast %bz_f_j : index to i64
        %bz_f_jf = arith.sitofp %bz_f_ji : i64 to !pme_real
        %bz_f_at = arith.subi %bz_f_km1, %bz_f_j : index
        %bz_f_below = arith.subi %bz_f_at, %bz_c1 : index
        %bz_f_lo = memref.load %wz[%bz_f_below] : memref<8x!pme_real>
        %bz_f_hi = memref.load %wz[%bz_f_at] : memref<8x!pme_real>
        %bz_f_wj = arith.addf %pz_wr, %bz_f_jf : !pme_real
        %bz_f_kj = arith.subf %bz_f_kf, %bz_f_jf : !pme_real
        %bz_f_kjw = arith.subf %bz_f_kj, %pz_wr : !pme_real
        %bz_f_t1 = arith.mulf %bz_f_wj, %bz_f_lo : !pme_real
        %bz_f_t2 = arith.mulf %bz_f_kjw, %bz_f_hi : !pme_real
        %bz_f_sum = arith.addf %bz_f_t1, %bz_f_t2 : !pme_real
        %bz_f_value = arith.mulf %bz_f_div, %bz_f_sum : !pme_real
        memref.store %bz_f_value, %wz[%bz_f_at] : memref<8x!pme_real>
      }
      %bz_f_first = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_f_omw = arith.subf %bz_one, %pz_wr : !pme_real
      %bz_f_d0 = arith.mulf %bz_f_div, %bz_f_omw : !pme_real
      %bz_f_bottom = arith.mulf %bz_f_d0, %bz_f_first : !pme_real
      memref.store %bz_f_bottom, %wz[%bz_c0] : memref<8x!pme_real>
      %scale = arith.constant 1099511627776.0 : !pme_real
      %qscaled = arith.mulf %qi, %scale : !pme_real
      %eight = arith.constant 8 : i64
      %gridindex = memref.extract_aligned_pointer_as_index %grid : memref<?xi64, 1> -> index
      // The grid is a buffer of its own, with no offset.
      %gridbase = arith.index_cast %gridindex : index to i64
      %j0 = arith.constant 0 : index
      %j1c = arith.constant 1 : index
      // The point of this thread along z; the threads of a particle add to
      // points next to one another in memory.
      %g3s = arith.addi %pz_start, %j3 : index
      %g3w = arith.subi %g3s, %k3 : index
      %g3over = arith.cmpi uge, %g3s, %k3 : index
      %g3 = arith.select %g3over, %g3w, %g3s : index
      %w3 = memref.load %wz[%j3] : memref<8x!pme_real>
      %q3 = arith.mulf %qscaled, %w3 : !pme_real
      scf.for %j1 = %j0 to %order step %j1c {
        %g1s = arith.addi %px_start, %j1 : index
        %g1w = arith.subi %g1s, %k1 : index
        %g1over = arith.cmpi uge, %g1s, %k1 : index
        %g1 = arith.select %g1over, %g1w, %g1s : index
        %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
        %q13 = arith.mulf %q3, %w1 : !pme_real
        scf.for %j2 = %j0 to %order step %j1c {
          %g2s = arith.addi %py_start, %j2 : index
          %g2w = arith.subi %g2s, %k2 : index
          %g2over = arith.cmpi uge, %g2s, %k2 : index
          %g2 = arith.select %g2over, %g2w, %g2s : index
          %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
          %value = arith.mulf %q13, %w2 : !pme_real
          %row1 = arith.muli %g1, %k2 : index
          %row = arith.addi %row1, %g2 : index
          %gbase = arith.muli %row, %k3 : index
            %rounded = math.roundeven %value : !pme_real
            %fixed = arith.fptosi %rounded : !pme_real to i64
          %at = arith.addi %gbase, %g3 : index
          // A relaxed atomic at the scope of the device: the sum needs no
          // order, and one of the system would wait for the host.
          %ati = arith.index_cast %at : index to i64
          %offset = arith.muli %ati, %eight : i64
          %address = arith.addi %gridbase, %offset : i64
          %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
            %old = llvm.atomicrmw add %pointer, %fixed syncscope("device") monotonic : !llvm.ptr<1>, i64
        }
      }
    }
    gpu.terminator
  }
  return
}

// Spreads the charges to `grid`, in !pme_real, with floating-point atomics, whose sum depends on
// the order of the threads (the default mode, D84).
func.func private @mdrt_gpu_pme_spread_float(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %box: vector<3xf64>, %grid: memref<?x!pme_real, 1>,
                                       %k1: index, %k2: index, %k3: index, %n: index) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %points = memref.dim %grid, %c0 : memref<?x!pme_real, 1>
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %spread_lanes = arith.constant PME_ORDER : index
  %spread = arith.muli %count, %spread_lanes : index
  %blocks_points = func.call @mdrt_gpu_pme_blocks(%points) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_points, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %points : index
    scf.if %inside {
      %none = arith.constant 0.0 : !pme_real
      memref.store %none, %grid[%item] : memref<?x!pme_real, 1>
    }
    gpu.terminator
  }
  %blocks_spread = func.call @mdrt_gpu_pme_blocks(%spread) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_spread, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %spread : index
    scf.if %inside {
      %lanes = arith.constant PME_ORDER : index
      %i = arith.divui %item, %lanes : index
      %j3 = arith.remui %item, %lanes : index
      %i0 = arith.constant 0 : index
      %i1 = arith.constant 1 : index
      %i2 = arith.constant 2 : index
      // The order of the splines, a constant of the instance, so that the loops
      // over it unroll and the splines are held in registers.
      %order = arith.constant PME_ORDER : index
      %wx = memref.alloca() : memref<8x!pme_real>
      %wy = memref.alloca() : memref<8x!pme_real>
      %wz = memref.alloca() : memref<8x!pme_real>
      %xs = memref.load %x[%i, %i0] : memref<?x3x!pme_pos, 1>
      %ys = memref.load %x[%i, %i1] : memref<?x3x!pme_pos, 1>
      %zs = memref.load %x[%i, %i2] : memref<?x3x!pme_pos, 1>
      %qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
      %xi = PME_EXTEND_POS %xs : !pme_pos to f64
      %yi = PME_EXTEND_POS %ys : !pme_pos to f64
      %zi = PME_EXTEND_POS %zs : !pme_pos to f64
      %qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real
      %px_s = arith.mulf %xi, %ilx : f64
      %px_fs = math.floor %px_s : f64
      %px_frac = arith.subf %px_s, %px_fs : f64
      %px_ki = arith.index_cast %k1 : index to i64
      %px_kf = arith.sitofp %px_ki : i64 to f64
      %px_u = arith.mulf %px_frac, %px_kf : f64
      %px_fu = math.floor %px_u : f64
      %px_w = arith.subf %px_u, %px_fu : f64
      %px_bi = arith.fptosi %px_fu : f64 to i64
      %px_b = arith.index_cast %px_bi : i64 to index
      %px_bk = arith.addi %px_b, %k1 : index
      %px_bkn = arith.subi %px_bk, %order : index
      %px_c1p = arith.constant 1 : index
      %px_start0 = arith.addi %px_bkn, %px_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %px_start = arith.remui %px_start0, %k1 : index
      %px_wr = PME_F64_TO_REAL %px_w : f64 to !pme_real
      %bx_c0 = arith.constant 0 : index
      %bx_c1 = arith.constant 1 : index
      %bx_c2 = arith.constant 2 : index
      %bx_c3 = arith.constant 3 : index
      %bx_c8 = arith.constant 8 : index
      %bx_zero = arith.constant 0.0 : !pme_real
      %bx_one = arith.constant 1.0 : !pme_real
      scf.for %bx_j = %bx_c0 to %bx_c8 step %bx_c1 {
        memref.store %bx_zero, %wx[%bx_j] : memref<8x!pme_real>
      }
      %bx_omw = arith.subf %bx_one, %px_wr : !pme_real
      memref.store %bx_omw, %wx[%bx_c0] : memref<8x!pme_real>
      memref.store %px_wr, %wx[%bx_c1] : memref<8x!pme_real>
      scf.for %bx_k = %bx_c3 to %order step %bx_c1 {
      %bx_r_km1 = arith.subi %bx_k, %bx_c1 : index
      %bx_r_km2 = arith.subi %bx_k, %bx_c2 : index
      %bx_r_km1i = arith.index_cast %bx_r_km1 : index to i64
      %bx_r_km1f = arith.sitofp %bx_r_km1i : i64 to !pme_real
      %bx_r_div = arith.divf %bx_one, %bx_r_km1f : !pme_real
      %bx_r_ki = arith.index_cast %bx_k : index to i64
      %bx_r_kf = arith.sitofp %bx_r_ki : i64 to !pme_real
      %bx_r_last = memref.load %wx[%bx_r_km2] : memref<8x!pme_real>
      %bx_r_dw = arith.mulf %bx_r_div, %px_wr : !pme_real
      %bx_r_top = arith.mulf %bx_r_dw, %bx_r_last : !pme_real
      memref.store %bx_r_top, %wx[%bx_r_km1] : memref<8x!pme_real>
      scf.for %bx_r_j = %bx_c1 to %bx_r_km1 step %bx_c1 {
        %bx_r_ji = arith.index_cast %bx_r_j : index to i64
        %bx_r_jf = arith.sitofp %bx_r_ji : i64 to !pme_real
        %bx_r_at = arith.subi %bx_r_km1, %bx_r_j : index
        %bx_r_below = arith.subi %bx_r_at, %bx_c1 : index
        %bx_r_lo = memref.load %wx[%bx_r_below] : memref<8x!pme_real>
        %bx_r_hi = memref.load %wx[%bx_r_at] : memref<8x!pme_real>
        %bx_r_wj = arith.addf %px_wr, %bx_r_jf : !pme_real
        %bx_r_kj = arith.subf %bx_r_kf, %bx_r_jf : !pme_real
        %bx_r_kjw = arith.subf %bx_r_kj, %px_wr : !pme_real
        %bx_r_t1 = arith.mulf %bx_r_wj, %bx_r_lo : !pme_real
        %bx_r_t2 = arith.mulf %bx_r_kjw, %bx_r_hi : !pme_real
        %bx_r_sum = arith.addf %bx_r_t1, %bx_r_t2 : !pme_real
        %bx_r_value = arith.mulf %bx_r_div, %bx_r_sum : !pme_real
        memref.store %bx_r_value, %wx[%bx_r_at] : memref<8x!pme_real>
      }
      %bx_r_first = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_r_omw = arith.subf %bx_one, %px_wr : !pme_real
      %bx_r_d0 = arith.mulf %bx_r_div, %bx_r_omw : !pme_real
      %bx_r_bottom = arith.mulf %bx_r_d0, %bx_r_first : !pme_real
      memref.store %bx_r_bottom, %wx[%bx_c0] : memref<8x!pme_real>
      }
      %bx_f_km1 = arith.subi %order, %bx_c1 : index
      %bx_f_km2 = arith.subi %order, %bx_c2 : index
      %bx_f_km1i = arith.index_cast %bx_f_km1 : index to i64
      %bx_f_km1f = arith.sitofp %bx_f_km1i : i64 to !pme_real
      %bx_f_div = arith.divf %bx_one, %bx_f_km1f : !pme_real
      %bx_f_ki = arith.index_cast %order : index to i64
      %bx_f_kf = arith.sitofp %bx_f_ki : i64 to !pme_real
      %bx_f_last = memref.load %wx[%bx_f_km2] : memref<8x!pme_real>
      %bx_f_dw = arith.mulf %bx_f_div, %px_wr : !pme_real
      %bx_f_top = arith.mulf %bx_f_dw, %bx_f_last : !pme_real
      memref.store %bx_f_top, %wx[%bx_f_km1] : memref<8x!pme_real>
      scf.for %bx_f_j = %bx_c1 to %bx_f_km1 step %bx_c1 {
        %bx_f_ji = arith.index_cast %bx_f_j : index to i64
        %bx_f_jf = arith.sitofp %bx_f_ji : i64 to !pme_real
        %bx_f_at = arith.subi %bx_f_km1, %bx_f_j : index
        %bx_f_below = arith.subi %bx_f_at, %bx_c1 : index
        %bx_f_lo = memref.load %wx[%bx_f_below] : memref<8x!pme_real>
        %bx_f_hi = memref.load %wx[%bx_f_at] : memref<8x!pme_real>
        %bx_f_wj = arith.addf %px_wr, %bx_f_jf : !pme_real
        %bx_f_kj = arith.subf %bx_f_kf, %bx_f_jf : !pme_real
        %bx_f_kjw = arith.subf %bx_f_kj, %px_wr : !pme_real
        %bx_f_t1 = arith.mulf %bx_f_wj, %bx_f_lo : !pme_real
        %bx_f_t2 = arith.mulf %bx_f_kjw, %bx_f_hi : !pme_real
        %bx_f_sum = arith.addf %bx_f_t1, %bx_f_t2 : !pme_real
        %bx_f_value = arith.mulf %bx_f_div, %bx_f_sum : !pme_real
        memref.store %bx_f_value, %wx[%bx_f_at] : memref<8x!pme_real>
      }
      %bx_f_first = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_f_omw = arith.subf %bx_one, %px_wr : !pme_real
      %bx_f_d0 = arith.mulf %bx_f_div, %bx_f_omw : !pme_real
      %bx_f_bottom = arith.mulf %bx_f_d0, %bx_f_first : !pme_real
      memref.store %bx_f_bottom, %wx[%bx_c0] : memref<8x!pme_real>
      %py_s = arith.mulf %yi, %ily : f64
      %py_fs = math.floor %py_s : f64
      %py_frac = arith.subf %py_s, %py_fs : f64
      %py_ki = arith.index_cast %k2 : index to i64
      %py_kf = arith.sitofp %py_ki : i64 to f64
      %py_u = arith.mulf %py_frac, %py_kf : f64
      %py_fu = math.floor %py_u : f64
      %py_w = arith.subf %py_u, %py_fu : f64
      %py_bi = arith.fptosi %py_fu : f64 to i64
      %py_b = arith.index_cast %py_bi : i64 to index
      %py_bk = arith.addi %py_b, %k2 : index
      %py_bkn = arith.subi %py_bk, %order : index
      %py_c1p = arith.constant 1 : index
      %py_start0 = arith.addi %py_bkn, %py_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %py_start = arith.remui %py_start0, %k2 : index
      %py_wr = PME_F64_TO_REAL %py_w : f64 to !pme_real
      %by_c0 = arith.constant 0 : index
      %by_c1 = arith.constant 1 : index
      %by_c2 = arith.constant 2 : index
      %by_c3 = arith.constant 3 : index
      %by_c8 = arith.constant 8 : index
      %by_zero = arith.constant 0.0 : !pme_real
      %by_one = arith.constant 1.0 : !pme_real
      scf.for %by_j = %by_c0 to %by_c8 step %by_c1 {
        memref.store %by_zero, %wy[%by_j] : memref<8x!pme_real>
      }
      %by_omw = arith.subf %by_one, %py_wr : !pme_real
      memref.store %by_omw, %wy[%by_c0] : memref<8x!pme_real>
      memref.store %py_wr, %wy[%by_c1] : memref<8x!pme_real>
      scf.for %by_k = %by_c3 to %order step %by_c1 {
      %by_r_km1 = arith.subi %by_k, %by_c1 : index
      %by_r_km2 = arith.subi %by_k, %by_c2 : index
      %by_r_km1i = arith.index_cast %by_r_km1 : index to i64
      %by_r_km1f = arith.sitofp %by_r_km1i : i64 to !pme_real
      %by_r_div = arith.divf %by_one, %by_r_km1f : !pme_real
      %by_r_ki = arith.index_cast %by_k : index to i64
      %by_r_kf = arith.sitofp %by_r_ki : i64 to !pme_real
      %by_r_last = memref.load %wy[%by_r_km2] : memref<8x!pme_real>
      %by_r_dw = arith.mulf %by_r_div, %py_wr : !pme_real
      %by_r_top = arith.mulf %by_r_dw, %by_r_last : !pme_real
      memref.store %by_r_top, %wy[%by_r_km1] : memref<8x!pme_real>
      scf.for %by_r_j = %by_c1 to %by_r_km1 step %by_c1 {
        %by_r_ji = arith.index_cast %by_r_j : index to i64
        %by_r_jf = arith.sitofp %by_r_ji : i64 to !pme_real
        %by_r_at = arith.subi %by_r_km1, %by_r_j : index
        %by_r_below = arith.subi %by_r_at, %by_c1 : index
        %by_r_lo = memref.load %wy[%by_r_below] : memref<8x!pme_real>
        %by_r_hi = memref.load %wy[%by_r_at] : memref<8x!pme_real>
        %by_r_wj = arith.addf %py_wr, %by_r_jf : !pme_real
        %by_r_kj = arith.subf %by_r_kf, %by_r_jf : !pme_real
        %by_r_kjw = arith.subf %by_r_kj, %py_wr : !pme_real
        %by_r_t1 = arith.mulf %by_r_wj, %by_r_lo : !pme_real
        %by_r_t2 = arith.mulf %by_r_kjw, %by_r_hi : !pme_real
        %by_r_sum = arith.addf %by_r_t1, %by_r_t2 : !pme_real
        %by_r_value = arith.mulf %by_r_div, %by_r_sum : !pme_real
        memref.store %by_r_value, %wy[%by_r_at] : memref<8x!pme_real>
      }
      %by_r_first = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_r_omw = arith.subf %by_one, %py_wr : !pme_real
      %by_r_d0 = arith.mulf %by_r_div, %by_r_omw : !pme_real
      %by_r_bottom = arith.mulf %by_r_d0, %by_r_first : !pme_real
      memref.store %by_r_bottom, %wy[%by_c0] : memref<8x!pme_real>
      }
      %by_f_km1 = arith.subi %order, %by_c1 : index
      %by_f_km2 = arith.subi %order, %by_c2 : index
      %by_f_km1i = arith.index_cast %by_f_km1 : index to i64
      %by_f_km1f = arith.sitofp %by_f_km1i : i64 to !pme_real
      %by_f_div = arith.divf %by_one, %by_f_km1f : !pme_real
      %by_f_ki = arith.index_cast %order : index to i64
      %by_f_kf = arith.sitofp %by_f_ki : i64 to !pme_real
      %by_f_last = memref.load %wy[%by_f_km2] : memref<8x!pme_real>
      %by_f_dw = arith.mulf %by_f_div, %py_wr : !pme_real
      %by_f_top = arith.mulf %by_f_dw, %by_f_last : !pme_real
      memref.store %by_f_top, %wy[%by_f_km1] : memref<8x!pme_real>
      scf.for %by_f_j = %by_c1 to %by_f_km1 step %by_c1 {
        %by_f_ji = arith.index_cast %by_f_j : index to i64
        %by_f_jf = arith.sitofp %by_f_ji : i64 to !pme_real
        %by_f_at = arith.subi %by_f_km1, %by_f_j : index
        %by_f_below = arith.subi %by_f_at, %by_c1 : index
        %by_f_lo = memref.load %wy[%by_f_below] : memref<8x!pme_real>
        %by_f_hi = memref.load %wy[%by_f_at] : memref<8x!pme_real>
        %by_f_wj = arith.addf %py_wr, %by_f_jf : !pme_real
        %by_f_kj = arith.subf %by_f_kf, %by_f_jf : !pme_real
        %by_f_kjw = arith.subf %by_f_kj, %py_wr : !pme_real
        %by_f_t1 = arith.mulf %by_f_wj, %by_f_lo : !pme_real
        %by_f_t2 = arith.mulf %by_f_kjw, %by_f_hi : !pme_real
        %by_f_sum = arith.addf %by_f_t1, %by_f_t2 : !pme_real
        %by_f_value = arith.mulf %by_f_div, %by_f_sum : !pme_real
        memref.store %by_f_value, %wy[%by_f_at] : memref<8x!pme_real>
      }
      %by_f_first = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_f_omw = arith.subf %by_one, %py_wr : !pme_real
      %by_f_d0 = arith.mulf %by_f_div, %by_f_omw : !pme_real
      %by_f_bottom = arith.mulf %by_f_d0, %by_f_first : !pme_real
      memref.store %by_f_bottom, %wy[%by_c0] : memref<8x!pme_real>
      %pz_s = arith.mulf %zi, %ilz : f64
      %pz_fs = math.floor %pz_s : f64
      %pz_frac = arith.subf %pz_s, %pz_fs : f64
      %pz_ki = arith.index_cast %k3 : index to i64
      %pz_kf = arith.sitofp %pz_ki : i64 to f64
      %pz_u = arith.mulf %pz_frac, %pz_kf : f64
      %pz_fu = math.floor %pz_u : f64
      %pz_w = arith.subf %pz_u, %pz_fu : f64
      %pz_bi = arith.fptosi %pz_fu : f64 to i64
      %pz_b = arith.index_cast %pz_bi : i64 to index
      %pz_bk = arith.addi %pz_b, %k3 : index
      %pz_bkn = arith.subi %pz_bk, %order : index
      %pz_c1p = arith.constant 1 : index
      %pz_start0 = arith.addi %pz_bkn, %pz_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %pz_start = arith.remui %pz_start0, %k3 : index
      %pz_wr = PME_F64_TO_REAL %pz_w : f64 to !pme_real
      %bz_c0 = arith.constant 0 : index
      %bz_c1 = arith.constant 1 : index
      %bz_c2 = arith.constant 2 : index
      %bz_c3 = arith.constant 3 : index
      %bz_c8 = arith.constant 8 : index
      %bz_zero = arith.constant 0.0 : !pme_real
      %bz_one = arith.constant 1.0 : !pme_real
      scf.for %bz_j = %bz_c0 to %bz_c8 step %bz_c1 {
        memref.store %bz_zero, %wz[%bz_j] : memref<8x!pme_real>
      }
      %bz_omw = arith.subf %bz_one, %pz_wr : !pme_real
      memref.store %bz_omw, %wz[%bz_c0] : memref<8x!pme_real>
      memref.store %pz_wr, %wz[%bz_c1] : memref<8x!pme_real>
      scf.for %bz_k = %bz_c3 to %order step %bz_c1 {
      %bz_r_km1 = arith.subi %bz_k, %bz_c1 : index
      %bz_r_km2 = arith.subi %bz_k, %bz_c2 : index
      %bz_r_km1i = arith.index_cast %bz_r_km1 : index to i64
      %bz_r_km1f = arith.sitofp %bz_r_km1i : i64 to !pme_real
      %bz_r_div = arith.divf %bz_one, %bz_r_km1f : !pme_real
      %bz_r_ki = arith.index_cast %bz_k : index to i64
      %bz_r_kf = arith.sitofp %bz_r_ki : i64 to !pme_real
      %bz_r_last = memref.load %wz[%bz_r_km2] : memref<8x!pme_real>
      %bz_r_dw = arith.mulf %bz_r_div, %pz_wr : !pme_real
      %bz_r_top = arith.mulf %bz_r_dw, %bz_r_last : !pme_real
      memref.store %bz_r_top, %wz[%bz_r_km1] : memref<8x!pme_real>
      scf.for %bz_r_j = %bz_c1 to %bz_r_km1 step %bz_c1 {
        %bz_r_ji = arith.index_cast %bz_r_j : index to i64
        %bz_r_jf = arith.sitofp %bz_r_ji : i64 to !pme_real
        %bz_r_at = arith.subi %bz_r_km1, %bz_r_j : index
        %bz_r_below = arith.subi %bz_r_at, %bz_c1 : index
        %bz_r_lo = memref.load %wz[%bz_r_below] : memref<8x!pme_real>
        %bz_r_hi = memref.load %wz[%bz_r_at] : memref<8x!pme_real>
        %bz_r_wj = arith.addf %pz_wr, %bz_r_jf : !pme_real
        %bz_r_kj = arith.subf %bz_r_kf, %bz_r_jf : !pme_real
        %bz_r_kjw = arith.subf %bz_r_kj, %pz_wr : !pme_real
        %bz_r_t1 = arith.mulf %bz_r_wj, %bz_r_lo : !pme_real
        %bz_r_t2 = arith.mulf %bz_r_kjw, %bz_r_hi : !pme_real
        %bz_r_sum = arith.addf %bz_r_t1, %bz_r_t2 : !pme_real
        %bz_r_value = arith.mulf %bz_r_div, %bz_r_sum : !pme_real
        memref.store %bz_r_value, %wz[%bz_r_at] : memref<8x!pme_real>
      }
      %bz_r_first = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_r_omw = arith.subf %bz_one, %pz_wr : !pme_real
      %bz_r_d0 = arith.mulf %bz_r_div, %bz_r_omw : !pme_real
      %bz_r_bottom = arith.mulf %bz_r_d0, %bz_r_first : !pme_real
      memref.store %bz_r_bottom, %wz[%bz_c0] : memref<8x!pme_real>
      }
      %bz_f_km1 = arith.subi %order, %bz_c1 : index
      %bz_f_km2 = arith.subi %order, %bz_c2 : index
      %bz_f_km1i = arith.index_cast %bz_f_km1 : index to i64
      %bz_f_km1f = arith.sitofp %bz_f_km1i : i64 to !pme_real
      %bz_f_div = arith.divf %bz_one, %bz_f_km1f : !pme_real
      %bz_f_ki = arith.index_cast %order : index to i64
      %bz_f_kf = arith.sitofp %bz_f_ki : i64 to !pme_real
      %bz_f_last = memref.load %wz[%bz_f_km2] : memref<8x!pme_real>
      %bz_f_dw = arith.mulf %bz_f_div, %pz_wr : !pme_real
      %bz_f_top = arith.mulf %bz_f_dw, %bz_f_last : !pme_real
      memref.store %bz_f_top, %wz[%bz_f_km1] : memref<8x!pme_real>
      scf.for %bz_f_j = %bz_c1 to %bz_f_km1 step %bz_c1 {
        %bz_f_ji = arith.index_cast %bz_f_j : index to i64
        %bz_f_jf = arith.sitofp %bz_f_ji : i64 to !pme_real
        %bz_f_at = arith.subi %bz_f_km1, %bz_f_j : index
        %bz_f_below = arith.subi %bz_f_at, %bz_c1 : index
        %bz_f_lo = memref.load %wz[%bz_f_below] : memref<8x!pme_real>
        %bz_f_hi = memref.load %wz[%bz_f_at] : memref<8x!pme_real>
        %bz_f_wj = arith.addf %pz_wr, %bz_f_jf : !pme_real
        %bz_f_kj = arith.subf %bz_f_kf, %bz_f_jf : !pme_real
        %bz_f_kjw = arith.subf %bz_f_kj, %pz_wr : !pme_real
        %bz_f_t1 = arith.mulf %bz_f_wj, %bz_f_lo : !pme_real
        %bz_f_t2 = arith.mulf %bz_f_kjw, %bz_f_hi : !pme_real
        %bz_f_sum = arith.addf %bz_f_t1, %bz_f_t2 : !pme_real
        %bz_f_value = arith.mulf %bz_f_div, %bz_f_sum : !pme_real
        memref.store %bz_f_value, %wz[%bz_f_at] : memref<8x!pme_real>
      }
      %bz_f_first = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_f_omw = arith.subf %bz_one, %pz_wr : !pme_real
      %bz_f_d0 = arith.mulf %bz_f_div, %bz_f_omw : !pme_real
      %bz_f_bottom = arith.mulf %bz_f_d0, %bz_f_first : !pme_real
      memref.store %bz_f_bottom, %wz[%bz_c0] : memref<8x!pme_real>
      %scale = arith.constant 1.0 : !pme_real
      %qscaled = arith.mulf %qi, %scale : !pme_real
      %eight = arith.constant PME_REAL_BYTES : i64
      %gridindex = memref.extract_aligned_pointer_as_index %grid : memref<?x!pme_real, 1> -> index
      // The grid is a buffer of its own, with no offset.
      %gridbase = arith.index_cast %gridindex : index to i64
      %j0 = arith.constant 0 : index
      %j1c = arith.constant 1 : index
      // The point of this thread along z; the threads of a particle add to
      // points next to one another in memory.
      %g3s = arith.addi %pz_start, %j3 : index
      %g3w = arith.subi %g3s, %k3 : index
      %g3over = arith.cmpi uge, %g3s, %k3 : index
      %g3 = arith.select %g3over, %g3w, %g3s : index
      %w3 = memref.load %wz[%j3] : memref<8x!pme_real>
      %q3 = arith.mulf %qscaled, %w3 : !pme_real
      scf.for %j1 = %j0 to %order step %j1c {
        %g1s = arith.addi %px_start, %j1 : index
        %g1w = arith.subi %g1s, %k1 : index
        %g1over = arith.cmpi uge, %g1s, %k1 : index
        %g1 = arith.select %g1over, %g1w, %g1s : index
        %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
        %q13 = arith.mulf %q3, %w1 : !pme_real
        scf.for %j2 = %j0 to %order step %j1c {
          %g2s = arith.addi %py_start, %j2 : index
          %g2w = arith.subi %g2s, %k2 : index
          %g2over = arith.cmpi uge, %g2s, %k2 : index
          %g2 = arith.select %g2over, %g2w, %g2s : index
          %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
          %value = arith.mulf %q13, %w2 : !pme_real
          %row1 = arith.muli %g1, %k2 : index
          %row = arith.addi %row1, %g2 : index
          %gbase = arith.muli %row, %k3 : index


          %at = arith.addi %gbase, %g3 : index
          // A relaxed atomic at the scope of the device: the sum needs no
          // order, and one of the system would wait for the host.
          %ati = arith.index_cast %at : index to i64
          %offset = arith.muli %ati, %eight : i64
          %address = arith.addi %gridbase, %offset : i64
          %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
            // An addition without a result: the instance chooses its op,
            // since the NVPTX backend of LLVM expands atomicrmw fadd of f32
            // into a loop of compare-and-swap.
            PME_ATOMIC_ADD %pointer, %value
        }
      }
    }
    gpu.terminator
  }
  return
}

// The grid in !pme_real, from fixed point.
func.func private @mdrt_gpu_pme_real(%grid: memref<?xi64, 1>, %real: memref<?x!pme_real, 1>) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %points = memref.dim %grid, %c0 : memref<?xi64, 1>
  %blocks_points = func.call @mdrt_gpu_pme_blocks(%points) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_points, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %points : index
    scf.if %inside {
      %inverse = arith.constant 9.094947017729282e-13 : !pme_real
      %fixed = memref.load %grid[%item] : memref<?xi64, 1>
      %value = arith.sitofp %fixed : i64 to !pme_real
      %scaled = arith.mulf %value, %inverse : !pme_real
      memref.store %scaled, %real[%item] : memref<?x!pme_real, 1>
    }
    gpu.terminator
  }
  return
}

// Multiplies the half-complex transform `c` by the influence function, which
// it computes from the factors of the edges in `moduli` and the cell, and
// returns the energy and the virial, as @mdrt.pme_convolve does. A thread
// takes a row of the grid, (k1, k2), and writes its sums to `rows`: the
// energy, then the virial xx, xy, xz, yy, yz, zz.
func.func private @mdrt_gpu_pme_convolve(%c: memref<?x!pme_real, 1>, %moduli: memref<?x?xf64, 1>,
                                         %rows: memref<?xf64, 1>, %box: vector<3xf64>,
                                         %beta: f64, %coulomb: f64,
                                         %k1: index, %k2: index, %k3: index)
    -> (f64, vector<9xf64>) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c10 = arith.constant 10 : index
  %c128 = arith.constant 128 : index
  %zero = arith.constant 0.0 : f64
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
  %prefactor = arith.divf %coulomb, %piv : f64
  %count = arith.muli %k1, %k2 : index
  %blocks_count = func.call @mdrt_gpu_pme_blocks(%count) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_count, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %count : index
    scf.if %inside {
      %cc0 = arith.constant 0 : index
      %cc1 = arith.constant 1 : index
      %cc2 = arith.constant 2 : index
      %kzero = arith.constant 0.0 : f64
      %khalf = arith.constant 0.5 : f64
      %kone = arith.constant 1.0 : f64
      %ktwo = arith.constant 2.0 : f64
      %a = arith.divui %item, %k2 : index
      %b = arith.remui %item, %k2 : index
      %w1_half = arith.divui %k1, %cc2 : index
      %w1_ki = arith.index_cast %a : index to i64
      %w1_ni = arith.index_cast %k1 : index to i64
      %w1_beyond = arith.cmpi ugt, %a, %w1_half : index
      %w1_shifted = arith.subi %w1_ki, %w1_ni : i64
      %w1_signed = arith.select %w1_beyond, %w1_shifted, %w1_ki : i64
      %w1_sf = arith.sitofp %w1_signed : i64 to f64
      %w1_m = arith.mulf %w1_sf, %ilx : f64
      %w2_half = arith.divui %k2, %cc2 : index
      %w2_ki = arith.index_cast %b : index to i64
      %w2_ni = arith.index_cast %k2 : index to i64
      %w2_beyond = arith.cmpi ugt, %b, %w2_half : index
      %w2_shifted = arith.subi %w2_ki, %w2_ni : i64
      %w2_signed = arith.select %w2_beyond, %w2_shifted, %w2_ki : i64
      %w2_sf = arith.sitofp %w2_signed : i64 to f64
      %w2_m = arith.mulf %w2_sf, %ily : f64
      %h = arith.divui %k3, %cc2 : index
      %h1 = arith.addi %h, %cc1 : index
      %odd = arith.remui %k3, %cc2 : index
      %even = arith.cmpi eq, %odd, %cc0 : index
      %m1s = arith.mulf %w1_m, %w1_m : f64
      %m2s = arith.mulf %w2_m, %w2_m : f64
      %m12 = arith.addf %m1s, %m2s : f64
      %mod1 = memref.load %moduli[%cc0, %a] : memref<?x?xf64, 1>
      %mod2 = memref.load %moduli[%cc1, %b] : memref<?x?xf64, 1>
      %mod12 = arith.mulf %mod1, %mod2 : f64
      %ke, %kw00, %kw01, %kw02, %kw11, %kw12, %kw22 = scf.for %z = %cc0 to %h1 step %cc1
          iter_args(%e0 = %kzero, %a00 = %kzero, %a01 = %kzero, %a02 = %kzero,
                    %a11 = %kzero, %a12 = %kzero, %a22 = %kzero)
          -> (f64, f64, f64, f64, f64, f64, f64) {
        %zi = arith.index_cast %z : index to i64
        %zf = arith.sitofp %zi : i64 to f64
        %m3 = arith.mulf %zf, %ilz : f64
        %mod3 = memref.load %moduli[%cc2, %z] : memref<?x?xf64, 1>
        %m3s = arith.mulf %m3, %m3 : f64
        %msq = arith.addf %m12, %m3s : f64
        %origin = arith.cmpf oeq, %msq, %kzero : f64
        %safe = arith.select %origin, %kone, %msq : f64
        %inverse = arith.divf %kone, %safe : f64
        %gm = arith.mulf %gauss, %msq : f64
        %ngm = arith.negf %gm : f64
        %ex = math.exp %ngm : f64
        %exm = arith.mulf %ex, %inverse : f64
        %pexm = arith.mulf %prefactor, %exm : f64
        %mods = arith.mulf %mod12, %mod3 : f64
        %bc0 = arith.mulf %pexm, %mods : f64
        %bc = arith.select %origin, %kzero, %bc0 : f64
        %base1 = arith.muli %item, %h1 : index
        %base2 = arith.addi %base1, %z : index
        %re_at = arith.muli %base2, %cc2 : index
        %im_at = arith.addi %re_at, %cc1 : index
        %rer = memref.load %c[%re_at] : memref<?x!pme_real, 1>
        %imr = memref.load %c[%im_at] : memref<?x!pme_real, 1>
        %re = PME_REAL_TO_F64 %rer : !pme_real to f64
        %im = PME_REAL_TO_F64 %imr : !pme_real to f64
        %re2 = arith.mulf %re, %re : f64
        %im2 = arith.mulf %im, %im : f64
        %g2 = arith.addf %re2, %im2 : f64
        %first = arith.cmpi eq, %z, %cc0 : index
        %middle = arith.cmpi eq, %z, %h : index
        %middle_even = arith.andi %middle, %even : i1
        %single = arith.ori %first, %middle_even : i1
        %weight = arith.select %single, %kone, %ktwo : f64
        %hw = arith.mulf %khalf, %weight : f64
        %hwb = arith.mulf %hw, %bc : f64
        %em = arith.mulf %hwb, %g2 : f64
        %sum = arith.addf %inverse, %gauss : f64
        %factor0 = arith.mulf %ktwo, %sum : f64
        %factor = arith.select %origin, %kzero, %factor0 : f64
        %ef = arith.mulf %em, %factor : f64
        %p11 = arith.mulf %w1_m, %w1_m : f64
        %p12 = arith.mulf %w1_m, %w2_m : f64
        %p13 = arith.mulf %w1_m, %m3 : f64
        %p22 = arith.mulf %w2_m, %w2_m : f64
        %p23 = arith.mulf %w2_m, %m3 : f64
        %p33 = arith.mulf %m3, %m3 : f64
        %t11 = arith.mulf %ef, %p11 : f64
        %t12 = arith.mulf %ef, %p12 : f64
        %t13 = arith.mulf %ef, %p13 : f64
        %t22 = arith.mulf %ef, %p22 : f64
        %t23 = arith.mulf %ef, %p23 : f64
        %t33 = arith.mulf %ef, %p33 : f64
        %d11 = arith.subf %em, %t11 : f64
        %d22 = arith.subf %em, %t22 : f64
        %d33 = arith.subf %em, %t33 : f64
        %n00 = arith.addf %a00, %d11 : f64
        %n01 = arith.subf %a01, %t12 : f64
        %n02 = arith.subf %a02, %t13 : f64
        %n11 = arith.addf %a11, %d22 : f64
        %n12 = arith.subf %a12, %t23 : f64
        %n22 = arith.addf %a22, %d33 : f64
        %ne = arith.addf %e0, %em : f64
        %reb = arith.mulf %re, %bc : f64
        %imb = arith.mulf %im, %bc : f64
        %rebr = PME_F64_TO_REAL %reb : f64 to !pme_real
        %imbr = PME_F64_TO_REAL %imb : f64 to !pme_real
        memref.store %rebr, %c[%re_at] : memref<?x!pme_real, 1>
        memref.store %imbr, %c[%im_at] : memref<?x!pme_real, 1>
        scf.yield %ne, %n00, %n01, %n02, %n11, %n12, %n22
            : f64, f64, f64, f64, f64, f64, f64
      }
      %out = arith.muli %item, %c10 : index
      %oc0 = arith.constant 0 : index
      %o0 = arith.addi %out, %oc0 : index
      memref.store %ke, %rows[%o0] : memref<?xf64, 1>
      %oc1 = arith.constant 1 : index
      %o1 = arith.addi %out, %oc1 : index
      memref.store %kw00, %rows[%o1] : memref<?xf64, 1>
      %oc2 = arith.constant 2 : index
      %o2 = arith.addi %out, %oc2 : index
      memref.store %kw01, %rows[%o2] : memref<?xf64, 1>
      %oc3 = arith.constant 3 : index
      %o3 = arith.addi %out, %oc3 : index
      memref.store %kw02, %rows[%o3] : memref<?xf64, 1>
      %oc4 = arith.constant 4 : index
      %o4 = arith.addi %out, %oc4 : index
      memref.store %kw11, %rows[%o4] : memref<?xf64, 1>
      %oc5 = arith.constant 5 : index
      %o5 = arith.addi %out, %oc5 : index
      memref.store %kw12, %rows[%o5] : memref<?xf64, 1>
      %oc6 = arith.constant 6 : index
      %o6 = arith.addi %out, %oc6 : index
      memref.store %kw22, %rows[%o6] : memref<?xf64, 1>
      %oc7 = arith.constant 7 : index
      %o7 = arith.addi %out, %oc7 : index
      memref.store %kzero, %rows[%o7] : memref<?xf64, 1>
      %oc8 = arith.constant 8 : index
      %o8 = arith.addi %out, %oc8 : index
      memref.store %kzero, %rows[%o8] : memref<?xf64, 1>
      %oc9 = arith.constant 9 : index
      %o9 = arith.addi %out, %oc9 : index
      memref.store %kzero, %rows[%o9] : memref<?xf64, 1>
    }
    gpu.terminator
  }

  // The rows, added up in their order on the host.
  %length = arith.muli %count, %c10 : index
  %host = memref.alloc(%length) : memref<?xf64>
  %t0 = gpu.wait async
  %t1 = gpu.memcpy async [%t0] %host, %rows : memref<?xf64>, memref<?xf64, 1>
  gpu.wait [%t1]
  %e, %w00, %w01, %w02, %w11, %w12, %w22 = scf.for %r = %c0 to %count step %c1
      iter_args(%s0 = %zero, %s1 = %zero, %s2 = %zero, %s3 = %zero,
                %s4 = %zero, %s5 = %zero, %s6 = %zero)
      -> (f64, f64, f64, f64, f64, f64, f64) {
    %at = arith.muli %r, %c10 : index
    %c2h = arith.constant 2 : index
    %c3h = arith.constant 3 : index
    %c4h = arith.constant 4 : index
    %c5h = arith.constant 5 : index
    %c6h = arith.constant 6 : index
    %a1 = arith.addi %at, %c1 : index
    %a2 = arith.addi %at, %c2h : index
    %a3 = arith.addi %at, %c3h : index
    %a4 = arith.addi %at, %c4h : index
    %a5 = arith.addi %at, %c5h : index
    %a6 = arith.addi %at, %c6h : index
    %v0 = memref.load %host[%at] : memref<?xf64>
    %v1 = memref.load %host[%a1] : memref<?xf64>
    %v2 = memref.load %host[%a2] : memref<?xf64>
    %v3 = memref.load %host[%a3] : memref<?xf64>
    %v4 = memref.load %host[%a4] : memref<?xf64>
    %v5 = memref.load %host[%a5] : memref<?xf64>
    %v6 = memref.load %host[%a6] : memref<?xf64>
    %n0 = arith.addf %s0, %v0 : f64
    %n1 = arith.addf %s1, %v1 : f64
    %n2 = arith.addf %s2, %v2 : f64
    %n3 = arith.addf %s3, %v3 : f64
    %n4 = arith.addf %s4, %v4 : f64
    %n5 = arith.addf %s5, %v5 : f64
    %n6 = arith.addf %s6, %v6 : f64
    scf.yield %n0, %n1, %n2, %n3, %n4, %n5, %n6 : f64, f64, f64, f64, f64, f64, f64
  }
  memref.dealloc %host : memref<?xf64>
  %virial = vector.from_elements %w00, %w01, %w02, %w01, %w11, %w12, %w02, %w12, %w22 : vector<9xf64>
  return %e, %virial : f64, vector<9xf64>
}

// Multiplies the half-complex transform `c` by the influence function, as
// @mdrt_gpu_pme_convolve does, where neither the energy nor the virial is
// needed: a thread for each point, and nothing for the host to wait for.
func.func private @mdrt_gpu_pme_scale(%c: memref<?x!pme_real, 1>, %moduli: memref<?x?xf64, 1>,
                                      %box: vector<3xf64>, %beta: f64, %coulomb: f64,
                                      %k1: index, %k2: index, %k3: index) {
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  %c128 = arith.constant 128 : index
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
  %prefactor = arith.divf %coulomb, %piv : f64
  %gaussr = PME_F64_TO_REAL %gauss : f64 to !pme_real
  %prefactorr = PME_F64_TO_REAL %prefactor : f64 to !pme_real
  %rows = arith.muli %k1, %k2 : index
  %half = arith.divui %k3, %c2 : index
  %depth = arith.addi %half, %c1 : index
  %points = arith.muli %rows, %depth : index
  %depth32 = arith.index_cast %depth : index to i32
  %k2_32 = arith.index_cast %k2 : index to i32
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %blocks_points = func.call @mdrt_gpu_pme_blocks(%points) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_points, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %points : index
    scf.if %inside {
      %cc0 = arith.constant 0 : index
      %cc1 = arith.constant 1 : index
      %cc2 = arith.constant 2 : index
      %kzero = arith.constant 0.0 : f64
      %kone = arith.constant 1.0 : f64
      // The point, in i32 (D85): a division of 64-bit integers is a long
      // sequence of instructions on a device.
      %item32 = arith.index_cast %item : index to i32
      %row32 = arith.divui %item32, %depth32 : i32
      %z32 = arith.remui %item32, %depth32 : i32
      %a32 = arith.divui %row32, %k2_32 : i32
      %b32 = arith.remui %row32, %k2_32 : i32
      %z = arith.index_cast %z32 : i32 to index
      %a = arith.index_cast %a32 : i32 to index
      %b = arith.index_cast %b32 : i32 to index
      %w1_half = arith.divui %k1, %cc2 : index
      %w1_ki = arith.index_cast %a : index to i64
      %w1_ni = arith.index_cast %k1 : index to i64
      %w1_beyond = arith.cmpi ugt, %a, %w1_half : index
      %w1_shifted = arith.subi %w1_ki, %w1_ni : i64
      %w1_signed = arith.select %w1_beyond, %w1_shifted, %w1_ki : i64
      %w1_sf = arith.sitofp %w1_signed : i64 to f64
      %w1_m = arith.mulf %w1_sf, %ilx : f64
      %w2_half = arith.divui %k2, %cc2 : index
      %w2_ki = arith.index_cast %b : index to i64
      %w2_ni = arith.index_cast %k2 : index to i64
      %w2_beyond = arith.cmpi ugt, %b, %w2_half : index
      %w2_shifted = arith.subi %w2_ki, %w2_ni : i64
      %w2_signed = arith.select %w2_beyond, %w2_shifted, %w2_ki : i64
      %w2_sf = arith.sitofp %w2_signed : i64 to f64
      %w2_m = arith.mulf %w2_sf, %ily : f64
      %m1s = arith.mulf %w1_m, %w1_m : f64
      %m2s = arith.mulf %w2_m, %w2_m : f64
      %m12 = arith.addf %m1s, %m2s : f64
      %mod1 = memref.load %moduli[%cc0, %a] : memref<?x?xf64, 1>
      %mod2 = memref.load %moduli[%cc1, %b] : memref<?x?xf64, 1>
      %mod12 = arith.mulf %mod1, %mod2 : f64
      %zi = arith.index_cast %z : index to i64
      %zf = arith.sitofp %zi : i64 to f64
      %m3 = arith.mulf %zf, %ilz : f64
      %mod3 = memref.load %moduli[%cc2, %z] : memref<?x?xf64, 1>
      %m3s = arith.mulf %m3, %m3 : f64
      %msq = arith.addf %m12, %m3s : f64
      %mods = arith.mulf %mod12, %mod3 : f64
      // The influence function in !pme_real: the exponential is most of the
      // work, and in f32 it is what the transform holds anyway.
      %msqr = PME_F64_TO_REAL %msq : f64 to !pme_real
      %modsr = PME_F64_TO_REAL %mods : f64 to !pme_real
      %rzero = arith.constant 0.0 : !pme_real
      %rone = arith.constant 1.0 : !pme_real
      %origin = arith.cmpf oeq, %msqr, %rzero : !pme_real
      %safe = arith.select %origin, %rone, %msqr : !pme_real
      %inverse = arith.divf %rone, %safe : !pme_real
      %gm = arith.mulf %gaussr, %msqr : !pme_real
      %ngm = arith.negf %gm : !pme_real
      %ex = math.exp %ngm : !pme_real
      %exm = arith.mulf %ex, %inverse : !pme_real
      %pexm = arith.mulf %prefactorr, %exm : !pme_real
      %bc0 = arith.mulf %pexm, %modsr : !pme_real
      %bc = arith.select %origin, %rzero, %bc0 : !pme_real
      %re_at = arith.muli %item, %cc2 : index
      %im_at = arith.addi %re_at, %cc1 : index
      %re = memref.load %c[%re_at] : memref<?x!pme_real, 1>
      %im = memref.load %c[%im_at] : memref<?x!pme_real, 1>
      %reb = arith.mulf %re, %bc : !pme_real
      %imb = arith.mulf %im, %bc : !pme_real
      memref.store %reb, %c[%re_at] : memref<?x!pme_real, 1>
      memref.store %imb, %c[%im_at] : memref<?x!pme_real, 1>
    }
    gpu.terminator
  }
  return
}

// The forces, as @mdrt.pme_gather gives them: a thread for each particle.
func.func private @mdrt_gpu_pme_gather(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %phi: memref<?x!pme_real, 1>, %box: vector<3xf64>,
                                       %k1: index, %k2: index, %k3: index, %n: index,
                                       %f: memref<?x3x!pme_frc, 1>) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %k1i = arith.index_cast %k1 : index to i64
  %k2i = arith.index_cast %k2 : index to i64
  %k3i = arith.index_cast %k3 : index to i64
  %k1f = arith.sitofp %k1i : i64 to f64
  %k2f = arith.sitofp %k2i : i64 to f64
  %k3f = arith.sitofp %k3i : i64 to f64
  %rx = arith.divf %k1f, %lx : f64
  %ry = arith.divf %k2f, %ly : f64
  %rz = arith.divf %k3f, %lz : f64
  %rxr = PME_F64_TO_REAL %rx : f64 to !pme_real
  %ryr = PME_F64_TO_REAL %ry : f64 to !pme_real
  %rzr = PME_F64_TO_REAL %rz : f64 to !pme_real
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %blocks_count = func.call @mdrt_gpu_pme_blocks(%count) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_count, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, %count : index
    scf.if %inside {
      %i = arith.addi %item, %c0 : index
      %i0 = arith.constant 0 : index
      %i1 = arith.constant 1 : index
      %i2 = arith.constant 2 : index
      // The order of the splines, a constant of the instance, so that the loops
      // over it unroll and the splines are held in registers.
      %order = arith.constant PME_ORDER : index
      %wx = memref.alloca() : memref<8x!pme_real>
      %wy = memref.alloca() : memref<8x!pme_real>
      %wz = memref.alloca() : memref<8x!pme_real>
      %dx = memref.alloca() : memref<8x!pme_real>
      %dy = memref.alloca() : memref<8x!pme_real>
      %dz = memref.alloca() : memref<8x!pme_real>
      %xs = memref.load %x[%i, %i0] : memref<?x3x!pme_pos, 1>
      %ys = memref.load %x[%i, %i1] : memref<?x3x!pme_pos, 1>
      %zs = memref.load %x[%i, %i2] : memref<?x3x!pme_pos, 1>
      %qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
      %xi = PME_EXTEND_POS %xs : !pme_pos to f64
      %yi = PME_EXTEND_POS %ys : !pme_pos to f64
      %zi = PME_EXTEND_POS %zs : !pme_pos to f64
      %qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real
      %px_s = arith.mulf %xi, %ilx : f64
      %px_fs = math.floor %px_s : f64
      %px_frac = arith.subf %px_s, %px_fs : f64
      %px_ki = arith.index_cast %k1 : index to i64
      %px_kf = arith.sitofp %px_ki : i64 to f64
      %px_u = arith.mulf %px_frac, %px_kf : f64
      %px_fu = math.floor %px_u : f64
      %px_w = arith.subf %px_u, %px_fu : f64
      %px_bi = arith.fptosi %px_fu : f64 to i64
      %px_b = arith.index_cast %px_bi : i64 to index
      %px_bk = arith.addi %px_b, %k1 : index
      %px_bkn = arith.subi %px_bk, %order : index
      %px_c1p = arith.constant 1 : index
      %px_start0 = arith.addi %px_bkn, %px_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %px_start = arith.remui %px_start0, %k1 : index
      %px_wr = PME_F64_TO_REAL %px_w : f64 to !pme_real
      %bx_c0 = arith.constant 0 : index
      %bx_c1 = arith.constant 1 : index
      %bx_c2 = arith.constant 2 : index
      %bx_c3 = arith.constant 3 : index
      %bx_c8 = arith.constant 8 : index
      %bx_zero = arith.constant 0.0 : !pme_real
      %bx_one = arith.constant 1.0 : !pme_real
      scf.for %bx_j = %bx_c0 to %bx_c8 step %bx_c1 {
        memref.store %bx_zero, %wx[%bx_j] : memref<8x!pme_real>
      }
      %bx_omw = arith.subf %bx_one, %px_wr : !pme_real
      memref.store %bx_omw, %wx[%bx_c0] : memref<8x!pme_real>
      memref.store %px_wr, %wx[%bx_c1] : memref<8x!pme_real>
      scf.for %bx_k = %bx_c3 to %order step %bx_c1 {
      %bx_r_km1 = arith.subi %bx_k, %bx_c1 : index
      %bx_r_km2 = arith.subi %bx_k, %bx_c2 : index
      %bx_r_km1i = arith.index_cast %bx_r_km1 : index to i64
      %bx_r_km1f = arith.sitofp %bx_r_km1i : i64 to !pme_real
      %bx_r_div = arith.divf %bx_one, %bx_r_km1f : !pme_real
      %bx_r_ki = arith.index_cast %bx_k : index to i64
      %bx_r_kf = arith.sitofp %bx_r_ki : i64 to !pme_real
      %bx_r_last = memref.load %wx[%bx_r_km2] : memref<8x!pme_real>
      %bx_r_dw = arith.mulf %bx_r_div, %px_wr : !pme_real
      %bx_r_top = arith.mulf %bx_r_dw, %bx_r_last : !pme_real
      memref.store %bx_r_top, %wx[%bx_r_km1] : memref<8x!pme_real>
      scf.for %bx_r_j = %bx_c1 to %bx_r_km1 step %bx_c1 {
        %bx_r_ji = arith.index_cast %bx_r_j : index to i64
        %bx_r_jf = arith.sitofp %bx_r_ji : i64 to !pme_real
        %bx_r_at = arith.subi %bx_r_km1, %bx_r_j : index
        %bx_r_below = arith.subi %bx_r_at, %bx_c1 : index
        %bx_r_lo = memref.load %wx[%bx_r_below] : memref<8x!pme_real>
        %bx_r_hi = memref.load %wx[%bx_r_at] : memref<8x!pme_real>
        %bx_r_wj = arith.addf %px_wr, %bx_r_jf : !pme_real
        %bx_r_kj = arith.subf %bx_r_kf, %bx_r_jf : !pme_real
        %bx_r_kjw = arith.subf %bx_r_kj, %px_wr : !pme_real
        %bx_r_t1 = arith.mulf %bx_r_wj, %bx_r_lo : !pme_real
        %bx_r_t2 = arith.mulf %bx_r_kjw, %bx_r_hi : !pme_real
        %bx_r_sum = arith.addf %bx_r_t1, %bx_r_t2 : !pme_real
        %bx_r_value = arith.mulf %bx_r_div, %bx_r_sum : !pme_real
        memref.store %bx_r_value, %wx[%bx_r_at] : memref<8x!pme_real>
      }
      %bx_r_first = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_r_omw = arith.subf %bx_one, %px_wr : !pme_real
      %bx_r_d0 = arith.mulf %bx_r_div, %bx_r_omw : !pme_real
      %bx_r_bottom = arith.mulf %bx_r_d0, %bx_r_first : !pme_real
      memref.store %bx_r_bottom, %wx[%bx_c0] : memref<8x!pme_real>
      }
      %bx_v0 = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_s0 = arith.negf %bx_v0 : !pme_real
      memref.store %bx_s0, %dx[%bx_c0] : memref<8x!pme_real>
      scf.for %bx_js = %bx_c1 to %order step %bx_c1 {
        %bx_jm1 = arith.subi %bx_js, %bx_c1 : index
        %bx_before = memref.load %wx[%bx_jm1] : memref<8x!pme_real>
        %bx_here = memref.load %wx[%bx_js] : memref<8x!pme_real>
        %bx_slope = arith.subf %bx_before, %bx_here : !pme_real
        memref.store %bx_slope, %dx[%bx_js] : memref<8x!pme_real>
      }
      %bx_f_km1 = arith.subi %order, %bx_c1 : index
      %bx_f_km2 = arith.subi %order, %bx_c2 : index
      %bx_f_km1i = arith.index_cast %bx_f_km1 : index to i64
      %bx_f_km1f = arith.sitofp %bx_f_km1i : i64 to !pme_real
      %bx_f_div = arith.divf %bx_one, %bx_f_km1f : !pme_real
      %bx_f_ki = arith.index_cast %order : index to i64
      %bx_f_kf = arith.sitofp %bx_f_ki : i64 to !pme_real
      %bx_f_last = memref.load %wx[%bx_f_km2] : memref<8x!pme_real>
      %bx_f_dw = arith.mulf %bx_f_div, %px_wr : !pme_real
      %bx_f_top = arith.mulf %bx_f_dw, %bx_f_last : !pme_real
      memref.store %bx_f_top, %wx[%bx_f_km1] : memref<8x!pme_real>
      scf.for %bx_f_j = %bx_c1 to %bx_f_km1 step %bx_c1 {
        %bx_f_ji = arith.index_cast %bx_f_j : index to i64
        %bx_f_jf = arith.sitofp %bx_f_ji : i64 to !pme_real
        %bx_f_at = arith.subi %bx_f_km1, %bx_f_j : index
        %bx_f_below = arith.subi %bx_f_at, %bx_c1 : index
        %bx_f_lo = memref.load %wx[%bx_f_below] : memref<8x!pme_real>
        %bx_f_hi = memref.load %wx[%bx_f_at] : memref<8x!pme_real>
        %bx_f_wj = arith.addf %px_wr, %bx_f_jf : !pme_real
        %bx_f_kj = arith.subf %bx_f_kf, %bx_f_jf : !pme_real
        %bx_f_kjw = arith.subf %bx_f_kj, %px_wr : !pme_real
        %bx_f_t1 = arith.mulf %bx_f_wj, %bx_f_lo : !pme_real
        %bx_f_t2 = arith.mulf %bx_f_kjw, %bx_f_hi : !pme_real
        %bx_f_sum = arith.addf %bx_f_t1, %bx_f_t2 : !pme_real
        %bx_f_value = arith.mulf %bx_f_div, %bx_f_sum : !pme_real
        memref.store %bx_f_value, %wx[%bx_f_at] : memref<8x!pme_real>
      }
      %bx_f_first = memref.load %wx[%bx_c0] : memref<8x!pme_real>
      %bx_f_omw = arith.subf %bx_one, %px_wr : !pme_real
      %bx_f_d0 = arith.mulf %bx_f_div, %bx_f_omw : !pme_real
      %bx_f_bottom = arith.mulf %bx_f_d0, %bx_f_first : !pme_real
      memref.store %bx_f_bottom, %wx[%bx_c0] : memref<8x!pme_real>
      %py_s = arith.mulf %yi, %ily : f64
      %py_fs = math.floor %py_s : f64
      %py_frac = arith.subf %py_s, %py_fs : f64
      %py_ki = arith.index_cast %k2 : index to i64
      %py_kf = arith.sitofp %py_ki : i64 to f64
      %py_u = arith.mulf %py_frac, %py_kf : f64
      %py_fu = math.floor %py_u : f64
      %py_w = arith.subf %py_u, %py_fu : f64
      %py_bi = arith.fptosi %py_fu : f64 to i64
      %py_b = arith.index_cast %py_bi : i64 to index
      %py_bk = arith.addi %py_b, %k2 : index
      %py_bkn = arith.subi %py_bk, %order : index
      %py_c1p = arith.constant 1 : index
      %py_start0 = arith.addi %py_bkn, %py_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %py_start = arith.remui %py_start0, %k2 : index
      %py_wr = PME_F64_TO_REAL %py_w : f64 to !pme_real
      %by_c0 = arith.constant 0 : index
      %by_c1 = arith.constant 1 : index
      %by_c2 = arith.constant 2 : index
      %by_c3 = arith.constant 3 : index
      %by_c8 = arith.constant 8 : index
      %by_zero = arith.constant 0.0 : !pme_real
      %by_one = arith.constant 1.0 : !pme_real
      scf.for %by_j = %by_c0 to %by_c8 step %by_c1 {
        memref.store %by_zero, %wy[%by_j] : memref<8x!pme_real>
      }
      %by_omw = arith.subf %by_one, %py_wr : !pme_real
      memref.store %by_omw, %wy[%by_c0] : memref<8x!pme_real>
      memref.store %py_wr, %wy[%by_c1] : memref<8x!pme_real>
      scf.for %by_k = %by_c3 to %order step %by_c1 {
      %by_r_km1 = arith.subi %by_k, %by_c1 : index
      %by_r_km2 = arith.subi %by_k, %by_c2 : index
      %by_r_km1i = arith.index_cast %by_r_km1 : index to i64
      %by_r_km1f = arith.sitofp %by_r_km1i : i64 to !pme_real
      %by_r_div = arith.divf %by_one, %by_r_km1f : !pme_real
      %by_r_ki = arith.index_cast %by_k : index to i64
      %by_r_kf = arith.sitofp %by_r_ki : i64 to !pme_real
      %by_r_last = memref.load %wy[%by_r_km2] : memref<8x!pme_real>
      %by_r_dw = arith.mulf %by_r_div, %py_wr : !pme_real
      %by_r_top = arith.mulf %by_r_dw, %by_r_last : !pme_real
      memref.store %by_r_top, %wy[%by_r_km1] : memref<8x!pme_real>
      scf.for %by_r_j = %by_c1 to %by_r_km1 step %by_c1 {
        %by_r_ji = arith.index_cast %by_r_j : index to i64
        %by_r_jf = arith.sitofp %by_r_ji : i64 to !pme_real
        %by_r_at = arith.subi %by_r_km1, %by_r_j : index
        %by_r_below = arith.subi %by_r_at, %by_c1 : index
        %by_r_lo = memref.load %wy[%by_r_below] : memref<8x!pme_real>
        %by_r_hi = memref.load %wy[%by_r_at] : memref<8x!pme_real>
        %by_r_wj = arith.addf %py_wr, %by_r_jf : !pme_real
        %by_r_kj = arith.subf %by_r_kf, %by_r_jf : !pme_real
        %by_r_kjw = arith.subf %by_r_kj, %py_wr : !pme_real
        %by_r_t1 = arith.mulf %by_r_wj, %by_r_lo : !pme_real
        %by_r_t2 = arith.mulf %by_r_kjw, %by_r_hi : !pme_real
        %by_r_sum = arith.addf %by_r_t1, %by_r_t2 : !pme_real
        %by_r_value = arith.mulf %by_r_div, %by_r_sum : !pme_real
        memref.store %by_r_value, %wy[%by_r_at] : memref<8x!pme_real>
      }
      %by_r_first = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_r_omw = arith.subf %by_one, %py_wr : !pme_real
      %by_r_d0 = arith.mulf %by_r_div, %by_r_omw : !pme_real
      %by_r_bottom = arith.mulf %by_r_d0, %by_r_first : !pme_real
      memref.store %by_r_bottom, %wy[%by_c0] : memref<8x!pme_real>
      }
      %by_v0 = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_s0 = arith.negf %by_v0 : !pme_real
      memref.store %by_s0, %dy[%by_c0] : memref<8x!pme_real>
      scf.for %by_js = %by_c1 to %order step %by_c1 {
        %by_jm1 = arith.subi %by_js, %by_c1 : index
        %by_before = memref.load %wy[%by_jm1] : memref<8x!pme_real>
        %by_here = memref.load %wy[%by_js] : memref<8x!pme_real>
        %by_slope = arith.subf %by_before, %by_here : !pme_real
        memref.store %by_slope, %dy[%by_js] : memref<8x!pme_real>
      }
      %by_f_km1 = arith.subi %order, %by_c1 : index
      %by_f_km2 = arith.subi %order, %by_c2 : index
      %by_f_km1i = arith.index_cast %by_f_km1 : index to i64
      %by_f_km1f = arith.sitofp %by_f_km1i : i64 to !pme_real
      %by_f_div = arith.divf %by_one, %by_f_km1f : !pme_real
      %by_f_ki = arith.index_cast %order : index to i64
      %by_f_kf = arith.sitofp %by_f_ki : i64 to !pme_real
      %by_f_last = memref.load %wy[%by_f_km2] : memref<8x!pme_real>
      %by_f_dw = arith.mulf %by_f_div, %py_wr : !pme_real
      %by_f_top = arith.mulf %by_f_dw, %by_f_last : !pme_real
      memref.store %by_f_top, %wy[%by_f_km1] : memref<8x!pme_real>
      scf.for %by_f_j = %by_c1 to %by_f_km1 step %by_c1 {
        %by_f_ji = arith.index_cast %by_f_j : index to i64
        %by_f_jf = arith.sitofp %by_f_ji : i64 to !pme_real
        %by_f_at = arith.subi %by_f_km1, %by_f_j : index
        %by_f_below = arith.subi %by_f_at, %by_c1 : index
        %by_f_lo = memref.load %wy[%by_f_below] : memref<8x!pme_real>
        %by_f_hi = memref.load %wy[%by_f_at] : memref<8x!pme_real>
        %by_f_wj = arith.addf %py_wr, %by_f_jf : !pme_real
        %by_f_kj = arith.subf %by_f_kf, %by_f_jf : !pme_real
        %by_f_kjw = arith.subf %by_f_kj, %py_wr : !pme_real
        %by_f_t1 = arith.mulf %by_f_wj, %by_f_lo : !pme_real
        %by_f_t2 = arith.mulf %by_f_kjw, %by_f_hi : !pme_real
        %by_f_sum = arith.addf %by_f_t1, %by_f_t2 : !pme_real
        %by_f_value = arith.mulf %by_f_div, %by_f_sum : !pme_real
        memref.store %by_f_value, %wy[%by_f_at] : memref<8x!pme_real>
      }
      %by_f_first = memref.load %wy[%by_c0] : memref<8x!pme_real>
      %by_f_omw = arith.subf %by_one, %py_wr : !pme_real
      %by_f_d0 = arith.mulf %by_f_div, %by_f_omw : !pme_real
      %by_f_bottom = arith.mulf %by_f_d0, %by_f_first : !pme_real
      memref.store %by_f_bottom, %wy[%by_c0] : memref<8x!pme_real>
      %pz_s = arith.mulf %zi, %ilz : f64
      %pz_fs = math.floor %pz_s : f64
      %pz_frac = arith.subf %pz_s, %pz_fs : f64
      %pz_ki = arith.index_cast %k3 : index to i64
      %pz_kf = arith.sitofp %pz_ki : i64 to f64
      %pz_u = arith.mulf %pz_frac, %pz_kf : f64
      %pz_fu = math.floor %pz_u : f64
      %pz_w = arith.subf %pz_u, %pz_fu : f64
      %pz_bi = arith.fptosi %pz_fu : f64 to i64
      %pz_b = arith.index_cast %pz_bi : i64 to index
      %pz_bk = arith.addi %pz_b, %k3 : index
      %pz_bkn = arith.subi %pz_bk, %order : index
      %pz_c1p = arith.constant 1 : index
      %pz_start0 = arith.addi %pz_bkn, %pz_c1p : index
      // The first point within the grid, so that the points of the particle need
      // one subtraction at most to wrap around.
      %pz_start = arith.remui %pz_start0, %k3 : index
      %pz_wr = PME_F64_TO_REAL %pz_w : f64 to !pme_real
      %bz_c0 = arith.constant 0 : index
      %bz_c1 = arith.constant 1 : index
      %bz_c2 = arith.constant 2 : index
      %bz_c3 = arith.constant 3 : index
      %bz_c8 = arith.constant 8 : index
      %bz_zero = arith.constant 0.0 : !pme_real
      %bz_one = arith.constant 1.0 : !pme_real
      scf.for %bz_j = %bz_c0 to %bz_c8 step %bz_c1 {
        memref.store %bz_zero, %wz[%bz_j] : memref<8x!pme_real>
      }
      %bz_omw = arith.subf %bz_one, %pz_wr : !pme_real
      memref.store %bz_omw, %wz[%bz_c0] : memref<8x!pme_real>
      memref.store %pz_wr, %wz[%bz_c1] : memref<8x!pme_real>
      scf.for %bz_k = %bz_c3 to %order step %bz_c1 {
      %bz_r_km1 = arith.subi %bz_k, %bz_c1 : index
      %bz_r_km2 = arith.subi %bz_k, %bz_c2 : index
      %bz_r_km1i = arith.index_cast %bz_r_km1 : index to i64
      %bz_r_km1f = arith.sitofp %bz_r_km1i : i64 to !pme_real
      %bz_r_div = arith.divf %bz_one, %bz_r_km1f : !pme_real
      %bz_r_ki = arith.index_cast %bz_k : index to i64
      %bz_r_kf = arith.sitofp %bz_r_ki : i64 to !pme_real
      %bz_r_last = memref.load %wz[%bz_r_km2] : memref<8x!pme_real>
      %bz_r_dw = arith.mulf %bz_r_div, %pz_wr : !pme_real
      %bz_r_top = arith.mulf %bz_r_dw, %bz_r_last : !pme_real
      memref.store %bz_r_top, %wz[%bz_r_km1] : memref<8x!pme_real>
      scf.for %bz_r_j = %bz_c1 to %bz_r_km1 step %bz_c1 {
        %bz_r_ji = arith.index_cast %bz_r_j : index to i64
        %bz_r_jf = arith.sitofp %bz_r_ji : i64 to !pme_real
        %bz_r_at = arith.subi %bz_r_km1, %bz_r_j : index
        %bz_r_below = arith.subi %bz_r_at, %bz_c1 : index
        %bz_r_lo = memref.load %wz[%bz_r_below] : memref<8x!pme_real>
        %bz_r_hi = memref.load %wz[%bz_r_at] : memref<8x!pme_real>
        %bz_r_wj = arith.addf %pz_wr, %bz_r_jf : !pme_real
        %bz_r_kj = arith.subf %bz_r_kf, %bz_r_jf : !pme_real
        %bz_r_kjw = arith.subf %bz_r_kj, %pz_wr : !pme_real
        %bz_r_t1 = arith.mulf %bz_r_wj, %bz_r_lo : !pme_real
        %bz_r_t2 = arith.mulf %bz_r_kjw, %bz_r_hi : !pme_real
        %bz_r_sum = arith.addf %bz_r_t1, %bz_r_t2 : !pme_real
        %bz_r_value = arith.mulf %bz_r_div, %bz_r_sum : !pme_real
        memref.store %bz_r_value, %wz[%bz_r_at] : memref<8x!pme_real>
      }
      %bz_r_first = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_r_omw = arith.subf %bz_one, %pz_wr : !pme_real
      %bz_r_d0 = arith.mulf %bz_r_div, %bz_r_omw : !pme_real
      %bz_r_bottom = arith.mulf %bz_r_d0, %bz_r_first : !pme_real
      memref.store %bz_r_bottom, %wz[%bz_c0] : memref<8x!pme_real>
      }
      %bz_v0 = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_s0 = arith.negf %bz_v0 : !pme_real
      memref.store %bz_s0, %dz[%bz_c0] : memref<8x!pme_real>
      scf.for %bz_js = %bz_c1 to %order step %bz_c1 {
        %bz_jm1 = arith.subi %bz_js, %bz_c1 : index
        %bz_before = memref.load %wz[%bz_jm1] : memref<8x!pme_real>
        %bz_here = memref.load %wz[%bz_js] : memref<8x!pme_real>
        %bz_slope = arith.subf %bz_before, %bz_here : !pme_real
        memref.store %bz_slope, %dz[%bz_js] : memref<8x!pme_real>
      }
      %bz_f_km1 = arith.subi %order, %bz_c1 : index
      %bz_f_km2 = arith.subi %order, %bz_c2 : index
      %bz_f_km1i = arith.index_cast %bz_f_km1 : index to i64
      %bz_f_km1f = arith.sitofp %bz_f_km1i : i64 to !pme_real
      %bz_f_div = arith.divf %bz_one, %bz_f_km1f : !pme_real
      %bz_f_ki = arith.index_cast %order : index to i64
      %bz_f_kf = arith.sitofp %bz_f_ki : i64 to !pme_real
      %bz_f_last = memref.load %wz[%bz_f_km2] : memref<8x!pme_real>
      %bz_f_dw = arith.mulf %bz_f_div, %pz_wr : !pme_real
      %bz_f_top = arith.mulf %bz_f_dw, %bz_f_last : !pme_real
      memref.store %bz_f_top, %wz[%bz_f_km1] : memref<8x!pme_real>
      scf.for %bz_f_j = %bz_c1 to %bz_f_km1 step %bz_c1 {
        %bz_f_ji = arith.index_cast %bz_f_j : index to i64
        %bz_f_jf = arith.sitofp %bz_f_ji : i64 to !pme_real
        %bz_f_at = arith.subi %bz_f_km1, %bz_f_j : index
        %bz_f_below = arith.subi %bz_f_at, %bz_c1 : index
        %bz_f_lo = memref.load %wz[%bz_f_below] : memref<8x!pme_real>
        %bz_f_hi = memref.load %wz[%bz_f_at] : memref<8x!pme_real>
        %bz_f_wj = arith.addf %pz_wr, %bz_f_jf : !pme_real
        %bz_f_kj = arith.subf %bz_f_kf, %bz_f_jf : !pme_real
        %bz_f_kjw = arith.subf %bz_f_kj, %pz_wr : !pme_real
        %bz_f_t1 = arith.mulf %bz_f_wj, %bz_f_lo : !pme_real
        %bz_f_t2 = arith.mulf %bz_f_kjw, %bz_f_hi : !pme_real
        %bz_f_sum = arith.addf %bz_f_t1, %bz_f_t2 : !pme_real
        %bz_f_value = arith.mulf %bz_f_div, %bz_f_sum : !pme_real
        memref.store %bz_f_value, %wz[%bz_f_at] : memref<8x!pme_real>
      }
      %bz_f_first = memref.load %wz[%bz_c0] : memref<8x!pme_real>
      %bz_f_omw = arith.subf %bz_one, %pz_wr : !pme_real
      %bz_f_d0 = arith.mulf %bz_f_div, %bz_f_omw : !pme_real
      %bz_f_bottom = arith.mulf %bz_f_d0, %bz_f_first : !pme_real
      memref.store %bz_f_bottom, %wz[%bz_c0] : memref<8x!pme_real>
      %gzero = arith.constant 0.0 : !pme_real
      %j0 = arith.constant 0 : index
      %j1c = arith.constant 1 : index
      %sumx, %sumy, %sumz = scf.for %j1 = %j0 to %order step %j1c
          iter_args(%ax = %gzero, %ay = %gzero, %az = %gzero) -> (!pme_real, !pme_real, !pme_real) {
        %g1s = arith.addi %px_start, %j1 : index
        %g1w = arith.subi %g1s, %k1 : index
        %g1over = arith.cmpi uge, %g1s, %k1 : index
        %g1 = arith.select %g1over, %g1w, %g1s : index
        %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
        %d1 = memref.load %dx[%j1] : memref<8x!pme_real>
        %bx2, %by2, %bz2 = scf.for %j2 = %j0 to %order step %j1c
            iter_args(%cx = %ax, %cy = %ay, %cz = %az) -> (!pme_real, !pme_real, !pme_real) {
          %g2s = arith.addi %py_start, %j2 : index
          %g2w = arith.subi %g2s, %k2 : index
          %g2over = arith.cmpi uge, %g2s, %k2 : index
          %g2 = arith.select %g2over, %g2w, %g2s : index
          %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
          %d2 = memref.load %dy[%j2] : memref<8x!pme_real>
          %row1 = arith.muli %g1, %k2 : index
          %row = arith.addi %row1, %g2 : index
          %gbase = arith.muli %row, %k3 : index
          %d1w2 = arith.mulf %d1, %w2 : !pme_real
          %w1d2 = arith.mulf %w1, %d2 : !pme_real
          %w1w2 = arith.mulf %w1, %w2 : !pme_real
          %ex, %ey, %ez = scf.for %j3 = %j0 to %order step %j1c
              iter_args(%tx3 = %cx, %ty3 = %cy, %tz3 = %cz) -> (!pme_real, !pme_real, !pme_real) {
            %g3s = arith.addi %pz_start, %j3 : index
            %g3w = arith.subi %g3s, %k3 : index
            %g3over = arith.cmpi uge, %g3s, %k3 : index
            %g3 = arith.select %g3over, %g3w, %g3s : index
            %w3 = memref.load %wz[%j3] : memref<8x!pme_real>
            %d3 = memref.load %dz[%j3] : memref<8x!pme_real>
            %at = arith.addi %gbase, %g3 : index
            %p = memref.load %phi[%at] : memref<?x!pme_real, 1>
            %px = arith.mulf %d1w2, %w3 : !pme_real
            %py = arith.mulf %w1d2, %w3 : !pme_real
            %pz = arith.mulf %w1w2, %d3 : !pme_real
            %vx = arith.mulf %p, %px : !pme_real
            %vy = arith.mulf %p, %py : !pme_real
            %vz = arith.mulf %p, %pz : !pme_real
            %nx = arith.addf %tx3, %vx : !pme_real
            %ny = arith.addf %ty3, %vy : !pme_real
            %nz = arith.addf %tz3, %vz : !pme_real
            scf.yield %nx, %ny, %nz : !pme_real, !pme_real, !pme_real
          }
          scf.yield %ex, %ey, %ez : !pme_real, !pme_real, !pme_real
        }
        scf.yield %bx2, %by2, %bz2 : !pme_real, !pme_real, !pme_real
      }
      %mq = arith.negf %qi : !pme_real
      %sxq = arith.mulf %mq, %rxr : !pme_real
      %syq = arith.mulf %mq, %ryr : !pme_real
      %szq = arith.mulf %mq, %rzr : !pme_real
      %fx64 = arith.mulf %sxq, %sumx : !pme_real
      %fy64 = arith.mulf %syq, %sumy : !pme_real
      %fz64 = arith.mulf %szq, %sumz : !pme_real
      %fxs = PME_REAL_TO_FRC %fx64 : !pme_real to !pme_frc
      %fys = PME_REAL_TO_FRC %fy64 : !pme_real to !pme_frc
      %fzs = PME_REAL_TO_FRC %fz64 : !pme_real to !pme_frc
      memref.store %fxs, %f[%i, %i0] : memref<?x3x!pme_frc, 1>
      memref.store %fys, %f[%i, %i1] : memref<?x3x!pme_frc, 1>
      memref.store %fzs, %f[%i, %i2] : memref<?x3x!pme_frc, 1>
    }
    gpu.terminator
  }
  return
}
