add_subdirectory(Dialect/MD)
add_subdirectory(Dialect/MD/Transforms)
add_subdirectory(Dialect/Dyn)
add_subdirectory(Dialect/MDRT)
add_subdirectory(Dialect/MDExec)
add_subdirectory(Conversion/MDToMDExec)
add_subdirectory(Conversion/MDExecKernels)
add_subdirectory(Conversion/MDExecToLoops)
add_subdirectory(Conversion/MDExecToGPU)
add_subdirectory(Dialect/MDExec/Transforms)
add_subdirectory(Driver)
add_subdirectory(Dialect/MDDist)
