#!/usr/bin/env python3
"""Writes lib/Runtime/Templates/NeighborsGroupsGPU.mlir, the template that
builds groups of 16 particles sharing a list of neighbors on a device
(docs/groups-m1.md, D89).

    python3 scripts/generate-groups-gpu-template.py

The networks that sort the particles of a chunk and the partners of the
excluded pairs of a group are written out, stage by stage; this script
writes them. Edit the script, not the template."""

import os

HEADER = """\
// Builds groups of 16 particles that share a list of neighbors on a device
// (docs/groups-m1.md, D89).
//
// Generated by scripts/generate-groups-gpu-template.py. Do not edit.
//
// This is a template. The compiler adds it to a module that builds neighbor
// structures of groups on a device, where it is specialized like any other
// code. The keys in brackets are those of docs/references.md.
//
// The particles are put in a compact order: the columns of a grid in x-y,
// each of the width of about 64 particles, sorted by z (a counting sort by
// column and bin of z, the particles of a bin by number), cut into chunks
// of 64, each sorted by x and halved, each half sorted by y and halved: 4
// groups of up to 16 particles that fill a near-cube. The places of a chunk
// are 64 consecutive places; those of a short group are empty (`order` is
// -1 there). Every sort breaks ties by the number of the particle, so the
// order does not depend on the threads.
//
// The list of group g holds, for every particle j at a place q within
// `reach` of one of its particles (in the minimum image) and not before
// the group (q >= 16 g), the entry (q, m): bit u of m is set when the pair
// of the particle at place 16 g + u and j is within the reach, is not an
// excluded pair of `excluded` (an incidence structure of pairs, as for the
// matrix), and, within the group itself, u is before q. Each pair within
// the reach is in one list once. The candidates come from a grid of cells
// of half the reach over the places, each cell in the order of its places,
// visited in a fixed order, so the order of the entries of a group does not
// depend on the threads either. The layout is that of [SalomonFerrer2013];
// every pair is tested against the reach.
//
// The loops read the lists by units of work of up to 64 entries: `units`
// holds 64 g + k for the unit k of group g.
//
// On return, `sizes` (on the host) holds the number of places, the largest
// number of entries of a group, and the number of units. A number beyond
// the capacity of its buffer means that the buffer was too small and the
// structure is not complete; the caller stops.
//
// A kernel runs in blocks of 128 threads, a thread or a warp an item. The
// buffers are on the device; positions are in the cell `box`, orthorhombic
// and periodic. The search computes in f32, on positions wrapped into the
// cell.

"""

HELPERS = """\
// The number of blocks of `block` threads that hold `count` threads.
func.func private @mdrt_gpu_groups_grid(%count: index, %block: index) -> index {
  %c1 = arith.constant 1 : index
  %last = arith.subi %block, %c1 : index
  %padded = arith.addi %count, %last : index
  %result = arith.divui %padded, %block : index
  return %result : index
}

// The other member of the excluded pair `k` of the particle `i` in the
// incidence structure `excluded` (see NeighborsMatrixGPU.mlir).
func.func private @mdrt_gpu_groups_partner(%excluded: memref<?x?xi32, 1>,
    %i: index, %k: index) -> i32 {
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  %c3 = arith.constant 3 : index
  %c4 = arith.constant 4 : index
  %zero = arith.constant 0 : i32
  %entry0 = arith.muli %k, %c4 : index
  %entry = arith.addi %entry0, %c1 : index
  %place_column = arith.addi %entry, %c1 : index
  %place = memref.load %excluded[%i, %place_column] : memref<?x?xi32, 1>
  %at_first = arith.cmpi eq, %place, %zero : i32
  %first = arith.addi %entry, %c2 : index
  %second = arith.addi %entry, %c3 : index
  %column = arith.select %at_first, %second, %first : index
  %partner = memref.load %excluded[%i, %column] : memref<?x?xi32, 1>
  return %partner : i32
}

// The image of the difference `d` in a cell of edge `l` (`il` = 1 / l).
func.func private @mdrt_gpu_groups_image(%d: f32, %l: f32, %il: f32) -> f32 {
  %s = arith.mulf %d, %il : f32
  %r = math.roundeven %s : f32
  %m = arith.mulf %r, %l : f32
  %result = arith.subf %d, %m : f32
  return %result : f32
}

"""

WG = "#gpu.address_space<workgroup>"


def indent(text, spaces):
    pad = " " * spaces
    return "\n".join(pad + line if line else line
                     for line in text.splitlines()) + "\n"


def launch(grid, body, threads="%block", workgroup=""):
    """A launch of `grid` blocks of `threads` threads running `body`."""
    wg = f"\n             workgroup({workgroup})" if workgroup else ""
    return f"""\
  gpu.launch blocks(%bx, %by, %bz) in (%gx = {grid}, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = {threads}, %sy = %c1, %sz = %c1){wg} {{
{indent(body, 4)}    gpu.terminator
  }}
"""


def per_item(count, body):
    """A thread an item below `count`: `%item`."""
    return f"""\
%base = arith.muli %bx, %block : index
%item = arith.addi %base, %tx : index
%inside = arith.cmpi ult, %item, {count} : index
scf.if %inside {{
{indent(body, 2)}}}
"""


def atomic_add(p, buffer, index, value, result):
    """A relaxed atomic addition of the i32 `value` to `buffer[index]` at the
    scope of the device, whose old value is `result`."""
    return f"""\
%{p}base = memref.extract_aligned_pointer_as_index {buffer} : memref<?xi32, 1> -> index
%{p}bi = arith.index_cast %{p}base : index to i64
%{p}ki = arith.index_cast {index} : index to i64
%{p}four = arith.constant 4 : i64
%{p}off = arith.muli %{p}ki, %{p}four : i64
%{p}addr = arith.addi %{p}bi, %{p}off : i64
%{p}ptr = llvm.inttoptr %{p}addr : i64 to !llvm.ptr<1>
{result} = llvm.atomicrmw add %{p}ptr, {value} syncscope("device") monotonic : !llvm.ptr<1>, i32
"""


def atomic_max(p, buffer, value):
    """A relaxed atomic maximum of the i32 `value` into `buffer[0]`."""
    return f"""\
%{p}base = memref.extract_aligned_pointer_as_index {buffer} : memref<3xi32, 1> -> index
%{p}bi = arith.index_cast %{p}base : index to i64
%{p}four = arith.constant 4 : i64
%{p}addr = arith.addi %{p}bi, %{p}four : i64
%{p}ptr = llvm.inttoptr %{p}addr : i64 to !llvm.ptr<1>
%{p}old = llvm.atomicrmw max %{p}ptr, {value} syncscope("device") monotonic : !llvm.ptr<1>, i32
"""


def clear(grid, buffer, count, value="0"):
    return launch(grid, per_item(count, f"""\
%v = arith.constant {value} : i32
memref.store %v, {buffer}[%item] : memref<?xi32, 1>"""))


def scan(p, counts, start, cursor, n):
    """The exclusive sums of `counts` (`n` of them, i32) into `start` (n + 1)
    and `cursor` (n): sums of chunks of 256 in parallel, the chunks in one
    thread, then the offsets within each chunk."""
    sums = per_item(f"%{p}chunks", f"""\
%i1 = arith.constant 1 : index
%none = arith.constant 0 : i32
%begin = arith.muli %item, %chunk : index
%full = arith.addi %begin, %chunk : index
%short = arith.cmpi ult, {n}, %full : index
%end = arith.select %short, {n}, %full : index
%sum = scf.for %c = %begin to %end step %i1 iter_args(%s = %none) -> (i32) {{
  %v = memref.load {counts}[%c] : memref<?xi32, 1>
  %t = arith.addi %s, %v : i32
  scf.yield %t : i32
}}
memref.store %sum, %{p}sums[%item] : memref<?xi32, 1>""")
    offsets = f"""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%none = arith.constant 0 : i32
%total = scf.for %b = %i0 to %{p}chunks step %i1 iter_args(%before = %none) -> (i32) {{
  %s = memref.load %{p}sums[%b] : memref<?xi32, 1>
  memref.store %before, %{p}sums[%b] : memref<?xi32, 1>
  %t = arith.addi %before, %s : i32
  scf.yield %t : i32
}}
memref.store %total, {start}[{n}] : memref<?xi32, 1>"""
    within = per_item(f"%{p}chunks", f"""\
%i1 = arith.constant 1 : index
%begin = arith.muli %item, %chunk : index
%full = arith.addi %begin, %chunk : index
%short = arith.cmpi ult, {n}, %full : index
%end = arith.select %short, {n}, %full : index
%first = memref.load %{p}sums[%item] : memref<?xi32, 1>
%last = scf.for %c = %begin to %end step %i1 iter_args(%before = %first) -> (i32) {{
  %v = memref.load {counts}[%c] : memref<?xi32, 1>
  memref.store %before, {start}[%c] : memref<?xi32, 1>
  memref.store %before, {cursor}[%c] : memref<?xi32, 1>
  %t = arith.addi %before, %v : i32
  scf.yield %t : i32
}}""")
    head = (f"  %{p}chunks = func.call @mdrt_gpu_groups_grid({n}, %chunk) : (index, index) -> index\n"
            f"  %{p}grid = func.call @mdrt_gpu_groups_grid(%{p}chunks, %block) : (index, index) -> index\n"
            f"  %{p}sums = gpu.alloc (%{p}chunks) : memref<?xi32, 1>\n")
    return (head + launch(f"%{p}grid", sums) + launch("%c1", offsets, threads="%c1")
            + launch(f"%{p}grid", within)
            + f"  %{p}sums_plain = memref.memory_space_cast %{p}sums : memref<?xi32, 1> to memref<?xi32>\n"
            + f"  gpu.dealloc %{p}sums_plain : memref<?xi32>\n")


def sort_bins(grid, start, items, n):
    """Sorts the items (i32) of each of the `n` bins of `start` ascending,
    by insertion: the bins hold few items, whose order after the atomics is
    not fixed."""
    return launch(grid, per_item(n, f'''\
%i1 = arith.constant 1 : index
%next = arith.addi %item, %i1 : index
%begin32 = memref.load {start}[%item] : memref<?xi32, 1>
%end32 = memref.load {start}[%next] : memref<?xi32, 1>
%begin = arith.index_cast %begin32 : i32 to index
%end = arith.index_cast %end32 : i32 to index
%first = arith.addi %begin, %i1 : index
scf.for %p = %first to %end step %i1 {{
  %value = memref.load {items}[%p] : memref<?xi32, 1>
  %hole = scf.while (%q = %p) : (index) -> index {{
    %more = arith.cmpi ugt, %q, %begin : index
    %before = arith.subi %q, %i1 : index
    %safe = arith.select %more, %before, %begin : index
    %left = memref.load {items}[%safe] : memref<?xi32, 1>
    %larger = arith.cmpi sgt, %left, %value : i32
    %go = arith.andi %more, %larger : i1
    scf.condition(%go) %q : index
  }} do {{
  ^bb0(%q: index):
    %before = arith.subi %q, %i1 : index
    %left = memref.load {items}[%before] : memref<?xi32, 1>
    memref.store %left, {items}[%q] : memref<?xi32, 1>
    scf.yield %before : index
  }}
  memref.store %value, {items}[%hole] : memref<?xi32, 1>
}}'''))


class Lines:
    def __init__(self):
        self.lines = []

    def __call__(self, text):
        self.lines.extend(text.splitlines())

    def text(self):
        return "\n".join(self.lines) + "\n"


def bitonic(out, p, n_values, keys, ids, lane):
    """A bitonic network sorting `n_values` (32 or 64) pairs (key f32, id i32)
    ascending by key, then id, held one or two a lane (position lane + 32 v
    for value v). Returns the SSA names of the sorted values of the lane."""
    per_lane = n_values // 32
    keys, ids = list(keys), list(ids)
    stage = 0
    size = 2
    while size <= n_values:
        stride = size // 2
        while stride > 0:
            stage += 1
            tag = f"{p}{stage}_"
            if stride == 32:
                # The two values of a lane; the whole sequence goes up.
                a, b, ia, ib = keys[0], keys[1], ids[0], ids[1]
                out(f"""\
%{tag}klt = arith.cmpf olt, {b}, {a} : f32
%{tag}keq = arith.cmpf oeq, {b}, {a} : f32
%{tag}ilt = arith.cmpi slt, {ib}, {ia} : i32
%{tag}tie = arith.andi %{tag}keq, %{tag}ilt : i1
%{tag}swap = arith.ori %{tag}klt, %{tag}tie : i1
%{tag}a = arith.select %{tag}swap, {b}, {a} : f32
%{tag}b = arith.select %{tag}swap, {a}, {b} : f32
%{tag}ia = arith.select %{tag}swap, {ib}, {ia} : i32
%{tag}ib = arith.select %{tag}swap, {ia}, {ib} : i32""")
                keys, ids = [f"%{tag}a", f"%{tag}b"], [f"%{tag}ia", f"%{tag}ib"]
            else:
                new_keys, new_ids = [], []
                for v in range(per_lane):
                    t = f"{tag}{v}_"
                    k, i = keys[v], ids[v]
                    out(f"""\
%{t}s = arith.constant {stride} : i32
%{t}w = arith.constant 32 : i32
%{t}pk, %{t}vk = gpu.shuffle xor {k}, %{t}s, %{t}w : f32
%{t}pi, %{t}vi = gpu.shuffle xor {i}, %{t}s, %{t}w : i32
%{t}off = arith.constant {32 * v} : i32
%{t}pos = arith.addi {lane}, %{t}off : i32
%{t}sz = arith.constant {size} : i32
%{t}zero = arith.constant 0 : i32
%{t}upb = arith.andi %{t}pos, %{t}sz : i32
%{t}up = arith.cmpi eq, %{t}upb, %{t}zero : i32
%{t}lob = arith.andi %{t}pos, %{t}s : i32
%{t}lower = arith.cmpi eq, %{t}lob, %{t}zero : i32
%{t}plt0 = arith.cmpf olt, %{t}pk, {k} : f32
%{t}peq = arith.cmpf oeq, %{t}pk, {k} : f32
%{t}pilt = arith.cmpi slt, %{t}pi, {i} : i32
%{t}pitie = arith.andi %{t}peq, %{t}pilt : i1
%{t}plt = arith.ori %{t}plt0, %{t}pitie : i1
%{t}pgt0 = arith.cmpf ogt, %{t}pk, {k} : f32
%{t}pigt = arith.cmpi sgt, %{t}pi, {i} : i32
%{t}pgtie = arith.andi %{t}peq, %{t}pigt : i1
%{t}pgt = arith.ori %{t}pgt0, %{t}pgtie : i1
// The lower of a pair keeps the smaller when the run goes up.
%{t}min = arith.cmpi eq, %{t}up, %{t}lower : i1
%{t}take = arith.select %{t}min, %{t}plt, %{t}pgt : i1
%{t}k = arith.select %{t}take, %{t}pk, {k} : f32
%{t}i = arith.select %{t}take, %{t}pi, {i} : i32""")
                    new_keys.append(f"%{t}k")
                    new_ids.append(f"%{t}i")
                keys, ids = new_keys, new_ids
            stride //= 2
        size *= 2
    return keys, ids


def chunk_body():
    """A warp a chunk: the order of its 64 particles."""
    b = Lines()
    b(f"""\
%base = arith.muli %bx, %block : index
%item = arith.addi %base, %tx : index
%c0w = arith.constant 0 : index
%c1w = arith.constant 1 : index
%c2w = arith.constant 2 : index
%c32w = arith.constant 32 : index
%c64w = arith.constant 64 : index
%c2i = arith.constant 2 : i32
%c16i = arith.constant 16 : i32
%c32i = arith.constant 32 : i32
%c64i = arith.constant 64 : i32
%zero_i = arith.constant 0 : i32
%one_i = arith.constant 1 : i32
%t = arith.divui %item, %c32w : index
%lane = arith.remui %tx, %c32w : index
%lane32 = arith.index_cast %lane : index to i32
%warp = arith.divui %tx, %c32w : index
%places32 = memref.load %sizes_device[%c0w] : memref<3xi32, 1>
%places = arith.index_cast %places32 : i32 to index
%total_chunks = arith.divui %places, %c64w : index
%real_chunk = arith.cmpi ult, %t, %total_chunks : index
scf.if %real_chunk {{
  %t32 = arith.index_cast %t : index to i32
  // The column: the last whose first chunk is not after t.
  %lo_c, %hi_c = scf.while (%lo = %c0w, %hi = %columns) : (index, index) -> (index, index) {{
    %span = arith.subi %hi, %lo : index
    %go = arith.cmpi ugt, %span, %c1w : index
    scf.condition(%go) %lo, %hi : index, index
  }} do {{
  ^bb0(%lo: index, %hi: index):
    %sum = arith.addi %lo, %hi : index
    %mid = arith.divui %sum, %c2w : index
    %first_mid = memref.load %chunk_base[%mid] : memref<?xi32, 1>
    %after = arith.cmpi sgt, %first_mid, %t32 : i32
    %nlo = arith.select %after, %lo, %mid : index
    %nhi = arith.select %after, %mid, %hi : index
    scf.yield %nlo, %nhi : index, index
  }}
  %first32 = memref.load %chunk_base[%lo_c] : memref<?xi32, 1>
  %j32 = arith.subi %t32, %first32 : i32
  %key_begin = arith.muli %lo_c, %nzb : index
  %column1 = arith.addi %lo_c, %c1w : index
  %key_end = arith.muli %column1, %nzb : index
  %col_begin32 = memref.load %key_start[%key_begin] : memref<?xi32, 1>
  %col_end32 = memref.load %key_start[%key_end] : memref<?xi32, 1>
  %j64 = arith.muli %j32, %c64i : i32
  %begin32 = arith.addi %col_begin32, %j64 : i32
  %left32 = arith.subi %col_end32, %begin32 : i32
  %len32 = arith.minsi %left32, %c64i : i32
  %begin = arith.index_cast %begin32 : i32 to index
  // Two particles a lane: positions lane and lane + 32 of the chunk.
  %l1 = arith.addi %lane32, %c32i : i32
  %has_a = arith.cmpi slt, %lane32, %len32 : i32
  %has_b = arith.cmpi slt, %l1, %len32 : i32
  %l1_i = arith.index_cast %l1 : i32 to index
  %sa = arith.addi %begin, %lane : index
  %sb = arith.addi %begin, %l1_i : index
  %big = arith.constant 2139095040 : i32
  %inf = arith.bitcast %big : i32 to f32
  %none = arith.constant 2147483647 : i32
  %ia0 = scf.if %has_a -> (i32) {{
    %v = memref.load %sorted[%sa] : memref<?xi32, 1>
    scf.yield %v : i32
  }} else {{
    scf.yield %none : i32
  }}
  %ib0 = scf.if %has_b -> (i32) {{
    %v = memref.load %sorted[%sb] : memref<?xi32, 1>
    scf.yield %v : i32
  }} else {{
    scf.yield %none : i32
  }}
  %xa0 = scf.if %has_a -> (f32) {{
    %ii = arith.index_cast %ia0 : i32 to index
    %v = memref.load %wrapped[%ii, %c0w] : memref<?x3xf32, 1>
    scf.yield %v : f32
  }} else {{
    scf.yield %inf : f32
  }}
  %xb0 = scf.if %has_b -> (f32) {{
    %ii = arith.index_cast %ib0 : i32 to index
    %v = memref.load %wrapped[%ii, %c0w] : memref<?x3xf32, 1>
    scf.yield %v : f32
  }} else {{
    scf.yield %inf : f32
  }}""")
    inner = Lines()
    k64, i64 = bitonic(inner, "bx", 64, ["%xa0", "%xb0"], ["%ia0", "%ib0"], "%lane32")
    b(indent(inner.text(), 2).rstrip("\n"))
    b(f"""\
  // The chunk by x, into the memory of the block; then each half by y.
  %warp_slot0 = arith.muli %warp, %c64w : index
  %sa_at = arith.addi %warp_slot0, %lane : index
  %sb_at = arith.addi %warp_slot0, %l1_i : index
  memref.store {i64[0]}, %ids_wg[%sa_at] : memref<256xi32, {WG}>
  memref.store {i64[1]}, %ids_wg[%sb_at] : memref<256xi32, {WG}>
  %all = arith.constant -1 : i32
  nvvm.bar.warp.sync %all : i32
  %len1 = arith.addi %len32, %one_i : i32
  %h32 = arith.divsi %len1, %c2i : i32
  %chunk_place0 = arith.muli %t, %c64w : index""")
    for half in range(2):
        tag = f"h{half}_"
        frm = "%h32" if half else "%zero_i"
        cnt = "arith.subi %len32, %h32 : i32" if half else "arith.addi %h32, %zero_i : i32"
        b(f"""\
  %{tag}count = {cnt}
  %{tag}has = arith.cmpi slt, %lane32, %{tag}count : i32
  %{tag}at32 = arith.addi {frm}, %lane32 : i32
  %{tag}at = arith.index_cast %{tag}at32 : i32 to index
  %{tag}slot = arith.addi %warp_slot0, %{tag}at : index
  %{tag}i0 = scf.if %{tag}has -> (i32) {{
    %v = memref.load %ids_wg[%{tag}slot] : memref<256xi32, {WG}>
    scf.yield %v : i32
  }} else {{
    scf.yield %none : i32
  }}
  %{tag}y0 = scf.if %{tag}has -> (f32) {{
    %ii = arith.index_cast %{tag}i0 : i32 to index
    %v = memref.load %wrapped[%ii, %c1w] : memref<?x3xf32, 1>
    scf.yield %v : f32
  }} else {{
    scf.yield %inf : f32
  }}""")
        inner = Lines()
        k2, i2 = bitonic(inner, f"b{tag}", 32, [f"%{tag}y0"], [f"%{tag}i0"], "%lane32")
        b(indent(inner.text(), 2).rstrip("\n"))
        b(f"""\
  // Quarter {2 * half} or {2 * half + 1}: the first ceil(count / 2) by y, then the rest.
  %{tag}c1 = arith.addi %{tag}count, %one_i : i32
  %{tag}q = arith.divsi %{tag}c1, %c2i : i32
  %{tag}second = arith.cmpi sge, %lane32, %{tag}q : i32
  %{tag}rank_b = arith.subi %lane32, %{tag}q : i32
  %{tag}rank = arith.select %{tag}second, %{tag}rank_b, %lane32 : i32
  %{tag}quarter_b = arith.constant {2 * half + 1} : i32
  %{tag}quarter_a = arith.constant {2 * half} : i32
  %{tag}quarter = arith.select %{tag}second, %{tag}quarter_b, %{tag}quarter_a : i32
  %{tag}q16 = arith.muli %{tag}quarter, %c16i : i32
  %{tag}in_chunk = arith.addi %{tag}q16, %{tag}rank : i32
  %{tag}in_chunk_i = arith.index_cast %{tag}in_chunk : i32 to index
  %{tag}place = arith.addi %chunk_place0, %{tag}in_chunk_i : index
  scf.if %{tag}has {{
    memref.store {i2[0]}, %order[%{tag}place] : memref<?xi32, 1>
    %ii = arith.index_cast {i2[0]} : i32 to index
    %place32 = arith.index_cast %{tag}place : index to i32
    memref.store %place32, %place_of[%ii] : memref<?xi32, 1>
  }}""")
    b("}")
    return b.text()


def sort_partners(out, span_values):
    """Sorts the partners of a group in the memory of its warp, 256 values
    (keys (place << 4) | u; empty slots hold the largest i32), a bitonic
    network over the memory, 4 pairs a lane a stage."""
    size = 2
    stage = 0
    while size <= span_values:
        stride = size // 2
        while stride > 0:
            stage += 1
            for r in range(span_values // 2 // 32):
                t = f"ps{stage}_{r}_"
                out(f"""\
%{t}pair = arith.constant {32 * r} : index
%{t}tp = arith.addi %lane, %{t}pair : index
%{t}s = arith.constant {stride} : index
%{t}sm1 = arith.constant {stride - 1} : index
%{t}low = arith.andi %{t}tp, %{t}sm1 : index
%{t}twice = arith.addi %{t}tp, %{t}tp : index
%{t}a = arith.subi %{t}twice, %{t}low : index
%{t}b = arith.addi %{t}a, %{t}s : index
%{t}sz = arith.constant {size} : index
%{t}upb = arith.andi %{t}a, %{t}sz : index
%{t}z = arith.constant 0 : index
%{t}up = arith.cmpi eq, %{t}upb, %{t}z : index
%{t}aa = arith.addi %pbase, %{t}a : index
%{t}bb = arith.addi %pbase, %{t}b : index
%{t}va = memref.load %partners[%{t}aa] : memref<1024xi32, {WG}>
%{t}vb = memref.load %partners[%{t}bb] : memref<1024xi32, {WG}>
%{t}gt = arith.cmpi sgt, %{t}va, %{t}vb : i32
%{t}swap = arith.cmpi eq, %{t}gt, %{t}up : i1
%{t}na = arith.select %{t}swap, %{t}vb, %{t}va : i32
%{t}nb = arith.select %{t}swap, %{t}va, %{t}vb : i32
memref.store %{t}na, %partners[%{t}aa] : memref<1024xi32, {WG}>
memref.store %{t}nb, %partners[%{t}bb] : memref<1024xi32, {WG}>""")
            out("nvvm.bar.warp.sync %all : i32")
            stride //= 2
        size *= 2


def lists_body():
    """A warp a group: its list."""
    b = Lines()
    b(f"""\
%base = arith.muli %bx, %block : index
%item = arith.addi %base, %tx : index
%c0w = arith.constant 0 : index
%c1w = arith.constant 1 : index
%c2w = arith.constant 2 : index
%c3w = arith.constant 3 : index
%c4w = arith.constant 4 : index
%c16w = arith.constant 16 : index
%c32w = arith.constant 32 : index
%zero_i = arith.constant 0 : i32
%one_i = arith.constant 1 : i32
%c2i = arith.constant 2 : i32
%c16i = arith.constant 16 : i32
%c32i = arith.constant 32 : i32
%all = arith.constant -1 : i32
%g = arith.divui %item, %c32w : index
%lane = arith.remui %tx, %c32w : index
%lane32 = arith.index_cast %lane : index to i32
%warp = arith.divui %tx, %c32w : index
%places32 = memref.load %sizes_device[%c0w] : memref<3xi32, 1>
%places = arith.index_cast %places32 : i32 to index
%groups = arith.divui %places, %c16w : index
%real_group = arith.cmpi ult, %g, %groups : index
scf.if %real_group {{
  %first = arith.muli %g, %c16w : index
  %first32 = arith.index_cast %first : index to i32
  // The particles of the group relative to the center of its box, in the
  // memory of the block: x, y, z, and 1 or 0 for a real one.
  %box_lo_x = memref.load %boxes[%g, %c0w] : memref<?x8xf32, 1>
  %box_lo_y = memref.load %boxes[%g, %c1w] : memref<?x8xf32, 1>
  %box_lo_z = memref.load %boxes[%g, %c2w] : memref<?x8xf32, 1>
  %box_hi_x = memref.load %boxes[%g, %c3w] : memref<?x8xf32, 1>
  %c4b = arith.constant 4 : index
  %c5b = arith.constant 5 : index
  %box_hi_y = memref.load %boxes[%g, %c4b] : memref<?x8xf32, 1>
  %box_hi_z = memref.load %boxes[%g, %c5b] : memref<?x8xf32, 1>
  %halff = arith.constant 0.5 : f32
  %sum_x = arith.addf %box_lo_x, %box_hi_x : f32
  %sum_y = arith.addf %box_lo_y, %box_hi_y : f32
  %sum_z = arith.addf %box_lo_z, %box_hi_z : f32
  %cx = arith.mulf %sum_x, %halff : f32
  %cy = arith.mulf %sum_y, %halff : f32
  %cz = arith.mulf %sum_z, %halff : f32
  %dif_x = arith.subf %box_hi_x, %box_lo_x : f32
  %dif_y = arith.subf %box_hi_y, %box_lo_y : f32
  %dif_z = arith.subf %box_hi_z, %box_lo_z : f32
  %hx = arith.mulf %dif_x, %halff : f32
  %hy = arith.mulf %dif_y, %halff : f32
  %hz = arith.mulf %dif_z, %halff : f32
  %rel0 = arith.muli %warp, %c16w : index
  %mine_lane = arith.cmpi ult, %lane, %c16w : index
  scf.if %mine_lane {{
    %p = arith.addi %first, %lane : index
    %pi = memref.load %order[%p] : memref<?xi32, 1>
    %real = arith.cmpi sge, %pi, %zero_i : i32
    %xi = memref.load %xp[%p, %c0w] : memref<?x4xf32, 1>
    %yi = memref.load %xp[%p, %c1w] : memref<?x4xf32, 1>
    %zi = memref.load %xp[%p, %c2w] : memref<?x4xf32, 1>
    %ex0 = arith.subf %xi, %cx : f32
    %ey0 = arith.subf %yi, %cy : f32
    %ez0 = arith.subf %zi, %cz : f32
    %rx = func.call @mdrt_gpu_groups_image(%ex0, %flx, %filx) : (f32, f32, f32) -> f32
    %ry = func.call @mdrt_gpu_groups_image(%ey0, %fly, %fily) : (f32, f32, f32) -> f32
    %rz = func.call @mdrt_gpu_groups_image(%ez0, %flz, %filz) : (f32, f32, f32) -> f32
    %one_ff = arith.constant 1.0 : f32
    %zero_ff = arith.constant 0.0 : f32
    %flag = arith.select %real, %one_ff, %zero_ff : f32
    %at = arith.addi %rel0, %lane : index
    memref.store %rx, %rel_wg[%at, %c0w] : memref<64x4xf32, {WG}>
    memref.store %ry, %rel_wg[%at, %c1w] : memref<64x4xf32, {WG}>
    memref.store %rz, %rel_wg[%at, %c2w] : memref<64x4xf32, {WG}>
    memref.store %flag, %rel_wg[%at, %c3w] : memref<64x4xf32, {WG}>
  }}
  // The partners of the excluded pairs of the group: (place << 4) | u,
  // sorted, 256 at most.
  %c256 = arith.constant 256 : index
  %pbase = arith.muli %warp, %c256 : index
  %largest_i = arith.constant 2147483647 : i32
  scf.for %s = %lane to %c256 step %c32w {{
    %at = arith.addi %pbase, %s : index
    memref.store %largest_i, %partners[%at] : memref<1024xi32, {WG}>
  }}
  nvvm.bar.warp.sync %all : i32
  %rows = memref.dim %excluded, %c0w : memref<?x?xi32, 1>
  %np_all = scf.for %u = %c0w to %c16w step %c1w iter_args(%np = %c0w) -> (index) {{
    %p = arith.addi %first, %u : index
    %pi = memref.load %order[%p] : memref<?xi32, 1>
    %pii = arith.index_cast %pi : i32 to index
    %real = arith.cmpi sge, %pi, %zero_i : i32
    %in_rows = arith.cmpi ult, %pii, %rows : index
    %has = arith.andi %real, %in_rows : i1
    %count = scf.if %has -> (index) {{
      %c32v = memref.load %excluded[%pii, %c0w] : memref<?x?xi32, 1>
      %cv = arith.index_cast %c32v : i32 to index
      scf.yield %cv : index
    }} else {{
      scf.yield %c0w : index
    }}
    scf.for %k = %lane to %count step %c32w {{
      %partner = func.call @mdrt_gpu_groups_partner(%excluded, %pii, %k) : (memref<?x?xi32, 1>, index, index) -> i32
      %pj = arith.index_cast %partner : i32 to index
      %q = memref.load %place_of[%pj] : memref<?xi32, 1>
      %four = arith.constant 4 : i32
      %shifted = arith.shli %q, %four : i32
      %u32 = arith.index_cast %u : index to i32
      %partner_key = arith.ori %shifted, %u32 : i32
      %slot0 = arith.addi %np, %k : index
      %fits = arith.cmpi ult, %slot0, %c256 : index
      scf.if %fits {{
        %at = arith.addi %pbase, %slot0 : index
        memref.store %partner_key, %partners[%at] : memref<1024xi32, {WG}>
      }}
    }}
    %next = arith.addi %np, %count : index
    scf.yield %next : index
  }}
  %np = arith.minui %np_all, %c256 : index
  nvvm.bar.warp.sync %all : i32""")
    inner = Lines()
    sort_partners(inner, 256)
    b(indent(inner.text(), 2).rstrip("\n"))
    b(f"""\
  // The cells of the grid within the reach of the box.
  %ecx = arith.addf %hx, %freach : f32
  %ecy = arith.addf %hy, %freach : f32
  %ecz = arith.addf %hz, %freach : f32
  %lox_f = arith.subf %cx, %ecx : f32
  %loy_f = arith.subf %cy, %ecy : f32
  %loz_f = arith.subf %cz, %ecz : f32
  %hix_f = arith.addf %cx, %ecx : f32
  %hiy_f = arith.addf %cy, %ecy : f32
  %hiz_f = arith.addf %cz, %ecz : f32
  %gnxf = arith.sitofp %gnx32 : i32 to f32
  %gnyf = arith.sitofp %gny32 : i32 to f32
  %gnzf = arith.sitofp %gnz32 : i32 to f32
  %rsx0 = arith.mulf %lox_f, %filx : f32
  %rsy0 = arith.mulf %loy_f, %fily : f32
  %rsz0 = arith.mulf %loz_f, %filz : f32
  %sx1 = arith.mulf %rsx0, %gnxf : f32
  %sy1 = arith.mulf %rsy0, %gnyf : f32
  %sz1 = arith.mulf %rsz0, %gnzf : f32
  %rtx0 = arith.mulf %hix_f, %filx : f32
  %rty0 = arith.mulf %hiy_f, %fily : f32
  %rtz0 = arith.mulf %hiz_f, %filz : f32
  %tx1 = arith.mulf %rtx0, %gnxf : f32
  %ty1 = arith.mulf %rty0, %gnyf : f32
  %tz1 = arith.mulf %rtz0, %gnzf : f32
  %sxf = math.floor %sx1 : f32
  %syf = math.floor %sy1 : f32
  %szf = math.floor %sz1 : f32
  %txf = math.floor %tx1 : f32
  %tyf = math.floor %ty1 : f32
  %tzf = math.floor %tz1 : f32
  %c0x = arith.fptosi %sxf : f32 to i32
  %c0y = arith.fptosi %syf : f32 to i32
  %c0z = arith.fptosi %szf : f32 to i32
  %c1x0 = arith.fptosi %txf : f32 to i32
  %c1y0 = arith.fptosi %tyf : f32 to i32
  %c1z0 = arith.fptosi %tzf : f32 to i32
  // A range wider than the grid is the whole grid.
  %wx = arith.subi %c1x0, %c0x : i32
  %wy = arith.subi %c1y0, %c0y : i32
  %wz = arith.subi %c1z0, %c0z : i32
  %wide_x = arith.cmpi sge, %wx, %gnx32 : i32
  %wide_y = arith.cmpi sge, %wy, %gny32 : i32
  %wide_z = arith.cmpi sge, %wz, %gnz32 : i32
  %gnx1 = arith.subi %gnx32, %one_i : i32
  %gny1 = arith.subi %gny32, %one_i : i32
  %gnz1 = arith.subi %gnz32, %one_i : i32
  %fx0 = arith.select %wide_x, %zero_i, %c0x : i32
  %fy0 = arith.select %wide_y, %zero_i, %c0y : i32
  %fz0 = arith.select %wide_z, %zero_i, %c0z : i32
  %fx1 = arith.select %wide_x, %gnx1, %c1x0 : i32
  %fy1 = arith.select %wide_y, %gny1, %c1y0 : i32
  %fz1 = arith.select %wide_z, %gnz1, %c1z0 : i32
  %reach2 = arith.mulf %freach, %freach : f32
  %lane_bit = arith.shli %one_i, %lane32 : i32
  %below = arith.subi %lane_bit, %one_i : i32
  %first16 = arith.addi %first32, %c16i : i32
  %width = memref.dim %entries, %c1w : memref<?x?xi32, 1>
  %fz1p = arith.addi %fz1, %one_i : i32
  %fy1p = arith.addi %fy1, %one_i : i32
  %count_all = scf.for %zz = %fz0 to %fz1p step %one_i iter_args(%cz_count = %zero_i) -> (i32) : i32 {{
    %zm = arith.remsi %zz, %gnz32 : i32
    %zneg = arith.cmpi slt, %zm, %zero_i : i32
    %zw = arith.addi %zm, %gnz32 : i32
    %iz = arith.select %zneg, %zw, %zm : i32
    %cy_count = scf.for %yy = %fy0 to %fy1p step %one_i iter_args(%cy0 = %cz_count) -> (i32) : i32 {{
      %ym = arith.remsi %yy, %gny32 : i32
      %yneg = arith.cmpi slt, %ym, %zero_i : i32
      %yw = arith.addi %ym, %gny32 : i32
      %iy = arith.select %yneg, %yw, %ym : i32
      %rowz = arith.muli %iz, %gny32 : i32
      %rowzy = arith.addi %rowz, %iy : i32
      %row = arith.muli %rowzy, %gnx32 : i32
      // The run along x, in one or two pieces around the edge.
      %under = arith.cmpi slt, %fx0, %zero_i : i32
      %over = arith.cmpi sge, %fx1, %gnx32 : i32
      %a_from = arith.addi %fx0, %gnx32 : i32
      %from1 = arith.select %under, %a_from, %fx0 : i32
      %to1 = arith.select %under, %gnx1, %fx1 : i32
      %to1b = arith.select %over, %gnx1, %to1 : i32
      %two_pieces = arith.ori %under, %over : i1
      %to2a = arith.subi %fx1, %gnx32 : i32
      %to2 = arith.select %under, %fx1, %to2a : i32
      %pieces = arith.select %two_pieces, %c2i, %one_i : i32
      %cp_count = scf.for %piece = %zero_i to %pieces step %one_i iter_args(%cp0 = %cy0) -> (i32) : i32 {{
        %is_second = arith.cmpi ne, %piece, %zero_i : i32
        %from = arith.select %is_second, %zero_i, %from1 : i32
        %to = arith.select %is_second, %to2, %to1b : i32
        %cfrom = arith.addi %row, %from : i32
        %to_next = arith.addi %to, %one_i : i32
        %cto = arith.addi %row, %to_next : i32
        %cfrom_i = arith.index_cast %cfrom : i32 to index
        %cto_i = arith.index_cast %cto : i32 to index
        %begin = memref.load %gstart[%cfrom_i] : memref<?xi32, 1>
        %end = memref.load %gstart[%cto_i] : memref<?xi32, 1>
        %cs_count = scf.for %s0 = %begin to %end step %c32i iter_args(%cs = %cp0) -> (i32) : i32 {{
          %s = arith.addi %s0, %lane32 : i32
          %in_run = arith.cmpi slt, %s, %end : i32
          %bits = scf.if %in_run -> (i32) {{
            %si = arith.index_cast %s : i32 to index
            %q = memref.load %gplace[%si] : memref<?xi32, 1>
            %later = arith.cmpi sge, %q, %first32 : i32
            %b2 = scf.if %later -> (i32) {{
              %qi = arith.index_cast %q : i32 to index
              %xq = memref.load %xp[%qi, %c0w] : memref<?x4xf32, 1>
              %yq = memref.load %xp[%qi, %c1w] : memref<?x4xf32, 1>
              %zq = memref.load %xp[%qi, %c2w] : memref<?x4xf32, 1>
              %dx0 = arith.subf %xq, %cx : f32
              %dy0 = arith.subf %yq, %cy : f32
              %dz0 = arith.subf %zq, %cz : f32
              %rqx = func.call @mdrt_gpu_groups_image(%dx0, %flx, %filx) : (f32, f32, f32) -> f32
              %rqy = func.call @mdrt_gpu_groups_image(%dy0, %fly, %fily) : (f32, f32, f32) -> f32
              %rqz = func.call @mdrt_gpu_groups_image(%dz0, %flz, %filz) : (f32, f32, f32) -> f32
              %ax = math.absf %rqx : f32
              %ay = math.absf %rqy : f32
              %az = math.absf %rqz : f32
              %zero_f = arith.constant 0.0 : f32
              %bx0 = arith.subf %ax, %hx : f32
              %by0 = arith.subf %ay, %hy : f32
              %bz0 = arith.subf %az, %hz : f32
              %bxd = arith.maximumf %bx0, %zero_f : f32
              %byd = arith.maximumf %by0, %zero_f : f32
              %bzd = arith.maximumf %bz0, %zero_f : f32
              %bx2 = arith.mulf %bxd, %bxd : f32
              %by2 = arith.mulf %byd, %byd : f32
              %bz2 = arith.mulf %bzd, %bzd : f32
              %bxy = arith.addf %bx2, %by2 : f32
              %bd2 = arith.addf %bxy, %bz2 : f32
              %near = arith.cmpf ole, %bd2, %reach2 : f32
              %b3 = scf.if %near -> (i32) {{
                %own = arith.cmpi slt, %q, %first16 : i32
                %m = scf.for %u = %c0w to %c16w step %c1w iter_args(%mm = %zero_i) -> (i32) {{
                  %at = arith.addi %rel0, %u : index
                  %gx_ = memref.load %rel_wg[%at, %c0w] : memref<64x4xf32, {WG}>
                  %gy_ = memref.load %rel_wg[%at, %c1w] : memref<64x4xf32, {WG}>
                  %gz_ = memref.load %rel_wg[%at, %c2w] : memref<64x4xf32, {WG}>
                  %gflag = memref.load %rel_wg[%at, %c3w] : memref<64x4xf32, {WG}>
                  %ex = arith.subf %rqx, %gx_ : f32
                  %ey = arith.subf %rqy, %gy_ : f32
                  %ez = arith.subf %rqz, %gz_ : f32
                  %ex2 = arith.mulf %ex, %ex : f32
                  %ey2 = arith.mulf %ey, %ey : f32
                  %ez2 = arith.mulf %ez, %ez : f32
                  %exy = arith.addf %ex2, %ey2 : f32
                  %e2 = arith.addf %exy, %ez2 : f32
                  %within = arith.cmpf ole, %e2, %reach2 : f32
                  %u32 = arith.index_cast %u : index to i32
                  %pu = arith.addi %first32, %u32 : i32
                  %not_after = arith.cmpi sle, %q, %pu : i32
                  %same = arith.andi %own, %not_after : i1
                  %true = arith.constant true
                  %distinct = arith.xori %same, %true : i1
                  %half_f = arith.constant 0.5 : f32
                  %is_real = arith.cmpf ogt, %gflag, %half_f : f32
                  %ok0 = arith.andi %within, %distinct : i1
                  %ok = arith.andi %ok0, %is_real : i1
                  %bit0 = arith.shli %one_i, %u32 : i32
                  %bit = arith.select %ok, %bit0, %zero_i : i32
                  %nm = arith.ori %mm, %bit : i32
                  scf.yield %nm : i32
                }}
                // The excluded pairs: a binary search among the sorted
                // partners for the first at the place q.
                %any = arith.cmpi ne, %m, %zero_i : i32
                %mex = scf.if %any -> (i32) {{
                  %four = arith.constant 4 : i32
                  %lo_r, %hi_r = scf.while (%lo = %c0w, %hi = %np) : (index, index) -> (index, index) {{
                    %go = arith.cmpi ult, %lo, %hi : index
                    scf.condition(%go) %lo, %hi : index, index
                  }} do {{
                  ^bb0(%lo: index, %hi: index):
                    %sum = arith.addi %lo, %hi : index
                    %mid = arith.divui %sum, %c2w : index
                    %at = arith.addi %pbase, %mid : index
                    %v = memref.load %partners[%at] : memref<1024xi32, {WG}>
                    %vq = arith.shrsi %v, %four : i32
                    %less = arith.cmpi slt, %vq, %q : i32
                    %mid1 = arith.addi %mid, %c1w : index
                    %nlo = arith.select %less, %mid1, %lo : index
                    %nhi = arith.select %less, %hi, %mid : index
                    scf.yield %nlo, %nhi : index, index
                  }}
                  %cleared, %e_end = scf.while (%mm = %m, %e = %lo_r) : (i32, index) -> (i32, index) {{
                    %in = arith.cmpi ult, %e, %np : index
                    %at = arith.addi %pbase, %e : index
                    %safe = arith.select %in, %at, %pbase : index
                    %v = memref.load %partners[%safe] : memref<1024xi32, {WG}>
                    %vq = arith.shrsi %v, %four : i32
                    %match = arith.cmpi eq, %vq, %q : i32
                    %go = arith.andi %in, %match : i1
                    scf.condition(%go) %mm, %e : i32, index
                  }} do {{
                  ^bb0(%mm: i32, %e: index):
                    %at = arith.addi %pbase, %e : index
                    %v = memref.load %partners[%at] : memref<1024xi32, {WG}>
                    %fifteen = arith.constant 15 : i32
                    %u = arith.andi %v, %fifteen : i32
                    %bit = arith.shli %one_i, %u : i32
                    %all_bits = arith.constant -1 : i32
                    %keep = arith.xori %bit, %all_bits : i32
                    %nm = arith.andi %mm, %keep : i32
                    %e1 = arith.addi %e, %c1w : index
                    scf.yield %nm, %e1 : i32, index
                  }}
                  scf.yield %cleared : i32
                }} else {{
                  scf.yield %m : i32
                }}
                scf.yield %mex : i32
              }} else {{
                scf.yield %zero_i : i32
              }}
              scf.yield %b3 : i32
            }} else {{
              scf.yield %zero_i : i32
            }}
            scf.yield %b2 : i32
          }} else {{
            scf.yield %zero_i : i32
          }}
          // The entries of the lanes that kept a candidate, in the order
          // of the lanes.
          %keep = arith.cmpi ne, %bits, %zero_i : i32
          %kept = gpu.ballot %keep : i32
          %before_bits = arith.andi %kept, %below : i32
          %rank = math.ctpop %before_bits : i32
          %slot = arith.addi %cs, %rank : i32
          %slot_i = arith.index_cast %slot : i32 to index
          %fits = arith.cmpi ult, %slot_i, %width : index
          %store = arith.andi %keep, %fits : i1
          scf.if %store {{
            %si = arith.index_cast %s : i32 to index
            %q = memref.load %gplace[%si] : memref<?xi32, 1>
            memref.store %q, %entries[%g, %slot_i] : memref<?x?xi32, 1>
            memref.store %bits, %masks[%g, %slot_i] : memref<?x?xi32, 1>
          }}
          %n_kept = math.ctpop %kept : i32
          %next = arith.addi %cs, %n_kept : i32
          scf.yield %next : i32
        }}
        scf.yield %cs_count : i32
      }}
      scf.yield %cp_count : i32
    }}
    scf.yield %cy_count : i32
  }}
  %lane0 = arith.cmpi eq, %lane, %c0w : index
  scf.if %lane0 {{
    memref.store %count_all, %counts[%g] : memref<?xi32, 1>
{indent(atomic_max("mx_", "%sizes_device", "%count_all"), 4).rstrip()}
  }}
}}""")
    return b.text()


def build():
    t = []
    t.append("""\
func.func private @mdrt_gpu_build_neighbors_groups(
    %x: memref<?x3xf64, 1>, %box: vector<3xf64>, %reach: f64,
    %excluded: memref<?x?xi32, 1>, %order: memref<?xi32, 1>,
    %place_of: memref<?xi32, 1>, %entries: memref<?x?xi32, 1>,
    %masks: memref<?x?xi32, 1>, %counts: memref<?xi32, 1>,
    %units: memref<?xi32, 1>, %sizes: memref<3xi32>) {
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %block = arith.constant 128 : index
  %chunk = arith.constant 256 : index
  %n = memref.dim %x, %c0 : memref<?x3xf64, 1>
  %capacity = memref.dim %order, %c0 : memref<?xi32, 1>
  %group_capacity = memref.dim %counts, %c0 : memref<?xi32, 1>
  %unit_capacity = memref.dim %units, %c0 : memref<?xi32, 1>
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %flx = arith.truncf %lx : f64 to f32
  %fly = arith.truncf %ly : f64 to f32
  %flz = arith.truncf %lz : f64 to f32
  %funit = arith.constant 1.0 : f32
  %filx = arith.divf %funit, %flx : f32
  %fily = arith.divf %funit, %fly : f32
  %filz = arith.divf %funit, %flz : f32
  // The reach, a little wider than asked, for the rounding of f32.
  %slack = arith.constant 1.000001 : f64
  %reach_wide = arith.mulf %reach, %slack : f64
  %freach = arith.truncf %reach_wide : f64 to f32

  // The columns: about 64 particles in a cube of their width.
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %n64 = arith.index_cast %n : index to i64
  %nf = arith.sitofp %n64 : i64 to f64
  %density = arith.divf %nf, %volume : f64
  %sixty_four = arith.constant 64.0 : f64
  %cube = arith.divf %sixty_four, %density : f64
  %third = arith.constant 0.3333333333333333 : f64
  %side = math.powf %cube, %third : f64
  %fcx = arith.divf %lx, %side : f64
  %fcy = arith.divf %ly, %side : f64
  %fcxf = math.floor %fcx : f64
  %fcyf = math.floor %fcy : f64
  %one_f = arith.constant 1.0 : f64
  %ncxf = arith.maximumf %fcxf, %one_f : f64
  %ncyf = arith.maximumf %fcyf, %one_f : f64
  %ncx64 = arith.fptosi %ncxf : f64 to i64
  %ncy64 = arith.fptosi %ncyf : f64 to i64
  %ncx = arith.index_cast %ncx64 : i64 to index
  %ncy = arith.index_cast %ncy64 : i64 to index
  %columns = arith.muli %ncx, %ncy : index
  // Bins along z: two for each particle of a column, on average.
  %n2 = arith.addi %n, %n : index
  %nzb0 = arith.divui %n2, %columns : index
  %nzb = arith.maxui %nzb0, %c1 : index
  %keys = arith.muli %columns, %nzb : index
  %keys1 = arith.addi %keys, %c1 : index

  // The grid of the candidates: cells of half the reach, 3 a side or more.
  %half = arith.constant 0.5 : f64
  %cell = arith.mulf %reach, %half : f64
  %gxf0 = arith.divf %lx, %cell : f64
  %gyf0 = arith.divf %ly, %cell : f64
  %gzf0 = arith.divf %lz, %cell : f64
  %three_f = arith.constant 3.0 : f64
  %gxf1 = math.floor %gxf0 : f64
  %gyf1 = math.floor %gyf0 : f64
  %gzf1 = math.floor %gzf0 : f64
  %gxf = arith.maximumf %gxf1, %three_f : f64
  %gyf = arith.maximumf %gyf1, %three_f : f64
  %gzf = arith.maximumf %gzf1, %three_f : f64
  %gx64 = arith.fptosi %gxf : f64 to i64
  %gy64 = arith.fptosi %gyf : f64 to i64
  %gz64 = arith.fptosi %gzf : f64 to i64
  %gnx = arith.index_cast %gx64 : i64 to index
  %gny = arith.index_cast %gy64 : i64 to index
  %gnz = arith.index_cast %gz64 : i64 to index
  %gnx32 = arith.trunci %gx64 : i64 to i32
  %gny32 = arith.trunci %gy64 : i64 to i32
  %gnz32 = arith.trunci %gz64 : i64 to i32
  %gxy = arith.muli %gnx, %gny : index
  %gcells = arith.muli %gxy, %gnz : index
  %gcells1 = arith.addi %gcells, %c1 : index

  %grid_of_n = func.call @mdrt_gpu_groups_grid(%n, %block) : (index, index) -> index
  %grid_of_keys = func.call @mdrt_gpu_groups_grid(%keys, %block) : (index, index) -> index
  %grid_of_gcells = func.call @mdrt_gpu_groups_grid(%gcells, %block) : (index, index) -> index
  %grid_of_capacity = func.call @mdrt_gpu_groups_grid(%capacity, %block) : (index, index) -> index
  %grid_of_groups = func.call @mdrt_gpu_groups_grid(%group_capacity, %block) : (index, index) -> index

  %wrapped = gpu.alloc (%n) : memref<?x3xf32, 1>
  %key = gpu.alloc (%n) : memref<?xi32, 1>
  %key_count = gpu.alloc (%keys) : memref<?xi32, 1>
  %key_start = gpu.alloc (%keys1) : memref<?xi32, 1>
  %key_cursor = gpu.alloc (%keys) : memref<?xi32, 1>
  %sorted = gpu.alloc (%n) : memref<?xi32, 1>
  %chunk_base = gpu.alloc (%columns) : memref<?xi32, 1>
  %sizes_device = gpu.alloc () : memref<3xi32, 1>
  %xp = gpu.alloc (%capacity) : memref<?x4xf32, 1>
  %gkey = gpu.alloc (%capacity) : memref<?xi32, 1>
  %gcount = gpu.alloc (%gcells) : memref<?xi32, 1>
  %gstart = gpu.alloc (%gcells1) : memref<?xi32, 1>
  %gcursor = gpu.alloc (%gcells) : memref<?xi32, 1>
  %gplace = gpu.alloc (%n) : memref<?xi32, 1>
  %boxes = gpu.alloc (%group_capacity) : memref<?x8xf32, 1>
  %group_units = gpu.alloc (%group_capacity) : memref<?xi32, 1>
  %unit_start1 = arith.addi %group_capacity, %c1 : index
  %unit_start = gpu.alloc (%unit_start1) : memref<?xi32, 1>
  %unit_cursor = gpu.alloc (%group_capacity) : memref<?xi32, 1>

  //===--------------------------------------------------------------------===//
  // The compact order
  //===--------------------------------------------------------------------===//

""")
    t.append(clear("%grid_of_keys", "%key_count", "%keys"))
    t.append(clear("%grid_of_capacity", "%order", "%capacity", "-1"))
    t.append("  // The key of each particle, and its position wrapped into the cell.\n")
    t.append(launch("%grid_of_n", per_item("%n", f"""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
%one = arith.constant 1 : i32
%xi = memref.load %x[%item, %i0] : memref<?x3xf64, 1>
%yi = memref.load %x[%item, %i1] : memref<?x3xf64, 1>
%zi = memref.load %x[%item, %i2] : memref<?x3xf64, 1>
%x0 = arith.mulf %xi, %ilx : f64
%x1 = math.floor %x0 : f64
%x2 = arith.mulf %x1, %lx : f64
%wx = arith.subf %xi, %x2 : f64
%y0 = arith.mulf %yi, %ily : f64
%y1 = math.floor %y0 : f64
%y2 = arith.mulf %y1, %ly : f64
%wy = arith.subf %yi, %y2 : f64
%z0 = arith.mulf %zi, %ilz : f64
%z1 = math.floor %z0 : f64
%z2 = arith.mulf %z1, %lz : f64
%wz = arith.subf %zi, %z2 : f64
%fx = arith.truncf %wx : f64 to f32
%fy = arith.truncf %wy : f64 to f32
%fz = arith.truncf %wz : f64 to f32
memref.store %fx, %wrapped[%item, %i0] : memref<?x3xf32, 1>
memref.store %fy, %wrapped[%item, %i1] : memref<?x3xf32, 1>
memref.store %fz, %wrapped[%item, %i2] : memref<?x3xf32, 1>
%ux = arith.mulf %wx, %ilx : f64
%uy = arith.mulf %wy, %ily : f64
%uz = arith.mulf %wz, %ilz : f64
%ncx_f = arith.sitofp %ncx64 : i64 to f64
%ncy_f = arith.sitofp %ncy64 : i64 to f64
%nzb64 = arith.index_cast %nzb : index to i64
%nzb_f = arith.sitofp %nzb64 : i64 to f64
%vx = arith.mulf %ux, %ncx_f : f64
%vy = arith.mulf %uy, %ncy_f : f64
%vz = arith.mulf %uz, %nzb_f : f64
%kx64 = arith.fptosi %vx : f64 to i64
%ky64 = arith.fptosi %vy : f64 to i64
%kz64 = arith.fptosi %vz : f64 to i64
%kx0 = arith.index_cast %kx64 : i64 to index
%ky0 = arith.index_cast %ky64 : i64 to index
%kz0 = arith.index_cast %kz64 : i64 to index
%ncx1 = arith.subi %ncx, %i1 : index
%ncy1 = arith.subi %ncy, %i1 : index
%nzb1 = arith.subi %nzb, %i1 : index
%kx = arith.minsi %kx0, %ncx1 : index
%ky = arith.minsi %ky0, %ncy1 : index
%kz = arith.minsi %kz0, %nzb1 : index
%col_y = arith.muli %ky, %ncx : index
%column = arith.addi %col_y, %kx : index
%col_z = arith.muli %column, %nzb : index
%k = arith.addi %col_z, %kz : index
%k32 = arith.index_cast %k : index to i32
memref.store %k32, %key[%item] : memref<?xi32, 1>
{atomic_add("ka_", "%key_count", "%k", "%one", "%ka_old")}""")))
    t.append(scan("ks_", "%key_count", "%key_start", "%key_cursor", "%keys"))
    t.append("  // Each particle takes the next slot of its key; the particles of a\n  // key are then sorted by number.\n")
    t.append(launch("%grid_of_n", per_item("%n", f"""\
%one = arith.constant 1 : i32
%k32 = memref.load %key[%item] : memref<?xi32, 1>
%k = arith.index_cast %k32 : i32 to index
{atomic_add("kc_", "%key_cursor", "%k", "%one", "%slot32")}\
%slot = arith.index_cast %slot32 : i32 to index
%i32v = arith.index_cast %item : index to i32
memref.store %i32v, %sorted[%slot] : memref<?xi32, 1>""")))
    t.append(sort_bins("%grid_of_keys", "%key_start", "%sorted", "%keys"))
    t.append("  // The first chunk of each column, in one thread, and the places.\n")
    t.append(launch("%c1", f"""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%none = arith.constant 0 : i32
%sixty_three = arith.constant 63 : i32
%six = arith.constant 6 : i32
%chunks_all = scf.for %c = %i0 to %columns step %i1 iter_args(%before = %none) -> (i32) {{
  memref.store %before, %chunk_base[%c] : memref<?xi32, 1>
  %kb = arith.muli %c, %nzb : index
  %c1_ = arith.addi %c, %i1 : index
  %ke = arith.muli %c1_, %nzb : index
  %b32 = memref.load %key_start[%kb] : memref<?xi32, 1>
  %e32 = memref.load %key_start[%ke] : memref<?xi32, 1>
  %len = arith.subi %e32, %b32 : i32
  %len63 = arith.addi %len, %sixty_three : i32
  %nch = arith.shrsi %len63, %six : i32
  %t = arith.addi %before, %nch : i32
  scf.yield %t : i32
}}
%sixty_four_i = arith.constant 64 : i32
%places = arith.muli %chunks_all, %sixty_four_i : i32
memref.store %places, %sizes_device[%i0] : memref<3xi32, 1>
memref.store %none, %sizes_device[%i1] : memref<3xi32, 1>
%i2 = arith.constant 2 : index
memref.store %none, %sizes_device[%i2] : memref<3xi32, 1>""", threads="%c1"))
    t.append("""\
  // The order: a warp a chunk of 64 particles. There are at most n / 32 +
  // (one for each column) chunks; the warps beyond the last do nothing.
  %c32l = arith.constant 32 : index
  %chunk_bound0 = arith.divui %n, %c32l : index
  %chunk_bound1 = arith.addi %chunk_bound0, %columns : index
  %chunk_threads = arith.muli %chunk_bound1, %c32l : index
  %grid_of_chunks = func.call @mdrt_gpu_groups_grid(%chunk_threads, %block) : (index, index) -> index
""")
    t.append(launch("%grid_of_chunks", chunk_body(),
                    workgroup=f"%ids_wg : memref<256xi32, {WG}>"))
    t.append("""\
  %key_plain = memref.memory_space_cast %key : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %key_plain : memref<?xi32>
  %key_count_plain = memref.memory_space_cast %key_count : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %key_count_plain : memref<?xi32>
  %key_start_plain = memref.memory_space_cast %key_start : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %key_start_plain : memref<?xi32>
  %key_cursor_plain = memref.memory_space_cast %key_cursor : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %key_cursor_plain : memref<?xi32>
  %sorted_plain = memref.memory_space_cast %sorted : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %sorted_plain : memref<?xi32>
  %chunk_base_plain = memref.memory_space_cast %chunk_base : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %chunk_base_plain : memref<?xi32>

  //===--------------------------------------------------------------------===//
  // The positions of the places, and the grid of the candidates
  //===--------------------------------------------------------------------===//

""")
    t.append(clear("%grid_of_gcells", "%gcount", "%gcells"))
    t.append(launch("%grid_of_capacity", per_item("%capacity", f"""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
%i3 = arith.constant 3 : index
%zero = arith.constant 0 : i32
%one = arith.constant 1 : i32
%places32 = memref.load %sizes_device[%i0] : memref<3xi32, 1>
%places = arith.index_cast %places32 : i32 to index
%used = arith.cmpi ult, %item, %places : index
%pi = memref.load %order[%item] : memref<?xi32, 1>
%real0 = arith.cmpi sge, %pi, %zero : i32
%real = arith.andi %used, %real0 : i1
%none = arith.constant -1 : i32
scf.if %real {{
  %ii = arith.index_cast %pi : i32 to index
  %xw = memref.load %wrapped[%ii, %i0] : memref<?x3xf32, 1>
  %yw = memref.load %wrapped[%ii, %i1] : memref<?x3xf32, 1>
  %zw = memref.load %wrapped[%ii, %i2] : memref<?x3xf32, 1>
  memref.store %xw, %xp[%item, %i0] : memref<?x4xf32, 1>
  memref.store %yw, %xp[%item, %i1] : memref<?x4xf32, 1>
  memref.store %zw, %xp[%item, %i2] : memref<?x4xf32, 1>
  %gxf_ = arith.sitofp %gnx32 : i32 to f32
  %gyf_ = arith.sitofp %gny32 : i32 to f32
  %gzf_ = arith.sitofp %gnz32 : i32 to f32
  %ux_ = arith.mulf %xw, %filx : f32
  %uy_ = arith.mulf %yw, %fily : f32
  %uz_ = arith.mulf %zw, %filz : f32
  %tx_ = arith.mulf %ux_, %gxf_ : f32
  %ty_ = arith.mulf %uy_, %gyf_ : f32
  %tz_ = arith.mulf %uz_, %gzf_ : f32
  %kx0 = arith.fptosi %tx_ : f32 to i32
  %ky0 = arith.fptosi %ty_ : f32 to i32
  %kz0 = arith.fptosi %tz_ : f32 to i32
  %gx1 = arith.subi %gnx32, %one : i32
  %gy1 = arith.subi %gny32, %one : i32
  %gz1 = arith.subi %gnz32, %one : i32
  %kx1 = arith.minsi %kx0, %gx1 : i32
  %ky1 = arith.minsi %ky0, %gy1 : i32
  %kz1 = arith.minsi %kz0, %gz1 : i32
  %kx = arith.maxsi %kx1, %zero : i32
  %ky = arith.maxsi %ky1, %zero : i32
  %kz = arith.maxsi %kz1, %zero : i32
  %rz = arith.muli %kz, %gny32 : i32
  %rzy = arith.addi %rz, %ky : i32
  %r = arith.muli %rzy, %gnx32 : i32
  %k = arith.addi %r, %kx : i32
  memref.store %k, %gkey[%item] : memref<?xi32, 1>
  %ki = arith.index_cast %k : i32 to index
{indent(atomic_add("ga_", "%gcount", "%ki", "%one", "%ga_old"), 2).rstrip()}
}} else {{
  memref.store %none, %gkey[%item] : memref<?xi32, 1>
  %big = arith.constant 1.0e30 : f32
  memref.store %big, %xp[%item, %i0] : memref<?x4xf32, 1>
  memref.store %big, %xp[%item, %i1] : memref<?x4xf32, 1>
  memref.store %big, %xp[%item, %i2] : memref<?x4xf32, 1>
}}""")))
    t.append(scan("gs_", "%gcount", "%gstart", "%gcursor", "%gcells"))
    t.append(launch("%grid_of_capacity", per_item("%capacity", f"""\
%zero = arith.constant 0 : i32
%one = arith.constant 1 : i32
%k = memref.load %gkey[%item] : memref<?xi32, 1>
%real = arith.cmpi sge, %k, %zero : i32
scf.if %real {{
  %ki = arith.index_cast %k : i32 to index
{indent(atomic_add("gc_", "%gcursor", "%ki", "%one", "%slot32"), 2).rstrip()}
  %slot = arith.index_cast %slot32 : i32 to index
  %p32 = arith.index_cast %item : index to i32
  memref.store %p32, %gplace[%slot] : memref<?xi32, 1>
}}""")))
    t.append(sort_bins("%grid_of_gcells", "%gstart", "%gplace", "%gcells"))
    t.append("""\
  //===--------------------------------------------------------------------===//
  // The boxes of the groups: a half-warp a group, relative to its first
  // particle in the minimum image
  //===--------------------------------------------------------------------===//

""")
    t.append(launch("%grid_of_boxes", f"""\
%base = arith.muli %bx, %block : index
%item = arith.addi %base, %tx : index
%c0w = arith.constant 0 : index
%c1w = arith.constant 1 : index
%c2w = arith.constant 2 : index
%c16w = arith.constant 16 : index
%zero = arith.constant 0 : i32
%places32 = memref.load %sizes_device[%c0w] : memref<3xi32, 1>
%places = arith.index_cast %places32 : i32 to index
%groups = arith.divui %places, %c16w : index
%g = arith.divui %item, %c16w : index
%u = arith.remui %item, %c16w : index
%inside = arith.cmpi ult, %g, %groups : index
%gs = arith.select %inside, %g, %c0w : index
%first = arith.muli %gs, %c16w : index
%p = arith.addi %first, %u : index
%pi = memref.load %order[%p] : memref<?xi32, 1>
%real0 = arith.cmpi sge, %pi, %zero : i32
%real = arith.andi %inside, %real0 : i1
%ox = memref.load %xp[%first, %c0w] : memref<?x4xf32, 1>
%oy = memref.load %xp[%first, %c1w] : memref<?x4xf32, 1>
%oz = memref.load %xp[%first, %c2w] : memref<?x4xf32, 1>
%vx = memref.load %xp[%p, %c0w] : memref<?x4xf32, 1>
%vy = memref.load %xp[%p, %c1w] : memref<?x4xf32, 1>
%vz = memref.load %xp[%p, %c2w] : memref<?x4xf32, 1>
%dx = arith.subf %vx, %ox : f32
%dy = arith.subf %vy, %oy : f32
%dz = arith.subf %vz, %oz : f32
%rx = func.call @mdrt_gpu_groups_image(%dx, %flx, %filx) : (f32, f32, f32) -> f32
%ry = func.call @mdrt_gpu_groups_image(%dy, %fly, %fily) : (f32, f32, f32) -> f32
%rz = func.call @mdrt_gpu_groups_image(%dz, %flz, %filz) : (f32, f32, f32) -> f32
%big = arith.constant 1.0e30 : f32
%small = arith.constant -1.0e30 : f32
%ax0 = arith.select %real, %rx, %big : f32
%ay0 = arith.select %real, %ry, %big : f32
%az0 = arith.select %real, %rz, %big : f32
%bx0 = arith.select %real, %rx, %small : f32
%by0 = arith.select %real, %ry, %small : f32
%bz0 = arith.select %real, %rz, %small : f32
{reduce_box()}\
%lead = arith.cmpi eq, %u, %c0w : index
%store = arith.andi %lead, %inside : i1
scf.if %store {{
  %lo_x = arith.addf %ox, %ax4 : f32
  %lo_y = arith.addf %oy, %ay4 : f32
  %lo_z = arith.addf %oz, %az4 : f32
  %hi_x = arith.addf %ox, %bx4 : f32
  %hi_y = arith.addf %oy, %by4 : f32
  %hi_z = arith.addf %oz, %bz4 : f32
  %c3w = arith.constant 3 : index
  %c4w = arith.constant 4 : index
  %c5w = arith.constant 5 : index
  memref.store %lo_x, %boxes[%g, %c0w] : memref<?x8xf32, 1>
  memref.store %lo_y, %boxes[%g, %c1w] : memref<?x8xf32, 1>
  memref.store %lo_z, %boxes[%g, %c2w] : memref<?x8xf32, 1>
  memref.store %hi_x, %boxes[%g, %c3w] : memref<?x8xf32, 1>
  memref.store %hi_y, %boxes[%g, %c4w] : memref<?x8xf32, 1>
  memref.store %hi_z, %boxes[%g, %c5w] : memref<?x8xf32, 1>
}}"""))
    t.append("""\
  //===--------------------------------------------------------------------===//
  // The lists: a warp a group, a lane a candidate
  //===--------------------------------------------------------------------===//

""")
    t.append(launch("%grid_of_lists", lists_body(),
                    workgroup=(f"%rel_wg : memref<64x4xf32, {WG}>, "
                               f"%partners : memref<1024xi32, {WG}>")))
    t.append("""\
  //===--------------------------------------------------------------------===//
  // The units of work: 64 entries at most
  //===--------------------------------------------------------------------===//

""")
    t.append(launch("%grid_of_groups", per_item("%group_capacity", """\
%i0 = arith.constant 0 : index
%zero = arith.constant 0 : i32
%sixty_three = arith.constant 63 : i32
%six = arith.constant 6 : i32
%c16 = arith.constant 16 : index
%places32 = memref.load %sizes_device[%i0] : memref<3xi32, 1>
%places = arith.index_cast %places32 : i32 to index
%groups = arith.divui %places, %c16 : index
%real = arith.cmpi ult, %item, %groups : index
%count = scf.if %real -> (i32) {
  %c = memref.load %counts[%item] : memref<?xi32, 1>
  scf.yield %c : i32
} else {
  scf.yield %zero : i32
}
%c63 = arith.addi %count, %sixty_three : i32
%u = arith.shrsi %c63, %six : i32
memref.store %u, %group_units[%item] : memref<?xi32, 1>""")))
    t.append(scan("us_", "%group_units", "%unit_start", "%unit_cursor", "%group_capacity"))
    t.append(launch("%grid_of_groups", per_item("%group_capacity", """\
%i1 = arith.constant 1 : index
%six = arith.constant 6 : i32
%u32 = memref.load %group_units[%item] : memref<?xi32, 1>
%s32 = memref.load %unit_start[%item] : memref<?xi32, 1>
%u = arith.index_cast %u32 : i32 to index
%s = arith.index_cast %s32 : i32 to index
%g32 = arith.index_cast %item : index to i32
%g64 = arith.shli %g32, %six : i32
%i0 = arith.constant 0 : index
scf.for %k = %i0 to %u step %i1 {
  %at = arith.addi %s, %k : index
  %fits = arith.cmpi ult, %at, %unit_capacity : index
  scf.if %fits {
    %k32 = arith.index_cast %k : index to i32
    %v = arith.addi %g64, %k32 : i32
    memref.store %v, %units[%at] : memref<?xi32, 1>
  }
}""")))
    t.append(launch("%c1", """\
%i2 = arith.constant 2 : index
%total = memref.load %unit_start[%group_capacity] : memref<?xi32, 1>
memref.store %total, %sizes_device[%i2] : memref<3xi32, 1>""", threads="%c1"))
    t.append("""\
  // The sizes, to the host.
  %copy_token0 = gpu.wait async
  %copy_token = gpu.memcpy async [%copy_token0] %sizes, %sizes_device : memref<3xi32>, memref<3xi32, 1>
  gpu.wait [%copy_token]

  %wrapped_plain = memref.memory_space_cast %wrapped : memref<?x3xf32, 1> to memref<?x3xf32>
  gpu.dealloc %wrapped_plain : memref<?x3xf32>
  %sizes_device_plain = memref.memory_space_cast %sizes_device : memref<3xi32, 1> to memref<3xi32>
  gpu.dealloc %sizes_device_plain : memref<3xi32>
  %xp_plain = memref.memory_space_cast %xp : memref<?x4xf32, 1> to memref<?x4xf32>
  gpu.dealloc %xp_plain : memref<?x4xf32>
  %gkey_plain = memref.memory_space_cast %gkey : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %gkey_plain : memref<?xi32>
  %gcount_plain = memref.memory_space_cast %gcount : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %gcount_plain : memref<?xi32>
  %gstart_plain = memref.memory_space_cast %gstart : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %gstart_plain : memref<?xi32>
  %gcursor_plain = memref.memory_space_cast %gcursor : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %gcursor_plain : memref<?xi32>
  %gplace_plain = memref.memory_space_cast %gplace : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %gplace_plain : memref<?xi32>
  %boxes_plain = memref.memory_space_cast %boxes : memref<?x8xf32, 1> to memref<?x8xf32>
  gpu.dealloc %boxes_plain : memref<?x8xf32>
  %group_units_plain = memref.memory_space_cast %group_units : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %group_units_plain : memref<?xi32>
  %unit_start_plain = memref.memory_space_cast %unit_start : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %unit_start_plain : memref<?xi32>
  %unit_cursor_plain = memref.memory_space_cast %unit_cursor : memref<?xi32, 1> to memref<?xi32>
  gpu.dealloc %unit_cursor_plain : memref<?xi32>
  return
}
""")
    return "".join(t)


def reduce_box():
    """The least and greatest relative coordinates of the 16 lanes of a
    half-warp, by shuffles."""
    out = []
    names = {"ax": "minimumf", "ay": "minimumf", "az": "minimumf",
             "bx": "maximumf", "by": "maximumf", "bz": "maximumf"}
    for level, offset in enumerate((8, 4, 2, 1)):
        for v, op in names.items():
            out.append(f"%{v}_s{level} = arith.constant {offset} : i32")
            out.append(f"%{v}_w{level} = arith.constant 32 : i32")
            out.append(f"%{v}_o{level}, %{v}_ok{level} = gpu.shuffle xor %{v}{level}, %{v}_s{level}, %{v}_w{level} : f32")
            out.append(f"%{v}{level + 1} = arith.{op} %{v}{level}, %{v}_o{level} : f32")
    return "\n".join(out) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "lib", "Runtime", "Templates",
                        "NeighborsGroupsGPU.mlir")
    text = HEADER + HELPERS + build()
    # Launch sizes that the body names.
    text = text.replace(
        "  gpu.launch blocks(%bx, %by, %bz) in (%gx = %grid_of_boxes,",
        "  %box_threads = arith.muli %group_capacity, %c16b : index\n"
        "  %grid_of_boxes = func.call @mdrt_gpu_groups_grid(%box_threads, %block) : (index, index) -> index\n"
        "  gpu.launch blocks(%bx, %by, %bz) in (%gx = %grid_of_boxes,", 1)
    text = text.replace(
        "  gpu.launch blocks(%bx, %by, %bz) in (%gx = %grid_of_lists,",
        "  %c32b = arith.constant 32 : index\n"
        "  %list_threads = arith.muli %group_capacity, %c32b : index\n"
        "  %grid_of_lists = func.call @mdrt_gpu_groups_grid(%list_threads, %block) : (index, index) -> index\n"
        "  gpu.launch blocks(%bx, %by, %bz) in (%gx = %grid_of_lists,", 1)
    text = text.replace("  %c32l = arith.constant 32 : index\n",
                        "  %c32l = arith.constant 32 : index\n  %c16b = arith.constant 16 : index\n", 1)
    with open(path, "w") as file:
        file.write(text)


if __name__ == "__main__":
    main()
