#!/usr/bin/env python3
"""Writes lib/Runtime/Templates/PMEGPU.mlir, the template of the reciprocal
sum of particle mesh Ewald on a device.

    python3 scripts/generate-pme-gpu-template.py

The kernels compute what those of the template for the host compute
(lib/Runtime/Templates/PME.mlir), point by point and particle by particle.
A kernel cannot call a function, so the B-splines are written out in each
kernel that needs them; this script writes them. Edit the script, not the
template."""

import os

HEADER = """\
// The reciprocal sum of smooth particle mesh Ewald on a device
// [Essmann1995] (docs/pme-m1.md). The keys are those of
// docs/references.md.
//
// Generated by scripts/generate-pme-gpu-template.py. Do not edit.
//
// This is a template. The compiler adds it to a module that has a
// reciprocal sum on a device, where it is specialized like any other code;
// the types and the conversions are those of the template for the host
// (PME.mlir), and so are the grid and the B-splines. The buffers are on the
// device.
//
// A kernel runs one thread per item, in blocks of 128 threads. The threads
// beyond the last item do nothing. The charges are added to the grid in
// fixed point with integer atomics, so that the sum does not depend on the
// order of the threads (D70). The product with the influence function sums
// the energy and the virial of each row of the grid in a thread; the host
// adds the rows up in their order.

!pme_pos = f64
!pme_chg = f64
!pme_frc = f64

func.func private @mdrt_gpu_pme_blocks(%count: index) -> index {
  %c127 = arith.constant 127 : index
  %c128 = arith.constant 128 : index
  %padded = arith.addi %count, %c127 : index
  %result = arith.divui %padded, %c128 : index
  return %result : index
}
"""


class Body:
    """Lines of a kernel, with names of their own."""

    def __init__(self, indent):
        self.indent = indent
        self.lines = []

    def __call__(self, text):
        for line in text.splitlines():
            self.lines.append(self.indent + line if line else "")

    def text(self):
        return "\n".join(self.lines) + "\n"


def bspline(body, p, w, n, values, slopes):
    """The weights and, if `slopes`, their derivatives of the B-spline of
    order `n` at the fraction `w`, into the arrays `values` and `slopes`
    (the recursion of Essmann et al., as @mdrt.pme_bspline does)."""

    def raise_order(k, tag):
        q = p + tag
        body(f"""\
%{q}km1 = arith.subi {k}, %{p}c1 : index
%{q}km2 = arith.subi {k}, %{p}c2 : index
%{q}km1i = arith.index_cast %{q}km1 : index to i64
%{q}km1f = arith.sitofp %{q}km1i : i64 to f64
%{q}div = arith.divf %{p}one, %{q}km1f : f64
%{q}ki = arith.index_cast {k} : index to i64
%{q}kf = arith.sitofp %{q}ki : i64 to f64
%{q}last = memref.load {values}[%{q}km2] : memref<8xf64>
%{q}dw = arith.mulf %{q}div, {w} : f64
%{q}top = arith.mulf %{q}dw, %{q}last : f64
memref.store %{q}top, {values}[%{q}km1] : memref<8xf64>
scf.for %{q}j = %{p}c1 to %{q}km1 step %{p}c1 {{
  %{q}ji = arith.index_cast %{q}j : index to i64
  %{q}jf = arith.sitofp %{q}ji : i64 to f64
  %{q}at = arith.subi %{q}km1, %{q}j : index
  %{q}below = arith.subi %{q}at, %{p}c1 : index
  %{q}lo = memref.load {values}[%{q}below] : memref<8xf64>
  %{q}hi = memref.load {values}[%{q}at] : memref<8xf64>
  %{q}wj = arith.addf {w}, %{q}jf : f64
  %{q}kj = arith.subf %{q}kf, %{q}jf : f64
  %{q}kjw = arith.subf %{q}kj, {w} : f64
  %{q}t1 = arith.mulf %{q}wj, %{q}lo : f64
  %{q}t2 = arith.mulf %{q}kjw, %{q}hi : f64
  %{q}sum = arith.addf %{q}t1, %{q}t2 : f64
  %{q}value = arith.mulf %{q}div, %{q}sum : f64
  memref.store %{q}value, {values}[%{q}at] : memref<8xf64>
}}
%{q}first = memref.load {values}[%{p}c0] : memref<8xf64>
%{q}omw = arith.subf %{p}one, {w} : f64
%{q}d0 = arith.mulf %{q}div, %{q}omw : f64
%{q}bottom = arith.mulf %{q}d0, %{q}first : f64
memref.store %{q}bottom, {values}[%{p}c0] : memref<8xf64>""")

    body(f"""\
%{p}c0 = arith.constant 0 : index
%{p}c1 = arith.constant 1 : index
%{p}c2 = arith.constant 2 : index
%{p}c3 = arith.constant 3 : index
%{p}c8 = arith.constant 8 : index
%{p}zero = arith.constant 0.0 : f64
%{p}one = arith.constant 1.0 : f64
scf.for %{p}j = %{p}c0 to %{p}c8 step %{p}c1 {{
  memref.store %{p}zero, {values}[%{p}j] : memref<8xf64>
}}
%{p}omw = arith.subf %{p}one, {w} : f64
memref.store %{p}omw, {values}[%{p}c0] : memref<8xf64>
memref.store {w}, {values}[%{p}c1] : memref<8xf64>
scf.for %{p}k = %{p}c3 to {n} step %{p}c1 {{""")
    raise_order(f"%{p}k", "r_")
    body("}")
    if slopes:
        body(f"""\
%{p}v0 = memref.load {values}[%{p}c0] : memref<8xf64>
%{p}s0 = arith.negf %{p}v0 : f64
memref.store %{p}s0, {slopes}[%{p}c0] : memref<8xf64>
scf.for %{p}js = %{p}c1 to {n} step %{p}c1 {{
  %{p}jm1 = arith.subi %{p}js, %{p}c1 : index
  %{p}before = memref.load {values}[%{p}jm1] : memref<8xf64>
  %{p}here = memref.load {values}[%{p}js] : memref<8xf64>
  %{p}slope = arith.subf %{p}before, %{p}here : f64
  memref.store %{p}slope, {slopes}[%{p}js] : memref<8xf64>
}}""")
    raise_order(n, "f_")


def place(body, p, x, length, k, n):
    """The first point and the fraction of a particle at `x` along an edge,
    as @mdrt.pme_place gives them."""
    body(f"""\
%{p}s = arith.divf {x}, {length} : f64
%{p}fs = math.floor %{p}s : f64
%{p}frac = arith.subf %{p}s, %{p}fs : f64
%{p}ki = arith.index_cast {k} : index to i64
%{p}kf = arith.sitofp %{p}ki : i64 to f64
%{p}u = arith.mulf %{p}frac, %{p}kf : f64
%{p}fu = math.floor %{p}u : f64
%{p}w = arith.subf %{p}u, %{p}fu : f64
%{p}bi = arith.fptosi %{p}fu : f64 to i64
%{p}b = arith.index_cast %{p}bi : i64 to index
%{p}bk = arith.addi %{p}b, {k} : index
%{p}bkn = arith.subi %{p}bk, {n} : index
%{p}c1p = arith.constant 1 : index
%{p}start = arith.addi %{p}bkn, %{p}c1p : index""")
    return f"%{p}start", f"%{p}w"


def particle_prologue(body, slopes):
    """The splines of particle %i along the three edges."""
    body("""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
%wx = memref.alloca() : memref<8xf64>
%wy = memref.alloca() : memref<8xf64>
%wz = memref.alloca() : memref<8xf64>""")
    if slopes:
        body("""\
%dx = memref.alloca() : memref<8xf64>
%dy = memref.alloca() : memref<8xf64>
%dz = memref.alloca() : memref<8xf64>""")
    body("""\
%xs = memref.load %x[%i, %i0] : memref<?x3x!pme_pos, 1>
%ys = memref.load %x[%i, %i1] : memref<?x3x!pme_pos, 1>
%zs = memref.load %x[%i, %i2] : memref<?x3x!pme_pos, 1>
%qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
%xi = PME_EXTEND_POS %xs : !pme_pos to f64
%yi = PME_EXTEND_POS %ys : !pme_pos to f64
%zi = PME_EXTEND_POS %zs : !pme_pos to f64
%qi = PME_EXTEND_CHG %qs : !pme_chg to f64""")
    starts = []
    for axis, (coordinate, length, k, w, d) in enumerate(
        (("%xi", "%lx", "%k1", "%wx", "%dx"), ("%yi", "%ly", "%k2", "%wy", "%dy"),
         ("%zi", "%lz", "%k3", "%wz", "%dz"))):
        tag = "xyz"[axis]
        start, fraction = place(body, f"p{tag}_", coordinate, length, k, "%n")
        bspline(body, f"b{tag}_", fraction, "%n", w, d if slopes else None)
        starts.append(start)
    return starts


def launch(body_text, count):
    return f"""\
  %blocks_{count[1:]} = func.call @mdrt_gpu_pme_blocks({count}) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_{count[1:]}, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, {count} : index
    scf.if %inside {{
{body_text}    }}
    gpu.terminator
  }}
"""


def spread():
    body = Body("      ")
    body("%i = arith.addi %item, %c0 : index")
    sx, sy, sz = particle_prologue(body, slopes=False)
    body(f"""\
%scale = arith.constant 1099511627776.0 : f64
%qscaled = arith.mulf %qi, %scale : f64
%eight = arith.constant 8 : i64
%gridindex = memref.extract_aligned_pointer_as_index %grid : memref<?xi64, 1> -> index
// The grid is a buffer of its own, with no offset.
%gridbase = arith.index_cast %gridindex : index to i64
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
scf.for %j1 = %j0 to %n step %j1c {{
  %g1s = arith.addi {sx}, %j1 : index
  %g1 = arith.remui %g1s, %k1 : index
  %w1 = memref.load %wx[%j1] : memref<8xf64>
  %q1 = arith.mulf %qscaled, %w1 : f64
  scf.for %j2 = %j0 to %n step %j1c {{
    %g2s = arith.addi {sy}, %j2 : index
    %g2 = arith.remui %g2s, %k2 : index
    %w2 = memref.load %wy[%j2] : memref<8xf64>
    %q12 = arith.mulf %q1, %w2 : f64
    %row1 = arith.muli %g1, %k2 : index
    %row = arith.addi %row1, %g2 : index
    %gbase = arith.muli %row, %k3 : index
    scf.for %j3 = %j0 to %n step %j1c {{
      %g3s = arith.addi {sz}, %j3 : index
      %g3 = arith.remui %g3s, %k3 : index
      %w3 = memref.load %wz[%j3] : memref<8xf64>
      %value = arith.mulf %q12, %w3 : f64
      %rounded = math.roundeven %value : f64
      %fixed = arith.fptosi %rounded : f64 to i64
      %at = arith.addi %gbase, %g3 : index
      // A relaxed atomic at the scope of the device: the sum needs no
      // order, and one of the system would wait for the host.
      %ati = arith.index_cast %at : index to i64
      %offset = arith.muli %ati, %eight : i64
      %address = arith.addi %gridbase, %offset : i64
      %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
      %old = llvm.atomicrmw add %pointer, %fixed syncscope("device") monotonic : !llvm.ptr<1>, i64
    }}
  }}
}}""")
    zero = Body("      ")
    zero("""\
%none = arith.constant 0 : i64
memref.store %none, %grid[%item] : memref<?xi64, 1>""")
    return f"""
// Spreads the charges to `grid`, in fixed point.
func.func private @mdrt_gpu_pme_spread(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %box: vector<3xf64>, %grid: memref<?xi64, 1>,
                                       %k1: index, %k2: index, %k3: index, %n: index) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %points = memref.dim %grid, %c0 : memref<?xi64, 1>
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
{launch(zero.text(), "%points")}{launch(body.text(), "%count")}  return
}}
"""


def real():
    body = Body("      ")
    body("""\
%inverse = arith.constant 9.094947017729282e-13 : f64
%fixed = memref.load %grid[%item] : memref<?xi64, 1>
%value = arith.sitofp %fixed : i64 to f64
%scaled = arith.mulf %value, %inverse : f64
memref.store %scaled, %real[%item] : memref<?xf64, 1>""")
    return f"""
// The grid in f64, from fixed point.
func.func private @mdrt_gpu_pme_real(%grid: memref<?xi64, 1>, %real: memref<?xf64, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %points = memref.dim %grid, %c0 : memref<?xi64, 1>
{launch(body.text(), "%points")}  return
}}
"""


def wave(body, p, k, count, length):
    body(f"""\
%{p}half = arith.divui {count}, %cc2 : index
%{p}ki = arith.index_cast {k} : index to i64
%{p}ni = arith.index_cast {count} : index to i64
%{p}beyond = arith.cmpi ugt, {k}, %{p}half : index
%{p}shifted = arith.subi %{p}ki, %{p}ni : i64
%{p}signed = arith.select %{p}beyond, %{p}shifted, %{p}ki : i64
%{p}sf = arith.sitofp %{p}signed : i64 to f64
%{p}m = arith.divf %{p}sf, {length} : f64""")
    return f"%{p}m"


def convolve():
    body = Body("      ")
    body("""\
%cc0 = arith.constant 0 : index
%cc1 = arith.constant 1 : index
%cc2 = arith.constant 2 : index
%kzero = arith.constant 0.0 : f64
%khalf = arith.constant 0.5 : f64
%kone = arith.constant 1.0 : f64
%ktwo = arith.constant 2.0 : f64
%a = arith.divui %item, %k2 : index
%b = arith.remui %item, %k2 : index""")
    m1 = wave(body, "w1_", "%a", "%k1", "%lx")
    m2 = wave(body, "w2_", "%b", "%k2", "%ly")
    body(f"""\
%h = arith.divui %k3, %cc2 : index
%h1 = arith.addi %h, %cc1 : index
%odd = arith.remui %k3, %cc2 : index
%even = arith.cmpi eq, %odd, %cc0 : index
%m1s = arith.mulf {m1}, {m1} : f64
%m2s = arith.mulf {m2}, {m2} : f64
%m12 = arith.addf %m1s, %m2s : f64
%mod1 = memref.load %moduli[%cc0, %a] : memref<?x?xf64, 1>
%mod2 = memref.load %moduli[%cc1, %b] : memref<?x?xf64, 1>
%mod12 = arith.mulf %mod1, %mod2 : f64
%ke, %kw00, %kw01, %kw02, %kw11, %kw12, %kw22 = scf.for %z = %cc0 to %h1 step %cc1
    iter_args(%e0 = %kzero, %a00 = %kzero, %a01 = %kzero, %a02 = %kzero,
              %a11 = %kzero, %a12 = %kzero, %a22 = %kzero)
    -> (f64, f64, f64, f64, f64, f64, f64) {{
  %zi = arith.index_cast %z : index to i64
  %zf = arith.sitofp %zi : i64 to f64
  %m3 = arith.divf %zf, %lz : f64
  %mod3 = memref.load %moduli[%cc2, %z] : memref<?x?xf64, 1>
  %m3s = arith.mulf %m3, %m3 : f64
  %msq = arith.addf %m12, %m3s : f64
  %origin = arith.cmpf oeq, %msq, %kzero : f64
  %safe = arith.select %origin, %kone, %msq : f64
  %inverse = arith.divf %kone, %safe : f64
  %gm = arith.mulf %gauss, %msq : f64
  %ngm = arith.negf %gm : f64
  %ex = math.exp %ngm : f64
  %exm = arith.mulf %ex, %inverse : f64
  %pexm = arith.mulf %prefactor, %exm : f64
  %mods = arith.mulf %mod12, %mod3 : f64
  %bc0 = arith.mulf %pexm, %mods : f64
  %bc = arith.select %origin, %kzero, %bc0 : f64
  %base1 = arith.muli %item, %h1 : index
  %base2 = arith.addi %base1, %z : index
  %re_at = arith.muli %base2, %cc2 : index
  %im_at = arith.addi %re_at, %cc1 : index
  %re = memref.load %c[%re_at] : memref<?xf64, 1>
  %im = memref.load %c[%im_at] : memref<?xf64, 1>
  %re2 = arith.mulf %re, %re : f64
  %im2 = arith.mulf %im, %im : f64
  %g2 = arith.addf %re2, %im2 : f64
  %first = arith.cmpi eq, %z, %cc0 : index
  %middle = arith.cmpi eq, %z, %h : index
  %middle_even = arith.andi %middle, %even : i1
  %single = arith.ori %first, %middle_even : i1
  %weight = arith.select %single, %kone, %ktwo : f64
  %hw = arith.mulf %khalf, %weight : f64
  %hwb = arith.mulf %hw, %bc : f64
  %em = arith.mulf %hwb, %g2 : f64
  %sum = arith.addf %inverse, %gauss : f64
  %factor0 = arith.mulf %ktwo, %sum : f64
  %factor = arith.select %origin, %kzero, %factor0 : f64
  %ef = arith.mulf %em, %factor : f64
  %p11 = arith.mulf {m1}, {m1} : f64
  %p12 = arith.mulf {m1}, {m2} : f64
  %p13 = arith.mulf {m1}, %m3 : f64
  %p22 = arith.mulf {m2}, {m2} : f64
  %p23 = arith.mulf {m2}, %m3 : f64
  %p33 = arith.mulf %m3, %m3 : f64
  %t11 = arith.mulf %ef, %p11 : f64
  %t12 = arith.mulf %ef, %p12 : f64
  %t13 = arith.mulf %ef, %p13 : f64
  %t22 = arith.mulf %ef, %p22 : f64
  %t23 = arith.mulf %ef, %p23 : f64
  %t33 = arith.mulf %ef, %p33 : f64
  %d11 = arith.subf %em, %t11 : f64
  %d22 = arith.subf %em, %t22 : f64
  %d33 = arith.subf %em, %t33 : f64
  %n00 = arith.addf %a00, %d11 : f64
  %n01 = arith.subf %a01, %t12 : f64
  %n02 = arith.subf %a02, %t13 : f64
  %n11 = arith.addf %a11, %d22 : f64
  %n12 = arith.subf %a12, %t23 : f64
  %n22 = arith.addf %a22, %d33 : f64
  %ne = arith.addf %e0, %em : f64
  %reb = arith.mulf %re, %bc : f64
  %imb = arith.mulf %im, %bc : f64
  memref.store %reb, %c[%re_at] : memref<?xf64, 1>
  memref.store %imb, %c[%im_at] : memref<?xf64, 1>
  scf.yield %ne, %n00, %n01, %n02, %n11, %n12, %n22
      : f64, f64, f64, f64, f64, f64, f64
}}
%out = arith.muli %item, %c10 : index""")
    for index, name in enumerate(
            ["%ke", "%kw00", "%kw01", "%kw02", "%kw11", "%kw12", "%kw22"]):
        body(f"%oc{index} = arith.constant {index} : index")
        body(f"%o{index} = arith.addi %out, %oc{index} : index")
        body(f"memref.store {name}, %rows[%o{index}] : memref<?xf64, 1>")
    return f"""
// Multiplies the half-complex transform `c` by the influence function, which
// it computes from the factors of the edges in `moduli` and the cell, and
// returns the energy and the virial, as @mdrt.pme_convolve does. A thread
// takes a row of the grid, (k1, k2), and writes its sums to `rows`: the
// energy, then the virial xx, xy, xz, yy, yz, zz.
func.func private @mdrt_gpu_pme_convolve(%c: memref<?xf64, 1>, %moduli: memref<?x?xf64, 1>,
                                         %rows: memref<?xf64, 1>, %box: vector<3xf64>,
                                         %beta: f64, %coulomb: f64,
                                         %k1: index, %k2: index, %k3: index)
    -> (f64, vector<9xf64>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c10 = arith.constant 10 : index
  %c128 = arith.constant 128 : index
  %zero = arith.constant 0.0 : f64
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
  %prefactor = arith.divf %coulomb, %piv : f64
  %count = arith.muli %k1, %k2 : index
{launch(body.text(), "%count")}
  // The rows, added up in their order on the host.
  %length = arith.muli %count, %c10 : index
  %host = memref.alloc(%length) : memref<?xf64>
  %t0 = gpu.wait async
  %t1 = gpu.memcpy async [%t0] %host, %rows : memref<?xf64>, memref<?xf64, 1>
  gpu.wait [%t1]
  %e, %w00, %w01, %w02, %w11, %w12, %w22 = scf.for %r = %c0 to %count step %c1
      iter_args(%s0 = %zero, %s1 = %zero, %s2 = %zero, %s3 = %zero,
                %s4 = %zero, %s5 = %zero, %s6 = %zero)
      -> (f64, f64, f64, f64, f64, f64, f64) {{
    %at = arith.muli %r, %c10 : index
    %c2h = arith.constant 2 : index
    %c3h = arith.constant 3 : index
    %c4h = arith.constant 4 : index
    %c5h = arith.constant 5 : index
    %c6h = arith.constant 6 : index
    %a1 = arith.addi %at, %c1 : index
    %a2 = arith.addi %at, %c2h : index
    %a3 = arith.addi %at, %c3h : index
    %a4 = arith.addi %at, %c4h : index
    %a5 = arith.addi %at, %c5h : index
    %a6 = arith.addi %at, %c6h : index
    %v0 = memref.load %host[%at] : memref<?xf64>
    %v1 = memref.load %host[%a1] : memref<?xf64>
    %v2 = memref.load %host[%a2] : memref<?xf64>
    %v3 = memref.load %host[%a3] : memref<?xf64>
    %v4 = memref.load %host[%a4] : memref<?xf64>
    %v5 = memref.load %host[%a5] : memref<?xf64>
    %v6 = memref.load %host[%a6] : memref<?xf64>
    %n0 = arith.addf %s0, %v0 : f64
    %n1 = arith.addf %s1, %v1 : f64
    %n2 = arith.addf %s2, %v2 : f64
    %n3 = arith.addf %s3, %v3 : f64
    %n4 = arith.addf %s4, %v4 : f64
    %n5 = arith.addf %s5, %v5 : f64
    %n6 = arith.addf %s6, %v6 : f64
    scf.yield %n0, %n1, %n2, %n3, %n4, %n5, %n6 : f64, f64, f64, f64, f64, f64, f64
  }}
  memref.dealloc %host : memref<?xf64>
  %virial = vector.from_elements %w00, %w01, %w02, %w01, %w11, %w12, %w02, %w12, %w22 : vector<9xf64>
  return %e, %virial : f64, vector<9xf64>
}}
"""


def scale():
    body = Body("      ")
    body("""\
%cc0 = arith.constant 0 : index
%cc1 = arith.constant 1 : index
%cc2 = arith.constant 2 : index
%kzero = arith.constant 0.0 : f64
%kone = arith.constant 1.0 : f64
%h = arith.divui %k3, %cc2 : index
%h1 = arith.addi %h, %cc1 : index
%row = arith.divui %item, %h1 : index
%z = arith.remui %item, %h1 : index
%a = arith.divui %row, %k2 : index
%b = arith.remui %row, %k2 : index""")
    m1 = wave(body, "w1_", "%a", "%k1", "%lx")
    m2 = wave(body, "w2_", "%b", "%k2", "%ly")
    body(f"""\
%m1s = arith.mulf {m1}, {m1} : f64
%m2s = arith.mulf {m2}, {m2} : f64
%m12 = arith.addf %m1s, %m2s : f64
%mod1 = memref.load %moduli[%cc0, %a] : memref<?x?xf64, 1>
%mod2 = memref.load %moduli[%cc1, %b] : memref<?x?xf64, 1>
%mod12 = arith.mulf %mod1, %mod2 : f64
%zi = arith.index_cast %z : index to i64
%zf = arith.sitofp %zi : i64 to f64
%m3 = arith.divf %zf, %lz : f64
%mod3 = memref.load %moduli[%cc2, %z] : memref<?x?xf64, 1>
%m3s = arith.mulf %m3, %m3 : f64
%msq = arith.addf %m12, %m3s : f64
%origin = arith.cmpf oeq, %msq, %kzero : f64
%safe = arith.select %origin, %kone, %msq : f64
%inverse = arith.divf %kone, %safe : f64
%gm = arith.mulf %gauss, %msq : f64
%ngm = arith.negf %gm : f64
%ex = math.exp %ngm : f64
%exm = arith.mulf %ex, %inverse : f64
%pexm = arith.mulf %prefactor, %exm : f64
%mods = arith.mulf %mod12, %mod3 : f64
%bc0 = arith.mulf %pexm, %mods : f64
%bc = arith.select %origin, %kzero, %bc0 : f64
%re_at = arith.muli %item, %cc2 : index
%im_at = arith.addi %re_at, %cc1 : index
%re = memref.load %c[%re_at] : memref<?xf64, 1>
%im = memref.load %c[%im_at] : memref<?xf64, 1>
%reb = arith.mulf %re, %bc : f64
%imb = arith.mulf %im, %bc : f64
memref.store %reb, %c[%re_at] : memref<?xf64, 1>
memref.store %imb, %c[%im_at] : memref<?xf64, 1>""")
    return f"""
// Multiplies the half-complex transform `c` by the influence function, as
// @mdrt_gpu_pme_convolve does, where neither the energy nor the virial is
// needed: a thread for each point, and nothing for the host to wait for.
func.func private @mdrt_gpu_pme_scale(%c: memref<?xf64, 1>, %moduli: memref<?x?xf64, 1>,
                                      %box: vector<3xf64>, %beta: f64, %coulomb: f64,
                                      %k1: index, %k2: index, %k3: index) {{
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  %c128 = arith.constant 128 : index
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
  %prefactor = arith.divf %coulomb, %piv : f64
  %rows = arith.muli %k1, %k2 : index
  %half = arith.divui %k3, %c2 : index
  %depth = arith.addi %half, %c1 : index
  %points = arith.muli %rows, %depth : index
{launch(body.text(), "%points")}  return
}}
"""


def gather():
    body = Body("      ")
    body("%i = arith.addi %item, %c0 : index")
    sx, sy, sz = particle_prologue(body, slopes=True)
    body(f"""\
%gzero = arith.constant 0.0 : f64
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
%sumx, %sumy, %sumz = scf.for %j1 = %j0 to %n step %j1c
    iter_args(%ax = %gzero, %ay = %gzero, %az = %gzero) -> (f64, f64, f64) {{
  %g1s = arith.addi {sx}, %j1 : index
  %g1 = arith.remui %g1s, %k1 : index
  %w1 = memref.load %wx[%j1] : memref<8xf64>
  %d1 = memref.load %dx[%j1] : memref<8xf64>
  %bx2, %by2, %bz2 = scf.for %j2 = %j0 to %n step %j1c
      iter_args(%cx = %ax, %cy = %ay, %cz = %az) -> (f64, f64, f64) {{
    %g2s = arith.addi {sy}, %j2 : index
    %g2 = arith.remui %g2s, %k2 : index
    %w2 = memref.load %wy[%j2] : memref<8xf64>
    %d2 = memref.load %dy[%j2] : memref<8xf64>
    %row1 = arith.muli %g1, %k2 : index
    %row = arith.addi %row1, %g2 : index
    %gbase = arith.muli %row, %k3 : index
    %d1w2 = arith.mulf %d1, %w2 : f64
    %w1d2 = arith.mulf %w1, %d2 : f64
    %w1w2 = arith.mulf %w1, %w2 : f64
    %ex, %ey, %ez = scf.for %j3 = %j0 to %n step %j1c
        iter_args(%tx3 = %cx, %ty3 = %cy, %tz3 = %cz) -> (f64, f64, f64) {{
      %g3s = arith.addi {sz}, %j3 : index
      %g3 = arith.remui %g3s, %k3 : index
      %w3 = memref.load %wz[%j3] : memref<8xf64>
      %d3 = memref.load %dz[%j3] : memref<8xf64>
      %at = arith.addi %gbase, %g3 : index
      %p = memref.load %phi[%at] : memref<?xf64, 1>
      %px = arith.mulf %d1w2, %w3 : f64
      %py = arith.mulf %w1d2, %w3 : f64
      %pz = arith.mulf %w1w2, %d3 : f64
      %vx = arith.mulf %p, %px : f64
      %vy = arith.mulf %p, %py : f64
      %vz = arith.mulf %p, %pz : f64
      %nx = arith.addf %tx3, %vx : f64
      %ny = arith.addf %ty3, %vy : f64
      %nz = arith.addf %tz3, %vz : f64
      scf.yield %nx, %ny, %nz : f64, f64, f64
    }}
    scf.yield %ex, %ey, %ez : f64, f64, f64
  }}
  scf.yield %bx2, %by2, %bz2 : f64, f64, f64
}}
%mq = arith.negf %qi : f64
%sxq = arith.mulf %mq, %rx : f64
%syq = arith.mulf %mq, %ry : f64
%szq = arith.mulf %mq, %rz : f64
%fx64 = arith.mulf %sxq, %sumx : f64
%fy64 = arith.mulf %syq, %sumy : f64
%fz64 = arith.mulf %szq, %sumz : f64
%fxs = PME_NARROW_FRC %fx64 : f64 to !pme_frc
%fys = PME_NARROW_FRC %fy64 : f64 to !pme_frc
%fzs = PME_NARROW_FRC %fz64 : f64 to !pme_frc
memref.store %fxs, %f[%i, %i0] : memref<?x3x!pme_frc, 1>
memref.store %fys, %f[%i, %i1] : memref<?x3x!pme_frc, 1>
memref.store %fzs, %f[%i, %i2] : memref<?x3x!pme_frc, 1>""")
    return f"""
// The forces, as @mdrt.pme_gather gives them: a thread for each particle.
func.func private @mdrt_gpu_pme_gather(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %phi: memref<?xf64, 1>, %box: vector<3xf64>,
                                       %k1: index, %k2: index, %k3: index, %n: index,
                                       %f: memref<?x3x!pme_frc, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %k1i = arith.index_cast %k1 : index to i64
  %k2i = arith.index_cast %k2 : index to i64
  %k3i = arith.index_cast %k3 : index to i64
  %k1f = arith.sitofp %k1i : i64 to f64
  %k2f = arith.sitofp %k2i : i64 to f64
  %k3f = arith.sitofp %k3i : i64 to f64
  %rx = arith.divf %k1f, %lx : f64
  %ry = arith.divf %k2f, %ly : f64
  %rz = arith.divf %k3f, %lz : f64
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
{launch(body.text(), "%count")}  return
}}
"""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "lib", "Runtime", "Templates", "PMEGPU.mlir")
    with open(path, "w") as file:
        file.write(HEADER + spread() + real() + convolve() + scale() +
                   gather())


if __name__ == "__main__":
    main()
