#!/usr/bin/env python3
"""Writes lib/Runtime/Templates/PMEGPU.mlir, the template of the reciprocal
sum of particle mesh Ewald on a device.

    python3 scripts/generate-pme-gpu-template.py

The kernels compute what those of the template for the host compute
(lib/Runtime/Templates/PME.mlir), point by point and particle by particle.
A kernel cannot call a function, so the B-splines are written out in each
kernel that needs them; this script writes them. Edit the script, not the
template."""

import os

HEADER = """\
// The reciprocal sum of smooth particle mesh Ewald on a device
// [Essmann1995] (docs/pme-m1.md). The keys are those of
// docs/references.md.
//
// Generated by scripts/generate-pme-gpu-template.py. Do not edit.
//
// This is a template. The compiler adds it to a module that has a
// reciprocal sum on a device, where it is specialized like any other code;
// the types of the positions, the charges, and the forces and their
// conversions are those of the template for the host (PME.mlir); the
// splines, the grid, and its transform are in !pme_real, which is the type
// of the forces, while the fractions of the positions and the edges of the
// cell are in f64. The buffers are on the device.
//
// A kernel runs one thread per item, in blocks of 128 threads. The threads
// beyond the last item do nothing. In the deterministic mode the charges
// are added to the grid in fixed point with integer atomics, so that the
// sum does not depend on the order of the threads (D70); by default they
// are added in !pme_real with floating-point atomics (D84). The product
// with the influence function sums
// the energy and the virial of each row of the grid in a thread; the host
// adds the rows up in their order.

!pme_pos = f64
!pme_chg = f64
!pme_frc = f64
// The type in which the splines, the grid, and its transform are computed:
// that of the forces on a device, so f32 in the mixed and single modes.
!pme_real = f64

func.func private @mdrt_gpu_pme_blocks(%count: index) -> index {
  %c127 = arith.constant 127 : index
  %c128 = arith.constant 128 : index
  %padded = arith.addi %count, %c127 : index
  %result = arith.divui %padded, %c128 : index
  return %result : index
}
"""


class Body:
    """Lines of a kernel, with names of their own."""

    def __init__(self, indent):
        self.indent = indent
        self.lines = []

    def __call__(self, text):
        for line in text.splitlines():
            self.lines.append(self.indent + line if line else "")

    def text(self):
        return "\n".join(self.lines) + "\n"


def bspline(body, p, w, n, values, slopes):
    """The weights and, if `slopes`, their derivatives of the B-spline of
    order `n` at the fraction `w`, into the arrays `values` and `slopes`
    (the recursion of Essmann et al., as @mdrt.pme_bspline does)."""

    def raise_order(k, tag):
        q = p + tag
        body(f"""\
%{q}km1 = arith.subi {k}, %{p}c1 : index
%{q}km2 = arith.subi {k}, %{p}c2 : index
%{q}km1i = arith.index_cast %{q}km1 : index to i64
%{q}km1f = arith.sitofp %{q}km1i : i64 to !pme_real
%{q}div = arith.divf %{p}one, %{q}km1f : !pme_real
%{q}ki = arith.index_cast {k} : index to i64
%{q}kf = arith.sitofp %{q}ki : i64 to !pme_real
%{q}last = memref.load {values}[%{q}km2] : memref<8x!pme_real>
%{q}dw = arith.mulf %{q}div, {w} : !pme_real
%{q}top = arith.mulf %{q}dw, %{q}last : !pme_real
memref.store %{q}top, {values}[%{q}km1] : memref<8x!pme_real>
scf.for %{q}j = %{p}c1 to %{q}km1 step %{p}c1 {{
  %{q}ji = arith.index_cast %{q}j : index to i64
  %{q}jf = arith.sitofp %{q}ji : i64 to !pme_real
  %{q}at = arith.subi %{q}km1, %{q}j : index
  %{q}below = arith.subi %{q}at, %{p}c1 : index
  %{q}lo = memref.load {values}[%{q}below] : memref<8x!pme_real>
  %{q}hi = memref.load {values}[%{q}at] : memref<8x!pme_real>
  %{q}wj = arith.addf {w}, %{q}jf : !pme_real
  %{q}kj = arith.subf %{q}kf, %{q}jf : !pme_real
  %{q}kjw = arith.subf %{q}kj, {w} : !pme_real
  %{q}t1 = arith.mulf %{q}wj, %{q}lo : !pme_real
  %{q}t2 = arith.mulf %{q}kjw, %{q}hi : !pme_real
  %{q}sum = arith.addf %{q}t1, %{q}t2 : !pme_real
  %{q}value = arith.mulf %{q}div, %{q}sum : !pme_real
  memref.store %{q}value, {values}[%{q}at] : memref<8x!pme_real>
}}
%{q}first = memref.load {values}[%{p}c0] : memref<8x!pme_real>
%{q}omw = arith.subf %{p}one, {w} : !pme_real
%{q}d0 = arith.mulf %{q}div, %{q}omw : !pme_real
%{q}bottom = arith.mulf %{q}d0, %{q}first : !pme_real
memref.store %{q}bottom, {values}[%{p}c0] : memref<8x!pme_real>""")

    body(f"""\
%{p}c0 = arith.constant 0 : index
%{p}c1 = arith.constant 1 : index
%{p}c2 = arith.constant 2 : index
%{p}c3 = arith.constant 3 : index
%{p}c8 = arith.constant 8 : index
%{p}zero = arith.constant 0.0 : !pme_real
%{p}one = arith.constant 1.0 : !pme_real
scf.for %{p}j = %{p}c0 to %{p}c8 step %{p}c1 {{
  memref.store %{p}zero, {values}[%{p}j] : memref<8x!pme_real>
}}
%{p}omw = arith.subf %{p}one, {w} : !pme_real
memref.store %{p}omw, {values}[%{p}c0] : memref<8x!pme_real>
memref.store {w}, {values}[%{p}c1] : memref<8x!pme_real>
scf.for %{p}k = %{p}c3 to {n} step %{p}c1 {{""")
    raise_order(f"%{p}k", "r_")
    body("}")
    if slopes:
        body(f"""\
%{p}v0 = memref.load {values}[%{p}c0] : memref<8x!pme_real>
%{p}s0 = arith.negf %{p}v0 : !pme_real
memref.store %{p}s0, {slopes}[%{p}c0] : memref<8x!pme_real>
scf.for %{p}js = %{p}c1 to {n} step %{p}c1 {{
  %{p}jm1 = arith.subi %{p}js, %{p}c1 : index
  %{p}before = memref.load {values}[%{p}jm1] : memref<8x!pme_real>
  %{p}here = memref.load {values}[%{p}js] : memref<8x!pme_real>
  %{p}slope = arith.subf %{p}before, %{p}here : !pme_real
  memref.store %{p}slope, {slopes}[%{p}js] : memref<8x!pme_real>
}}""")
    raise_order(n, "f_")


def place(body, p, x, length, k, n):
    """The first point and the fraction of a particle at `x` along an edge,
    as @mdrt.pme_place gives them; `length` is one over the edge."""
    body(f"""\
%{p}s = arith.mulf {x}, {length} : f64
%{p}fs = math.floor %{p}s : f64
%{p}frac = arith.subf %{p}s, %{p}fs : f64
%{p}ki = arith.index_cast {k} : index to i32
%{p}kf = arith.sitofp %{p}ki : i32 to !pme_real
%{p}fracr = PME_F64_TO_REAL %{p}frac : f64 to !pme_real
%{p}u = arith.mulf %{p}fracr, %{p}kf : !pme_real
%{p}fu = math.floor %{p}u : !pme_real
%{p}w = arith.subf %{p}u, %{p}fu : !pme_real
%{p}bi32 = arith.fptosi %{p}fu : !pme_real to i32
%{p}bi = arith.extsi %{p}bi32 : i32 to i64
%{p}b = arith.index_cast %{p}bi : i64 to index
%{p}bk = arith.addi %{p}b, {k} : index
%{p}bkn = arith.subi %{p}bk, {n} : index
%{p}c1p = arith.constant 1 : index
%{p}start0 = arith.addi %{p}bkn, %{p}c1p : index
// The first point within the grid, so that the points of the particle need
// one subtraction at most to wrap around.
%{p}start = arith.remui %{p}start0, {k} : index
""")
    return f"%{p}start", f"%{p}w"


def particle_prologue(body, slopes):
    """The splines of particle %i along the three edges."""
    body("""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
// The order of the splines, a constant of the instance, so that the loops
// over it unroll and the splines are held in registers.
%order = arith.constant PME_ORDER : index
%wx = memref.alloca() : memref<8x!pme_real>
%wy = memref.alloca() : memref<8x!pme_real>
%wz = memref.alloca() : memref<8x!pme_real>""")
    if slopes:
        body("""\
%dx = memref.alloca() : memref<8x!pme_real>
%dy = memref.alloca() : memref<8x!pme_real>
%dz = memref.alloca() : memref<8x!pme_real>""")
    body("""\
%xs = memref.load %x[%i, %i0] : memref<?x3x!pme_pos, 1>
%ys = memref.load %x[%i, %i1] : memref<?x3x!pme_pos, 1>
%zs = memref.load %x[%i, %i2] : memref<?x3x!pme_pos, 1>
%qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
%xi = PME_EXTEND_POS %xs : !pme_pos to f64
%yi = PME_EXTEND_POS %ys : !pme_pos to f64
%zi = PME_EXTEND_POS %zs : !pme_pos to f64
%qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real""")
    starts = []
    for axis, (coordinate, length, k, w, d) in enumerate(
        (("%xi", "%ilx", "%k1", "%wx", "%dx"), ("%yi", "%ily", "%k2", "%wy", "%dy"),
         ("%zi", "%ilz", "%k3", "%wz", "%dz"))):
        tag = "xyz"[axis]
        start, fraction = place(body, f"p{tag}_", coordinate, length, k, "%order")
        bspline(body, f"b{tag}_", fraction, "%order", w, d if slopes else None)
        starts.append(start)
    return starts


def pick(body, p, array, index):
    """The element `index` of the spline `array`, a value held in registers:
    compared with every place, so that no load has an index that is not a
    constant once the loop over the order unrolls."""
    body(f"""\
%{p}none = arith.constant 0.0 : !pme_real
%{p}c0 = arith.constant 0 : index
%{p}c1 = arith.constant 1 : index
%{p}value = scf.for %{p}e = %{p}c0 to %order step %{p}c1
    iter_args(%{p}acc = %{p}none) -> (!pme_real) {{
  %{p}at = memref.load {array}[%{p}e] : memref<8x!pme_real>
  %{p}here = arith.cmpi eq, %{p}e, {index} : index
  %{p}chosen = arith.select %{p}here, %{p}at, %{p}acc : !pme_real
  scf.yield %{p}chosen : !pme_real
}}""")
    return f"%{p}value"


def launch(body_text, count):
    return f"""\
  %blocks_{count[1:]} = func.call @mdrt_gpu_pme_blocks({count}) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_{count[1:]}, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, {count} : index
    scf.if %inside {{
{body_text}    }}
    gpu.terminator
  }}
"""


def spread(fixed=True):
    body = Body("      ")
    # A thread for each particle and point of its splines along z, so that
    # the threads of a particle add to neighboring points of the grid at
    # once, as those of GROMACS do.
    body("""\
%lanes = arith.constant PME_ORDER : index
%i = arith.divui %item, %lanes : index
%j3 = arith.remui %item, %lanes : index""")
    sx, sy, sz = particle_prologue(body, slopes=False)
    w3 = pick(body, "w3p_", "%wz", "%j3")
    rounded_line = ("      %rounded = math.roundeven %value : !pme_real" if fixed else "")
    fixed_line = ("      %fixed = arith.fptosi %rounded : !pme_real to i64" if fixed else "")
    if fixed:
        atomic_line = ('      %old = llvm.atomicrmw add %pointer, %fixed syncscope("device") '
                       'monotonic : !llvm.ptr<1>, i64')
    else:
        atomic_line = ("      // An addition without a result: the instance chooses its op,\n"
                       "      // since the NVPTX backend of LLVM expands atomicrmw fadd of f32\n"
                       "      // into a loop of compare-and-swap.\n"
                       "      PME_ATOMIC_ADD %pointer, %value")
    body(f"""\
{"%scale = arith.constant 1099511627776.0 : !pme_real" if fixed else "%scale = arith.constant 1.0 : !pme_real"}
%qscaled = arith.mulf %qi, %scale : !pme_real
%eight = arith.constant {8 if fixed else "PME_REAL_BYTES"} : i64
%gridindex = memref.extract_aligned_pointer_as_index %grid : memref<?x{"i64" if fixed else "!pme_real"}, 1> -> index
// The grid is a buffer of its own, with no offset.
%gridbase = arith.index_cast %gridindex : index to i64
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
// The point of this thread along z; the threads of a particle add to
// points next to one another in memory.
%g3s = arith.addi {sz}, %j3 : index
%g3w = arith.subi %g3s, %k3 : index
%g3over = arith.cmpi uge, %g3s, %k3 : index
%g3 = arith.select %g3over, %g3w, %g3s : index
%q3 = arith.mulf %qscaled, {w3} : !pme_real
scf.for %j1 = %j0 to %order step %j1c {{
  %g1s = arith.addi {sx}, %j1 : index
  %g1w = arith.subi %g1s, %k1 : index
  %g1over = arith.cmpi uge, %g1s, %k1 : index
  %g1 = arith.select %g1over, %g1w, %g1s : index
  %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
  %q13 = arith.mulf %q3, %w1 : !pme_real
  scf.for %j2 = %j0 to %order step %j1c {{
    %g2s = arith.addi {sy}, %j2 : index
    %g2w = arith.subi %g2s, %k2 : index
    %g2over = arith.cmpi uge, %g2s, %k2 : index
    %g2 = arith.select %g2over, %g2w, %g2s : index
    %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
    %value = arith.mulf %q13, %w2 : !pme_real
    %row1 = arith.muli %g1, %k2 : index
    %row = arith.addi %row1, %g2 : index
    %gbase = arith.muli %row, %k3 : index
{rounded_line}
{fixed_line}
    %at = arith.addi %gbase, %g3 : index
    // A relaxed atomic at the scope of the device: the sum needs no
    // order, and one of the system would wait for the host.
    %ati = arith.index_cast %at : index to i64
    %offset = arith.muli %ati, %eight : i64
    %address = arith.addi %gridbase, %offset : i64
    %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
{atomic_line}
  }}
}}""")

    zero = Body("      ")
    zero(f"""\
%none = arith.constant {"0 : i64" if fixed else "0.0 : !pme_real"}
memref.store %none, %grid[%item] : memref<?x{"i64" if fixed else "!pme_real"}, 1>""")
    name = "spread" if fixed else "spread_float"
    what = ("in fixed point, so that the sum does not depend on the order of\n"
            "// the threads (D70; the deterministic mode, D84)") if fixed else (
            "in !pme_real, with floating-point atomics, whose sum depends on\n"
            "// the order of the threads (the default mode, D84)")
    grid_type = "i64" if fixed else "!pme_real"
    return f"""
// Spreads the charges to `grid`, {what}.
func.func private @mdrt_gpu_pme_{name}(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %box: vector<3xf64>, %grid: memref<?x{grid_type}, 1>,
                                       %k1: index, %k2: index, %k3: index, %n: index) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %points = memref.dim %grid, %c0 : memref<?x{grid_type}, 1>
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %spread_lanes = arith.constant PME_ORDER : index
  %spread = arith.muli %count, %spread_lanes : index
{launch(zero.text(), "%points")}{launch(body.text(), "%spread")}  return
}}
"""


def real():
    body = Body("      ")
    body("""\
%inverse = arith.constant 9.094947017729282e-13 : !pme_real
%fixed = memref.load %grid[%item] : memref<?xi64, 1>
%value = arith.sitofp %fixed : i64 to !pme_real
%scaled = arith.mulf %value, %inverse : !pme_real
memref.store %scaled, %real[%item] : memref<?x!pme_real, 1>""")
    return f"""
// The grid in !pme_real, from fixed point.
func.func private @mdrt_gpu_pme_real(%grid: memref<?xi64, 1>, %real: memref<?x!pme_real, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %points = memref.dim %grid, %c0 : memref<?xi64, 1>
{launch(body.text(), "%points")}  return
}}
"""


def wave(body, p, k, count, length, real="f64"):
    """The wave number of the point `k` of `count` along an edge, signed,
    over the edge; `length` is one over the edge, of the type `real`."""
    body(f"""\
%{p}half = arith.divui {count}, %cc2 : index
%{p}ki = arith.index_cast {k} : index to i64
%{p}ni = arith.index_cast {count} : index to i64
%{p}beyond = arith.cmpi ugt, {k}, %{p}half : index
%{p}shifted = arith.subi %{p}ki, %{p}ni : i64
%{p}signed = arith.select %{p}beyond, %{p}shifted, %{p}ki : i64
%{p}sf = arith.sitofp %{p}signed : i64 to {real}
%{p}m = arith.mulf %{p}sf, {length} : {real}""")
    return f"%{p}m"


def convolve():
    body = Body("      ")
    body("""\
%cc0 = arith.constant 0 : index
%cc1 = arith.constant 1 : index
%cc2 = arith.constant 2 : index
%kzero = arith.constant 0.0 : f64
%khalf = arith.constant 0.5 : f64
%kone = arith.constant 1.0 : f64
%ktwo = arith.constant 2.0 : f64
%a = arith.divui %item, %k2 : index
%b = arith.remui %item, %k2 : index""")
    m1 = wave(body, "w1_", "%a", "%k1", "%ilx")
    m2 = wave(body, "w2_", "%b", "%k2", "%ily")
    body(f"""\
%h = arith.divui %k3, %cc2 : index
%h1 = arith.addi %h, %cc1 : index
%odd = arith.remui %k3, %cc2 : index
%even = arith.cmpi eq, %odd, %cc0 : index
%m1s = arith.mulf {m1}, {m1} : f64
%m2s = arith.mulf {m2}, {m2} : f64
%m12 = arith.addf %m1s, %m2s : f64
%mod1 = memref.load %moduli[%cc0, %a] : memref<?x?xf64, 1>
%mod2 = memref.load %moduli[%cc1, %b] : memref<?x?xf64, 1>
%mod12 = arith.mulf %mod1, %mod2 : f64
%ke, %kw00, %kw01, %kw02, %kw11, %kw12, %kw22 = scf.for %z = %cc0 to %h1 step %cc1
    iter_args(%e0 = %kzero, %a00 = %kzero, %a01 = %kzero, %a02 = %kzero,
              %a11 = %kzero, %a12 = %kzero, %a22 = %kzero)
    -> (f64, f64, f64, f64, f64, f64, f64) {{
  %zi = arith.index_cast %z : index to i64
  %zf = arith.sitofp %zi : i64 to f64
  %m3 = arith.mulf %zf, %ilz : f64
  %mod3 = memref.load %moduli[%cc2, %z] : memref<?x?xf64, 1>
  %m3s = arith.mulf %m3, %m3 : f64
  %msq = arith.addf %m12, %m3s : f64
  %origin = arith.cmpf oeq, %msq, %kzero : f64
  %safe = arith.select %origin, %kone, %msq : f64
  %inverse = arith.divf %kone, %safe : f64
  %gm = arith.mulf %gauss, %msq : f64
  %ngm = arith.negf %gm : f64
  %ex = math.exp %ngm : f64
  %exm = arith.mulf %ex, %inverse : f64
  %pexm = arith.mulf %prefactor, %exm : f64
  %mods = arith.mulf %mod12, %mod3 : f64
  %bc0 = arith.mulf %pexm, %mods : f64
  %bc = arith.select %origin, %kzero, %bc0 : f64
  %base1 = arith.muli %item, %h1 : index
  %base2 = arith.addi %base1, %z : index
  %re_at = arith.muli %base2, %cc2 : index
  %im_at = arith.addi %re_at, %cc1 : index
  %rer = memref.load %c[%re_at] : memref<?x!pme_real, 1>
  %imr = memref.load %c[%im_at] : memref<?x!pme_real, 1>
  %re = PME_REAL_TO_F64 %rer : !pme_real to f64
  %im = PME_REAL_TO_F64 %imr : !pme_real to f64
  %re2 = arith.mulf %re, %re : f64
  %im2 = arith.mulf %im, %im : f64
  %g2 = arith.addf %re2, %im2 : f64
  %first = arith.cmpi eq, %z, %cc0 : index
  %middle = arith.cmpi eq, %z, %h : index
  %middle_even = arith.andi %middle, %even : i1
  %single = arith.ori %first, %middle_even : i1
  %weight = arith.select %single, %kone, %ktwo : f64
  %hw = arith.mulf %khalf, %weight : f64
  %hwb = arith.mulf %hw, %bc : f64
  %em = arith.mulf %hwb, %g2 : f64
  %sum = arith.addf %inverse, %gauss : f64
  %factor0 = arith.mulf %ktwo, %sum : f64
  %factor = arith.select %origin, %kzero, %factor0 : f64
  %ef = arith.mulf %em, %factor : f64
  %p11 = arith.mulf {m1}, {m1} : f64
  %p12 = arith.mulf {m1}, {m2} : f64
  %p13 = arith.mulf {m1}, %m3 : f64
  %p22 = arith.mulf {m2}, {m2} : f64
  %p23 = arith.mulf {m2}, %m3 : f64
  %p33 = arith.mulf %m3, %m3 : f64
  %t11 = arith.mulf %ef, %p11 : f64
  %t12 = arith.mulf %ef, %p12 : f64
  %t13 = arith.mulf %ef, %p13 : f64
  %t22 = arith.mulf %ef, %p22 : f64
  %t23 = arith.mulf %ef, %p23 : f64
  %t33 = arith.mulf %ef, %p33 : f64
  %d11 = arith.subf %em, %t11 : f64
  %d22 = arith.subf %em, %t22 : f64
  %d33 = arith.subf %em, %t33 : f64
  %n00 = arith.addf %a00, %d11 : f64
  %n01 = arith.subf %a01, %t12 : f64
  %n02 = arith.subf %a02, %t13 : f64
  %n11 = arith.addf %a11, %d22 : f64
  %n12 = arith.subf %a12, %t23 : f64
  %n22 = arith.addf %a22, %d33 : f64
  %ne = arith.addf %e0, %em : f64
  %reb = arith.mulf %re, %bc : f64
  %imb = arith.mulf %im, %bc : f64
  %rebr = PME_F64_TO_REAL %reb : f64 to !pme_real
  %imbr = PME_F64_TO_REAL %imb : f64 to !pme_real
  memref.store %rebr, %c[%re_at] : memref<?x!pme_real, 1>
  memref.store %imbr, %c[%im_at] : memref<?x!pme_real, 1>
  scf.yield %ne, %n00, %n01, %n02, %n11, %n12, %n22
      : f64, f64, f64, f64, f64, f64, f64
}}
%out = arith.muli %item, %c10 : index""")
    # The row has ten slots and seven sums; the last three hold zeros, so
    # that the copy of the rows reads nothing that no kernel has written.
    for index, name in enumerate(
            ["%ke", "%kw00", "%kw01", "%kw02", "%kw11", "%kw12", "%kw22",
             "%kzero", "%kzero", "%kzero"]):
        body(f"%oc{index} = arith.constant {index} : index")
        body(f"%o{index} = arith.addi %out, %oc{index} : index")
        body(f"memref.store {name}, %rows[%o{index}] : memref<?xf64, 1>")
    return f"""
// Multiplies the half-complex transform `c` by the influence function, which
// it computes from the factors of the edges in `moduli` and the cell, and
// returns the energy and the virial, as @mdrt.pme_convolve does. A thread
// takes a row of the grid, (k1, k2), and writes its sums to `rows`: the
// energy, then the virial xx, xy, xz, yy, yz, zz.
func.func private @mdrt_gpu_pme_convolve(%c: memref<?x!pme_real, 1>, %moduli: memref<?x?xf64, 1>,
                                         %rows: memref<?xf64, 1>, %box: vector<3xf64>,
                                         %beta: f64, %coulomb: f64,
                                         %k1: index, %k2: index, %k3: index)
    -> (f64, vector<9xf64>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c10 = arith.constant 10 : index
  %c128 = arith.constant 128 : index
  %zero = arith.constant 0.0 : f64
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
  %prefactor = arith.divf %coulomb, %piv : f64
  %count = arith.muli %k1, %k2 : index
{launch(body.text(), "%count")}
  // The rows, added up in their order on the host.
  %length = arith.muli %count, %c10 : index
  %host = memref.alloc(%length) : memref<?xf64>
  %t0 = gpu.wait async
  %t1 = gpu.memcpy async [%t0] %host, %rows : memref<?xf64>, memref<?xf64, 1>
  gpu.wait [%t1]
  %e, %w00, %w01, %w02, %w11, %w12, %w22 = scf.for %r = %c0 to %count step %c1
      iter_args(%s0 = %zero, %s1 = %zero, %s2 = %zero, %s3 = %zero,
                %s4 = %zero, %s5 = %zero, %s6 = %zero)
      -> (f64, f64, f64, f64, f64, f64, f64) {{
    %at = arith.muli %r, %c10 : index
    %c2h = arith.constant 2 : index
    %c3h = arith.constant 3 : index
    %c4h = arith.constant 4 : index
    %c5h = arith.constant 5 : index
    %c6h = arith.constant 6 : index
    %a1 = arith.addi %at, %c1 : index
    %a2 = arith.addi %at, %c2h : index
    %a3 = arith.addi %at, %c3h : index
    %a4 = arith.addi %at, %c4h : index
    %a5 = arith.addi %at, %c5h : index
    %a6 = arith.addi %at, %c6h : index
    %v0 = memref.load %host[%at] : memref<?xf64>
    %v1 = memref.load %host[%a1] : memref<?xf64>
    %v2 = memref.load %host[%a2] : memref<?xf64>
    %v3 = memref.load %host[%a3] : memref<?xf64>
    %v4 = memref.load %host[%a4] : memref<?xf64>
    %v5 = memref.load %host[%a5] : memref<?xf64>
    %v6 = memref.load %host[%a6] : memref<?xf64>
    %n0 = arith.addf %s0, %v0 : f64
    %n1 = arith.addf %s1, %v1 : f64
    %n2 = arith.addf %s2, %v2 : f64
    %n3 = arith.addf %s3, %v3 : f64
    %n4 = arith.addf %s4, %v4 : f64
    %n5 = arith.addf %s5, %v5 : f64
    %n6 = arith.addf %s6, %v6 : f64
    scf.yield %n0, %n1, %n2, %n3, %n4, %n5, %n6 : f64, f64, f64, f64, f64, f64, f64
  }}
  memref.dealloc %host : memref<?xf64>
  %virial = vector.from_elements %w00, %w01, %w02, %w01, %w11, %w12, %w02, %w12, %w22 : vector<9xf64>
  return %e, %virial : f64, vector<9xf64>
}}
"""


def scale():
    body = Body("      ")
    body("""\
%cc0 = arith.constant 0 : index
%cc1 = arith.constant 1 : index
%cc2 = arith.constant 2 : index
%kzero = arith.constant 0.0 : f64
%kone = arith.constant 1.0 : f64
// The point, in i32 (D85): a division of 64-bit integers is a long
// sequence of instructions on a device.
%item32 = arith.index_cast %item : index to i32
%row32 = arith.divui %item32, %depth32 : i32
%z32 = arith.remui %item32, %depth32 : i32
%a32 = arith.divui %row32, %k2_32 : i32
%b32 = arith.remui %row32, %k2_32 : i32
%z = arith.index_cast %z32 : i32 to index
%a = arith.index_cast %a32 : i32 to index
%b = arith.index_cast %b32 : i32 to index""")
    m1 = wave(body, "w1_", "%a", "%k1", "%ilxr", "!pme_real")
    m2 = wave(body, "w2_", "%b", "%k2", "%ilyr", "!pme_real")
    body(f"""\
%m1s = arith.mulf {m1}, {m1} : !pme_real
%m2s = arith.mulf {m2}, {m2} : !pme_real
%m12 = arith.addf %m1s, %m2s : !pme_real
// The influence function in !pme_real, f32 in the mixed mode: the
// transform holds no more than that, and f64 is slow on a device.
%mod1 = memref.load %moduli[%cc0, %a] : memref<?x?xf64, 1>
%mod2 = memref.load %moduli[%cc1, %b] : memref<?x?xf64, 1>
%mod3 = memref.load %moduli[%cc2, %z] : memref<?x?xf64, 1>
%mod1r = PME_F64_TO_REAL %mod1 : f64 to !pme_real
%mod2r = PME_F64_TO_REAL %mod2 : f64 to !pme_real
%mod3r = PME_F64_TO_REAL %mod3 : f64 to !pme_real
%mod12 = arith.mulf %mod1r, %mod2r : !pme_real
%modsr = arith.mulf %mod12, %mod3r : !pme_real
%zi = arith.index_cast %z : index to i64
%zf = arith.sitofp %zi : i64 to !pme_real
%m3 = arith.mulf %zf, %ilzr : !pme_real
%m3s = arith.mulf %m3, %m3 : !pme_real
%msqr = arith.addf %m12, %m3s : !pme_real
%rzero = arith.constant 0.0 : !pme_real
%rone = arith.constant 1.0 : !pme_real
%origin = arith.cmpf oeq, %msqr, %rzero : !pme_real
%safe = arith.select %origin, %rone, %msqr : !pme_real
%inverse = arith.divf %rone, %safe : !pme_real
%gm = arith.mulf %gaussr, %msqr : !pme_real
%ngm = arith.negf %gm : !pme_real
%ex = math.exp %ngm : !pme_real
%exm = arith.mulf %ex, %inverse : !pme_real
%pexm = arith.mulf %prefactorr, %exm : !pme_real
%bc0 = arith.mulf %pexm, %modsr : !pme_real
%bc = arith.select %origin, %rzero, %bc0 : !pme_real
%re_at = arith.muli %item, %cc2 : index
%im_at = arith.addi %re_at, %cc1 : index
%re = memref.load %c[%re_at] : memref<?x!pme_real, 1>
%im = memref.load %c[%im_at] : memref<?x!pme_real, 1>
%reb = arith.mulf %re, %bc : !pme_real
%imb = arith.mulf %im, %bc : !pme_real
memref.store %reb, %c[%re_at] : memref<?x!pme_real, 1>
memref.store %imb, %c[%im_at] : memref<?x!pme_real, 1>""")
    return f"""
// Multiplies the half-complex transform `c` by the influence function, as
// @mdrt_gpu_pme_convolve does, where neither the energy nor the virial is
// needed: a thread for each point, and nothing for the host to wait for.
func.func private @mdrt_gpu_pme_scale(%c: memref<?x!pme_real, 1>, %moduli: memref<?x?xf64, 1>,
                                      %box: vector<3xf64>, %beta: f64, %coulomb: f64,
                                      %k1: index, %k2: index, %k3: index) {{
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  %c128 = arith.constant 128 : index
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
  %prefactor = arith.divf %coulomb, %piv : f64
  %gaussr = PME_F64_TO_REAL %gauss : f64 to !pme_real
  %prefactorr = PME_F64_TO_REAL %prefactor : f64 to !pme_real
  %rows = arith.muli %k1, %k2 : index
  %half = arith.divui %k3, %c2 : index
  %depth = arith.addi %half, %c1 : index
  %points = arith.muli %rows, %depth : index
  %depth32 = arith.index_cast %depth : index to i32
  %k2_32 = arith.index_cast %k2 : index to i32
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %ilxr = PME_F64_TO_REAL %ilx : f64 to !pme_real
  %ilyr = PME_F64_TO_REAL %ily : f64 to !pme_real
  %ilzr = PME_F64_TO_REAL %ilz : f64 to !pme_real
{launch(body.text(), "%points")}  return
}}
"""


def spread_warp():
    """A warp for each particle, of order 4: lane = 16 a + 4 b + c takes the
    points (a, b, c) and (a + 2, b, c) of the splines along x, y, z. The
    lanes of an atomic add to 32 points of one particle, none the same, 8
    runs of 4 along z; a warp of 8 particles, next to one another in the
    order, added to the same points at once. Lanes 0 to 2 place the
    particle along one axis each, in f64, and hand the first points and the
    fractions to the others with shuffles."""
    body = Body("      ")
    body("""\
%c32i = arith.constant 32 : index
%i = arith.divui %item, %c32i : index
%lane = arith.remui %item, %c32i : index
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
%i3 = arith.constant 3 : index
%i4 = arith.constant 4 : index
%i16 = arith.constant 16 : index
%order = arith.constant 4 : index
%qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
%qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real
// Lane a < 3 places the particle along axis a.
%axis = arith.minui %lane, %i2 : index
%xs = memref.load %x[%i, %axis] : memref<?x3x!pme_pos, 1>
%xa = PME_EXTEND_POS %xs : !pme_pos to f64
%is_y = arith.cmpi eq, %axis, %i1 : index
%is_z = arith.cmpi eq, %axis, %i2 : index
%il_xy = arith.select %is_y, %ily, %ilx : f64
%il = arith.select %is_z, %ilz, %il_xy : f64
%k_xy = arith.select %is_y, %k2, %k1 : index
%ka = arith.select %is_z, %k3, %k_xy : index""")
    start, frac = place(body, "pa_", "%xa", "%il", "%ka", "%order")
    body(f"""\
%start32 = arith.index_cast {start} : index to i32
%width = arith.constant 32 : i32
%l0 = arith.constant 0 : i32
%l1 = arith.constant 1 : i32
%l2 = arith.constant 2 : i32
%stx32, %v0 = gpu.shuffle idx %start32, %l0, %width : i32
%sty32, %v1 = gpu.shuffle idx %start32, %l1, %width : i32
%stz32, %v2 = gpu.shuffle idx %start32, %l2, %width : i32
%fx, %v3 = gpu.shuffle idx {frac}, %l0, %width : !pme_real
%fy, %v4 = gpu.shuffle idx {frac}, %l1, %width : !pme_real
%fz, %v5 = gpu.shuffle idx {frac}, %l2, %width : !pme_real
%stx = arith.index_cast %stx32 : i32 to index
%sty = arith.index_cast %sty32 : i32 to index
%stz = arith.index_cast %stz32 : i32 to index
%wx = memref.alloca() : memref<8x!pme_real>
%wy = memref.alloca() : memref<8x!pme_real>
%wz = memref.alloca() : memref<8x!pme_real>""")
    bspline(body, "bx_", "%fx", "%order", "%wx", None)
    bspline(body, "by_", "%fy", "%order", "%wy", None)
    bspline(body, "bz_", "%fz", "%order", "%wz", None)
    body("""\
%j3 = arith.remui %lane, %i4 : index
%lane4 = arith.divui %lane, %i4 : index
%j2 = arith.remui %lane4, %i4 : index
%j1a = arith.divui %lane, %i16 : index""")
    w3 = pick(body, "w3p_", "%wz", "%j3")
    w2 = pick(body, "w2p_", "%wy", "%j2")
    body(f"""\
%qyz0 = arith.mulf %qi, {w3} : !pme_real
%qyz = arith.mulf %qyz0, {w2} : !pme_real
%eight = arith.constant PME_REAL_BYTES : i64
%gridindex = memref.extract_aligned_pointer_as_index %grid : memref<?x!pme_real, 1> -> index
%gridbase = arith.index_cast %gridindex : index to i64
%g3s = arith.addi %stz, %j3 : index
%g3w = arith.subi %g3s, %k3 : index
%g3over = arith.cmpi uge, %g3s, %k3 : index
%g3 = arith.select %g3over, %g3w, %g3s : index
%g2s = arith.addi %sty, %j2 : index
%g2w = arith.subi %g2s, %k2 : index
%g2over = arith.cmpi uge, %g2s, %k2 : index
%g2 = arith.select %g2over, %g2w, %g2s : index
scf.for %h = %i0 to %i2 step %i1 {{
  %h2 = arith.muli %h, %i2 : index
  %j1 = arith.addi %j1a, %h2 : index""")
    w1 = pick(body, "w1p_", "%wx", "%j1")
    body(f"""\
  %g1s = arith.addi %stx, %j1 : index
  %g1w = arith.subi %g1s, %k1 : index
  %g1over = arith.cmpi uge, %g1s, %k1 : index
  %g1 = arith.select %g1over, %g1w, %g1s : index
  %value = arith.mulf %qyz, {w1} : !pme_real
  %row1 = arith.muli %g1, %k2 : index
  %row = arith.addi %row1, %g2 : index
  %gbase = arith.muli %row, %k3 : index
  %at = arith.addi %gbase, %g3 : index
  %ati = arith.index_cast %at : index to i64
  %offset = arith.muli %ati, %eight : i64
  %address = arith.addi %gridbase, %offset : i64
  %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
  PME_ATOMIC_ADD %pointer, %value
}}""")
    return f"""
// Spreads the charges to `grid` as @mdrt_gpu_pme_spread_float does, with a
// warp for each particle (order 4 only; see spread_warp in the script).
func.func private @mdrt_gpu_pme_spread_warp(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                            %box: vector<3xf64>, %grid: memref<?x!pme_real, 1>,
                                            %k1: index, %k2: index, %k3: index, %n: index) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %points = memref.dim %grid, %c0 : memref<?x!pme_real, 1>
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %c32 = arith.constant 32 : index
  %spread = arith.muli %count, %c32 : index
{launch(zero_text(), "%points")}{launch(body.text(), "%spread")}  return
}}
"""


def zero_text():
    zero = Body("      ")
    zero("""\
%none = arith.constant 0.0 : !pme_real
memref.store %none, %grid[%item] : memref<?x!pme_real, 1>""")
    return zero.text()


def gather():
    body = Body("      ")
    # A thread for each particle and point of its splines along z, as the
    # spreading has them: the threads of a particle read neighboring points
    # of the grid at once, and their sums are added with shuffles.
    body("""\
%lanes = arith.constant PME_LANES : index
%i = arith.divui %item, %lanes : index
%j3 = arith.remui %item, %lanes : index""")
    sx, sy, sz = particle_prologue(body, slopes=True)
    w3 = pick(body, "w3p_", "%wz", "%j3")
    d3 = pick(body, "d3p_", "%dz", "%j3")
    body(f"""\
%gzero = arith.constant 0.0 : !pme_real
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
%g3s = arith.addi {sz}, %j3 : index
%g3w = arith.subi %g3s, %k3 : index
%g3over = arith.cmpi uge, %g3s, %k3 : index
%g3 = arith.select %g3over, %g3w, %g3s : index
%sumx, %sumy, %sumz = scf.for %j1 = %j0 to %order step %j1c
    iter_args(%ax = %gzero, %ay = %gzero, %az = %gzero) -> (!pme_real, !pme_real, !pme_real) {{
  %g1s = arith.addi {sx}, %j1 : index
  %g1w = arith.subi %g1s, %k1 : index
  %g1over = arith.cmpi uge, %g1s, %k1 : index
  %g1 = arith.select %g1over, %g1w, %g1s : index
  %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
  %d1 = memref.load %dx[%j1] : memref<8x!pme_real>
  %bx2, %by2, %bz2 = scf.for %j2 = %j0 to %order step %j1c
      iter_args(%cx = %ax, %cy = %ay, %cz = %az) -> (!pme_real, !pme_real, !pme_real) {{
    %g2s = arith.addi {sy}, %j2 : index
    %g2w = arith.subi %g2s, %k2 : index
    %g2over = arith.cmpi uge, %g2s, %k2 : index
    %g2 = arith.select %g2over, %g2w, %g2s : index
    %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
    %d2 = memref.load %dy[%j2] : memref<8x!pme_real>
    %row1 = arith.muli %g1, %k2 : index
    %row = arith.addi %row1, %g2 : index
    %gbase = arith.muli %row, %k3 : index
    %at = arith.addi %gbase, %g3 : index
    %p = memref.load %phi[%at] : memref<?x!pme_real, 1>
    %d1w2 = arith.mulf %d1, %w2 : !pme_real
    %w1d2 = arith.mulf %w1, %d2 : !pme_real
    %w1w2 = arith.mulf %w1, %w2 : !pme_real
    %px = arith.mulf %d1w2, {w3} : !pme_real
    %py = arith.mulf %w1d2, {w3} : !pme_real
    %pz = arith.mulf %w1w2, {d3} : !pme_real
    %vx = arith.mulf %p, %px : !pme_real
    %vy = arith.mulf %p, %py : !pme_real
    %vz = arith.mulf %p, %pz : !pme_real
    %nx = arith.addf %cx, %vx : !pme_real
    %ny = arith.addf %cy, %vy : !pme_real
    %nz = arith.addf %cz, %vz : !pme_real
    scf.yield %nx, %ny, %nz : !pme_real, !pme_real, !pme_real
  }}
  scf.yield %bx2, %by2, %bz2 : !pme_real, !pme_real, !pme_real
}}""")
    return f"""
// The forces, as @mdrt.pme_gather gives them: for each particle, a thread
// for each point of its splines along z (PME_LANES threads, the least power
// of 2 not below the order; those beyond it add zeros), and the first
// thread of a particle stores. The threads of a particle are consecutive
// and within a warp. The shuffles take every thread of the
// block, so the threads beyond the last particle compute too, from the
// last particle, and do not store.
func.func private @mdrt_gpu_pme_gather(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %phi: memref<?x!pme_real, 1>, %box: vector<3xf64>,
                                       %k1: index, %k2: index, %k3: index, %n: index,
                                       %f: memref<?x3x!pme_frc, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %k1i = arith.index_cast %k1 : index to i64
  %k2i = arith.index_cast %k2 : index to i64
  %k3i = arith.index_cast %k3 : index to i64
  %k1f = arith.sitofp %k1i : i64 to f64
  %k2f = arith.sitofp %k2i : i64 to f64
  %k3f = arith.sitofp %k3i : i64 to f64
  %rx = arith.divf %k1f, %lx : f64
  %ry = arith.divf %k2f, %ly : f64
  %rz = arith.divf %k3f, %lz : f64
  %rxr = PME_F64_TO_REAL %rx : f64 to !pme_real
  %ryr = PME_F64_TO_REAL %ry : f64 to !pme_real
  %rzr = PME_F64_TO_REAL %rz : f64 to !pme_real
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %lanes_all = arith.constant PME_LANES : index
  %points = arith.muli %count, %lanes_all : index
  %last = arith.subi %count, %c1 : index
{gather_launch(body.text())}  return
}}
"""


def gather_launch(body_text):
    """The launch of the gather: every thread of a block takes part in the
    shuffles, so the threads beyond the last point compute for the last
    particle."""
    return f"""\
  %blocks_points = func.call @mdrt_gpu_pme_blocks(%points) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_points, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
    %base = arith.muli %bx, %c128 : index
    %item0 = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item0, %points : index
    %lanes_l = arith.constant PME_LANES : index
    %c4l = arith.constant 4 : index
    %lane_of = arith.remui %item0, %lanes_l : index
    %last_first = arith.muli %last, %lanes_l : index
    %last_item = arith.addi %last_first, %lane_of : index
    %item = arith.select %inside, %item0, %last_item : index
{body_text}\
      %width = arith.constant 32 : i32
      %one32 = arith.constant 1 : i32
      %two32 = arith.constant 2 : i32
      %sx1, %vsx1 = gpu.shuffle xor %sumx, %one32, %width : !pme_real
      %sy1, %vsy1 = gpu.shuffle xor %sumy, %one32, %width : !pme_real
      %sz1, %vsz1 = gpu.shuffle xor %sumz, %one32, %width : !pme_real
      %tx1 = arith.addf %sumx, %sx1 : !pme_real
      %ty1 = arith.addf %sumy, %sy1 : !pme_real
      %tz1 = arith.addf %sumz, %sz1 : !pme_real
      %sx2, %vsx2 = gpu.shuffle xor %tx1, %two32, %width : !pme_real
      %sy2, %vsy2 = gpu.shuffle xor %ty1, %two32, %width : !pme_real
      %sz2, %vsz2 = gpu.shuffle xor %tz1, %two32, %width : !pme_real
      %ux = arith.addf %tx1, %sx2 : !pme_real
      %uy = arith.addf %ty1, %sy2 : !pme_real
      %uz = arith.addf %tz1, %sz2 : !pme_real
      // With 8 threads a particle, the halves are added too; with 4, the
      // other half of the shuffle is another particle.
      %four32 = arith.constant 4 : i32
      %eight_lanes = arith.cmpi ugt, %lanes_l, %c4l : index
      %sx4, %vsx4 = gpu.shuffle xor %ux, %four32, %width : !pme_real
      %sy4, %vsy4 = gpu.shuffle xor %uy, %four32, %width : !pme_real
      %sz4, %vsz4 = gpu.shuffle xor %uz, %four32, %width : !pme_real
      %zero_r = arith.constant 0.0 : !pme_real
      %hx = arith.select %eight_lanes, %sx4, %zero_r : !pme_real
      %hy = arith.select %eight_lanes, %sy4, %zero_r : !pme_real
      %hz = arith.select %eight_lanes, %sz4, %zero_r : !pme_real
      %allx = arith.addf %ux, %hx : !pme_real
      %ally = arith.addf %uy, %hy : !pme_real
      %allz = arith.addf %uz, %hz : !pme_real
      %first = arith.cmpi eq, %j3, %c0 : index
      %stores = arith.andi %inside, %first : i1
      scf.if %stores {{
        %mq = arith.negf %qi : !pme_real
        %sxq = arith.mulf %mq, %rxr : !pme_real
        %syq = arith.mulf %mq, %ryr : !pme_real
        %szq = arith.mulf %mq, %rzr : !pme_real
        %fx64 = arith.mulf %sxq, %allx : !pme_real
        %fy64 = arith.mulf %syq, %ally : !pme_real
        %fz64 = arith.mulf %szq, %allz : !pme_real
        %fxs = PME_REAL_TO_FRC %fx64 : !pme_real to !pme_frc
        %fys = PME_REAL_TO_FRC %fy64 : !pme_real to !pme_frc
        %fzs = PME_REAL_TO_FRC %fz64 : !pme_real to !pme_frc
        memref.store %fxs, %f[%i, %i0] : memref<?x3x!pme_frc, 1>
        memref.store %fys, %f[%i, %i1] : memref<?x3x!pme_frc, 1>
        memref.store %fzs, %f[%i, %i2] : memref<?x3x!pme_frc, 1>
      }}
    gpu.terminator
  }}
"""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "..", "lib", "Runtime", "Templates", "PMEGPU.mlir")
    with open(path, "w") as file:
        file.write(HEADER + spread() + spread(fixed=False) + spread_warp() + real() +
                   convolve() + scale() + gather())


if __name__ == "__main__":
    main()
