#!/usr/bin/env python3
"""Writes the generated part of lib/Runtime/Templates/NeighborsMatrix.mlir and
NeighborsMatrixGPU.mlir: the build of the neighbor matrix of a triclinic cell
that takes a pair if any of its images is within the reach
(docs/triclinic-m2.md, Section 2, D[matrix-images]), and the function that
chooses between it and the build that tests the image of the one pass alone.

The build of the one pass, `..._triclinic_pass`, is written by hand in each
template. The build of all images is that function with the test of a
candidate replaced: a candidate whose image of the pass is beyond the reach
is tested at the others. It is a function of its own, not a branch in the
loops of the first, so that a build in a cell wider than twice the reach, the
common case, runs the code it ran before: a branch that is never taken in
the search of the device cost 6% of a build (19,072 particles, RTX 3090).

    generate-matrix-images-template.py [DIRECTORY]

rewrites the part between the lines BEGIN GENERATED and END GENERATED of the
two templates of the repository, or writes the two files to DIRECTORY, which
test/Runtime/generated-templates.test compares with them.
"""
import os
import sys

BEGIN = ("// BEGIN GENERATED by scripts/generate-matrix-images-template.py. "
         "Do not edit.\n")
END = "// END GENERATED\n"

WITHIN = """\
// Whether an image of the displacement d of a pair is within the reach,
// `far`, whose square is `limit2`, in a triclinic cell of the diagonal a_x,
// b_y, c_z and the tilts b_x, c_x, c_y (docs/triclinic-m2.md, Section 2).
// H is lower triangular, so z' = d_z - n_c c_z depends on n_c alone, y' on
// n_c and n_b, and x' on all three: the images with |z'|, |y'|, |x'| within
// the reach, which hold every image within it, are the n_c of
// [(d_z - far) / c_z, (d_z + far) / c_z], for each the n_b of the same range
// of y' over b_y, and for each the n_a of that of x' over a_x. From the
// image of the one pass and with a reach of at most the least of a_x, b_y,
// c_z these are that image and, where L - |d| along an axis is less than
// the reach, the one on the other side: 8 at most. The numbers a side are
// at most `most`: a cell that a failed run has blown up gives loops that
// end, as it gives a count of cells that is defined (#168).
func.func private @NAME(
    %dx: f32, %dy: f32, %dz: f32, %ax: f32, %by: f32, %cz: f32, %bx: f32,
    %cx: f32, %cy: f32, %iax: f32, %iby: f32, %icz: f32, %far: f32,
    %limit2: f32, %most: f32) -> i1 {
  %one = arith.constant 1 : i32
  %false = arith.constant false
  %least = arith.negf %most : f32
  %zl0 = arith.subf %dz, %far : f32
  %zh0 = arith.addf %dz, %far : f32
  %zl1 = arith.mulf %zl0, %icz : f32
  %zh1 = arith.mulf %zh0, %icz : f32
  %zl2 = math.ceil %zl1 : f32
  %zh2 = math.floor %zh1 : f32
  %zl3 = arith.maxnumf %zl2, %least : f32
  %zh3 = arith.minnumf %zh2, %most : f32
  %zl = arith.fptosi %zl3 : f32 to i32
  %zh4 = arith.fptosi %zh3 : f32 to i32
  %zh = arith.addi %zh4, %one : i32
  %found = scf.for %nc = %zl to %zh step %one
      iter_args(%found_c = %false) -> (i1) : i32 {
    %fc = arith.sitofp %nc : i32 to f32
    %sz = arith.mulf %fc, %cz : f32
    %sy = arith.mulf %fc, %cy : f32
    %sx = arith.mulf %fc, %cx : f32
    %z = arith.subf %dz, %sz : f32
    %y1 = arith.subf %dy, %sy : f32
    %x1 = arith.subf %dx, %sx : f32
    %z2 = arith.mulf %z, %z : f32
    %yl0 = arith.subf %y1, %far : f32
    %yh0 = arith.addf %y1, %far : f32
    %yl1 = arith.mulf %yl0, %iby : f32
    %yh1 = arith.mulf %yh0, %iby : f32
    %yl2 = math.ceil %yl1 : f32
    %yh2 = math.floor %yh1 : f32
    %yl3 = arith.maxnumf %yl2, %least : f32
    %yh3 = arith.minnumf %yh2, %most : f32
    %yl = arith.fptosi %yl3 : f32 to i32
    %yh4 = arith.fptosi %yh3 : f32 to i32
    %yh = arith.addi %yh4, %one : i32
    %after_b = scf.for %nb = %yl to %yh step %one
        iter_args(%found_b = %found_c) -> (i1) : i32 {
      %fb = arith.sitofp %nb : i32 to f32
      %ty = arith.mulf %fb, %by : f32
      %tx = arith.mulf %fb, %bx : f32
      %y = arith.subf %y1, %ty : f32
      %x2 = arith.subf %x1, %tx : f32
      %y2 = arith.mulf %y, %y : f32
      %zy2 = arith.addf %z2, %y2 : f32
      %xl0 = arith.subf %x2, %far : f32
      %xh0 = arith.addf %x2, %far : f32
      %xl1 = arith.mulf %xl0, %iax : f32
      %xh1 = arith.mulf %xh0, %iax : f32
      %xl2 = math.ceil %xl1 : f32
      %xh2 = math.floor %xh1 : f32
      %xl3 = arith.maxnumf %xl2, %least : f32
      %xh3 = arith.minnumf %xh2, %most : f32
      %xl = arith.fptosi %xl3 : f32 to i32
      %xh4 = arith.fptosi %xh3 : f32 to i32
      %xh = arith.addi %xh4, %one : i32
      %after_a = scf.for %na = %xl to %xh step %one
          iter_args(%found_a = %found_b) -> (i1) : i32 {
        %fa = arith.sitofp %na : i32 to f32
        %ux = arith.mulf %fa, %ax : f32
        %x = arith.subf %x2, %ux : f32
        %xx = arith.mulf %x, %x : f32
        %r2 = arith.addf %zy2, %xx : f32
        %near = arith.cmpf olt, %r2, %limit2 : f32
        %next = arith.ori %found_a, %near : i1
        scf.yield %next : i1
      }
      scf.yield %after_a : i1
    }
    scf.yield %after_b : i1
  }
  return %found : i1
}

"""

# After the square of the reach: the reach in f32 and the most images a side.
SETUP_OLD = """\
  %far2 = arith.mulf %far, %far : f64
  %limit2 = arith.truncf %far2 : f64 to f32
"""
SETUP_NEW = SETUP_OLD + """\
  %narrow_far = arith.truncf %far : f64 to f32
  %most_images = arith.constant 64.0 : f32
"""

ARGUMENTS = """\
%dx, %dy, %dz, %narrow_lx, %narrow_ly, %narrow_lz,
{0}%narrow_bx, %narrow_cx, %narrow_cy, %narrow_ilx,
{0}%narrow_ily, %narrow_ilz, %narrow_far, %limit2,
{0}%most_images)
{0}: (f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32,
{0}   f32, f32, f32, f32) -> i1
"""

HOST = {
    "file": "NeighborsMatrix.mlir",
    "pass": "@mdrt.build_neighbors_matrix_triclinic_pass",
    "images": "@mdrt.build_neighbors_matrix_triclinic_images",
    "within": "@mdrt.image_within_triclinic",
    "test_old": """\
            %near = arith.cmpf olt, %r2, %limit2 : f32
            %other = arith.cmpi ne, %p, %q : index
""",
    "test_new": """\
            // A candidate whose image of the pass is beyond the reach is
            // tested at its other images within the reach.
            %near_pass = arith.cmpf olt, %r2, %limit2 : f32
            %near = scf.if %near_pass -> (i1) {
              scf.yield %near_pass : i1
            } else {
              %near_image = func.call @mdrt.image_within_triclinic(
                  """ + ARGUMENTS.format(" " * 18) + """\
              scf.yield %near_image : i1
            }
            %other = arith.cmpi ne, %p, %q : index
""",
    "doc": """\
// The neighbor matrix of a triclinic cell where the reach may be more than
// half of the least of a_x, b_y, c_z: the build of
// @mdrt.build_neighbors_matrix_triclinic_pass with the test of a candidate
// at every image within the reach. A row holds a particle once if any of
// its images is within `reach`.
""",
    "dispatch": """\
// The neighbor matrix of a triclinic cell, `box` = (a_x, b_y, c_z, b_x,
// c_x, c_y), with the widths of the cell between its faces, `widths`
// (docs/triclinic-m2.md, Section 2). A row holds a particle once if any of
// its images is within `reach`. Where the reach is at most half of the
// least of a_x, b_y, c_z that is the image of the one pass along c, b, and
// a, and the build tests it alone; in a narrower cell it tests the others
// within the reach as well. The reach is compared with 0.49 of the least,
// which leaves room for the margin of the search in f32. The loops over
// pairs take the image of the pass, the only one that can be within a
// cutoff of at most half of the least of a_x, b_y, c_z.
func.func private @mdrt.build_neighbors_matrix_triclinic(
    %x: memref<?x3xf64>, %box: vector<6xf64>, %widths: vector<3xf64>,
    %reach: f64, %cell_width: f64,
    %counts: memref<?xi32>, %index: memref<?x?xi32>) -> index {
  %lx = vector.extract %box[0] : f64 from vector<6xf64>
  %ly = vector.extract %box[1] : f64 from vector<6xf64>
  %lz = vector.extract %box[2] : f64 from vector<6xf64>
  %least_xy = arith.minimumf %lx, %ly : f64
  %least = arith.minimumf %least_xy, %lz : f64
  %part = arith.constant 0.49 : f64
  %bound = arith.mulf %least, %part : f64
  %within = arith.cmpf ole, %reach, %bound : f64
  %largest = scf.if %within -> (index) {
    %one = func.call @mdrt.build_neighbors_matrix_triclinic_pass(
        %x, %box, %widths, %reach, %cell_width, %counts, %index)
        : (memref<?x3xf64>, vector<6xf64>, vector<3xf64>, f64, f64,
           memref<?xi32>, memref<?x?xi32>) -> index
    scf.yield %one : index
  } else {
    %all = func.call @mdrt.build_neighbors_matrix_triclinic_images(
        %x, %box, %widths, %reach, %cell_width, %counts, %index)
        : (memref<?x3xf64>, vector<6xf64>, vector<3xf64>, f64, f64,
           memref<?xi32>, memref<?x?xi32>) -> index
    scf.yield %all : index
  }
  return %largest : index
}

""",
}

DEVICE = {
    "file": "NeighborsMatrixGPU.mlir",
    "pass": "@mdrt_gpu_build_neighbors_matrix_triclinic_pass",
    "images": "@mdrt_gpu_build_neighbors_matrix_triclinic_images",
    "within": "@mdrt_gpu_matrix_image_within",
    "test_old": """\
            %near = arith.cmpf olt, %r2, %limit2 : f32
            %other = arith.cmpi ne, %p32, %q32 : i32
""",
    "test_new": """\
            // A lane whose image of the pass is beyond the reach tests the
            // other images within the reach, on its own; the ballot below
            // is of all lanes.
            %near_pass = arith.cmpf olt, %r2, %limit2 : f32
            %true_w = arith.constant true
            %far_pass = arith.xori %near_pass, %true_w : i1
            %try = arith.andi %far_pass, %in_run : i1
            %near = scf.if %try -> (i1) {
              %near_image = func.call @mdrt_gpu_matrix_image_within(
                  """ + ARGUMENTS.format(" " * 18) + """\
              scf.yield %near_image : i1
            } else {
              scf.yield %near_pass : i1
            }
            %other = arith.cmpi ne, %p32, %q32 : i32
""",
    "doc": """\
// The neighbor matrix of a triclinic cell on a device where the reach may
// be more than half of the least of a_x, b_y, c_z: the build of
// @mdrt_gpu_build_neighbors_matrix_triclinic_pass with the test of a
// candidate at every image within the reach, as on the host.
""",
    "dispatch": """\
// The neighbor matrix of a triclinic cell on a device (docs/triclinic-m2.md,
// Section 2): a row holds a particle once if any of its images is within
// `reach`, as @mdrt.build_neighbors_matrix_triclinic of the host has it.
// Where the reach is at most 0.49 of the least of a_x, b_y, c_z the build
// tests the image of the one pass alone, the kernels of before; in a
// narrower cell, the others within the reach as well.
func.func private @mdrt_gpu_build_neighbors_matrix_triclinic(
    %x: memref<?x3xf64, 1>, %box: vector<6xf64>, %widths: vector<3xf64>,
    %reach: f64, %cell_width: f64, %excluded: memref<?x?xi32, 1>,
    %counts: memref<?xi32, 1>, %index: memref<?x?xi32, 1>,
    %order: memref<?xi32, 1>) -> (index, index) {
  %lx = vector.extract %box[0] : f64 from vector<6xf64>
  %ly = vector.extract %box[1] : f64 from vector<6xf64>
  %lz = vector.extract %box[2] : f64 from vector<6xf64>
  %least_xy = arith.minimumf %lx, %ly : f64
  %least = arith.minimumf %least_xy, %lz : f64
  %part = arith.constant 0.49 : f64
  %bound = arith.mulf %least, %part : f64
  %within = arith.cmpf ole, %reach, %bound : f64
  %largest, %not_numbers = scf.if %within -> (index, index) {
    %one, %one_not = func.call @mdrt_gpu_build_neighbors_matrix_triclinic_pass(
        %x, %box, %widths, %reach, %cell_width, %excluded, %counts, %index,
        %order)
        : (memref<?x3xf64, 1>, vector<6xf64>, vector<3xf64>, f64, f64,
           memref<?x?xi32, 1>, memref<?xi32, 1>, memref<?x?xi32, 1>,
           memref<?xi32, 1>) -> (index, index)
    scf.yield %one, %one_not : index, index
  } else {
    %all, %all_not = func.call @mdrt_gpu_build_neighbors_matrix_triclinic_images(
        %x, %box, %widths, %reach, %cell_width, %excluded, %counts, %index,
        %order)
        : (memref<?x3xf64, 1>, vector<6xf64>, vector<3xf64>, f64, f64,
           memref<?x?xi32, 1>, memref<?xi32, 1>, memref<?x?xi32, 1>,
           memref<?xi32, 1>) -> (index, index)
    scf.yield %all, %all_not : index, index
  }
  return %largest, %not_numbers : index, index
}

""",
}


def replace_once(text, old, new):
    assert text.count(old) == 1, old
    return text.replace(old, new)


def generate(text, spec):
    """The template `text` with its generated part written anew."""
    start = text.index("func.func private " + spec["pass"] + "(")
    stop = text.index("\n}\n", start) + 3
    body = text[start:stop]
    body = replace_once(body, spec["pass"] + "(", spec["images"] + "(")
    body = replace_once(body, SETUP_OLD, SETUP_NEW)
    body = replace_once(body, spec["test_old"], spec["test_new"])
    generated = (BEGIN + "\n" + WITHIN.replace("@NAME", spec["within"]) +
                 spec["doc"] + body + "\n" + spec["dispatch"] + END)
    begin = text.index(BEGIN)
    end = text.index(END, begin) + len(END)
    return text[:begin] + generated + text[end:]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    templates = os.path.join(here, "..", "lib", "Runtime", "Templates")
    target = sys.argv[1] if len(sys.argv) > 1 else templates
    for spec in (HOST, DEVICE):
        with open(os.path.join(templates, spec["file"])) as file:
            text = file.read()
        with open(os.path.join(target, spec["file"]), "w") as file:
            file.write(generate(text, spec))


if __name__ == "__main__":
    main()
