#!/usr/bin/env python3
"""Writes lib/Runtime/Templates/PMEGPU.mlir, the template of the reciprocal
sum of particle mesh Ewald on a device, and PMEGPUTriclinic.mlir, its
kernels for a triclinic cell.

    python3 scripts/generate-pme-gpu-template.py

The kernels compute what those of the template for the host compute
(lib/Runtime/Templates/PME.mlir), point by point and particle by particle.
A kernel cannot call a function, so the B-splines are written out in each
kernel that needs them; this script writes them. Edit the script, not the
template."""

import os
import re
import sys

# Whether the kernels being written are those of a triclinic cell, whose
# fractional coordinates are s = x H⁻¹ and whose wave vectors are k = H⁻¹ m
# (docs/triclinic-m2.md); main writes them to a template of their own.
TILTED = False

# Whether the kernels being written are those of the sum of the dispersion
# (D162), whose influence function is not a product of factors of the
# axes: named with `_dispersion`, for tables, convolve, and scale only.
DISPERSION = False

HEADER = """\
// The reciprocal sum of smooth particle mesh Ewald on a device
// [Essmann1995] (docs/pme-m1.md). The keys are those of
// docs/references.md.
//
// Generated by scripts/generate-pme-gpu-template.py. Do not edit.
//
// This is a template. The compiler adds it to a module that has a
// reciprocal sum on a device, where it is specialized like any other code;
// the types of the positions, the charges, and the forces and their
// conversions are those of the template for the host (PME.mlir); the
// splines, the grid, and its transform are in !pme_real, which is the type
// of the forces, while the fractions of the positions and the edges of the
// cell are in f64. The buffers are on the device.
//
// A kernel runs one thread per item, in blocks of 128 threads. The threads
// beyond the last item do nothing. In the deterministic mode the charges
// are added to the grid in fixed point with integer atomics, as the fixed
// point of Le Grand et al. accumulates forces [LeGrand2013], so that the
// sum does not depend on the order of the threads (D70); by default they
// are added in !pme_real with floating-point atomics (D84). The product
// with the influence function sums
// the energy and the virial of each row of the grid in a thread; the host
// adds the rows up in their order.

!pme_pos = f64
!pme_chg = f64
!pme_frc = f64
// The type in which the splines, the grid, and its transform are computed:
// that of the forces on a device, so f32 in the mixed and single modes.
!pme_real = f64

func.func private @mdrt_gpu_pme_blocks(%count: index) -> index {
  %c127 = arith.constant 127 : index
  %c128 = arith.constant 128 : index
  %padded = arith.addi %count, %c127 : index
  %result = arith.divui %padded, %c128 : index
  return %result : index
}
"""


class Body:
    """Lines of a kernel, with names of their own."""

    def __init__(self, indent):
        self.indent = indent
        self.lines = []

    def __call__(self, text):
        for line in text.splitlines():
            self.lines.append(self.indent + line if line else "")

    def text(self):
        return "\n".join(self.lines) + "\n"


def bspline(body, p, w, n, values, slopes):
    """The weights and, if `slopes`, their derivatives of the B-spline of
    order `n` at the fraction `w`, into the arrays `values` and `slopes`
    (the recursion of Essmann et al., as @mdrt.pme_bspline does)."""

    def raise_order(k, tag):
        q = p + tag
        body(f"""\
%{q}km1 = arith.subi {k}, %{p}c1 : index
%{q}km2 = arith.subi {k}, %{p}c2 : index
%{q}km1i = arith.index_cast %{q}km1 : index to i64
%{q}km1f = arith.sitofp %{q}km1i : i64 to !pme_real
%{q}div = arith.divf %{p}one, %{q}km1f : !pme_real
%{q}ki = arith.index_cast {k} : index to i64
%{q}kf = arith.sitofp %{q}ki : i64 to !pme_real
%{q}last = memref.load {values}[%{q}km2] : memref<8x!pme_real>
%{q}dw = arith.mulf %{q}div, {w} : !pme_real
%{q}top = arith.mulf %{q}dw, %{q}last : !pme_real
memref.store %{q}top, {values}[%{q}km1] : memref<8x!pme_real>
scf.for %{q}j = %{p}c1 to %{q}km1 step %{p}c1 {{
  %{q}ji = arith.index_cast %{q}j : index to i64
  %{q}jf = arith.sitofp %{q}ji : i64 to !pme_real
  %{q}at = arith.subi %{q}km1, %{q}j : index
  %{q}below = arith.subi %{q}at, %{p}c1 : index
  %{q}lo = memref.load {values}[%{q}below] : memref<8x!pme_real>
  %{q}hi = memref.load {values}[%{q}at] : memref<8x!pme_real>
  %{q}wj = arith.addf {w}, %{q}jf : !pme_real
  %{q}kj = arith.subf %{q}kf, %{q}jf : !pme_real
  %{q}kjw = arith.subf %{q}kj, {w} : !pme_real
  %{q}t1 = arith.mulf %{q}wj, %{q}lo : !pme_real
  %{q}t2 = arith.mulf %{q}kjw, %{q}hi : !pme_real
  %{q}sum = arith.addf %{q}t1, %{q}t2 : !pme_real
  %{q}value = arith.mulf %{q}div, %{q}sum : !pme_real
  memref.store %{q}value, {values}[%{q}at] : memref<8x!pme_real>
}}
%{q}first = memref.load {values}[%{p}c0] : memref<8x!pme_real>
%{q}omw = arith.subf %{p}one, {w} : !pme_real
%{q}d0 = arith.mulf %{q}div, %{q}omw : !pme_real
%{q}bottom = arith.mulf %{q}d0, %{q}first : !pme_real
memref.store %{q}bottom, {values}[%{p}c0] : memref<8x!pme_real>""")

    body(f"""\
%{p}c0 = arith.constant 0 : index
%{p}c1 = arith.constant 1 : index
%{p}c2 = arith.constant 2 : index
%{p}c3 = arith.constant 3 : index
%{p}c8 = arith.constant 8 : index
%{p}zero = arith.constant 0.0 : !pme_real
%{p}one = arith.constant 1.0 : !pme_real
scf.for %{p}j = %{p}c0 to %{p}c8 step %{p}c1 {{
  memref.store %{p}zero, {values}[%{p}j] : memref<8x!pme_real>
}}
%{p}omw = arith.subf %{p}one, {w} : !pme_real
memref.store %{p}omw, {values}[%{p}c0] : memref<8x!pme_real>
memref.store {w}, {values}[%{p}c1] : memref<8x!pme_real>
scf.for %{p}k = %{p}c3 to {n} step %{p}c1 {{""")
    raise_order(f"%{p}k", "r_")
    body("}")
    if slopes:
        body(f"""\
%{p}v0 = memref.load {values}[%{p}c0] : memref<8x!pme_real>
%{p}s0 = arith.negf %{p}v0 : !pme_real
memref.store %{p}s0, {slopes}[%{p}c0] : memref<8x!pme_real>
scf.for %{p}js = %{p}c1 to {n} step %{p}c1 {{
  %{p}jm1 = arith.subi %{p}js, %{p}c1 : index
  %{p}before = memref.load {values}[%{p}jm1] : memref<8x!pme_real>
  %{p}here = memref.load {values}[%{p}js] : memref<8x!pme_real>
  %{p}slope = arith.subf %{p}before, %{p}here : !pme_real
  memref.store %{p}slope, {slopes}[%{p}js] : memref<8x!pme_real>
}}""")
    raise_order(n, "f_")


def place(body, p, x, length, k, n):
    """The first point and the fraction of a particle at `x` along an edge,
    as @mdrt.pme_place gives them; `length` is one over the edge."""
    body(f"""\
%{p}s = arith.mulf {x}, {length} : f64
%{p}fs = math.floor %{p}s : f64
%{p}frac = arith.subf %{p}s, %{p}fs : f64
%{p}ki = arith.index_cast {k} : index to i32
%{p}kf = arith.sitofp %{p}ki : i32 to !pme_real
%{p}fracr = PME_F64_TO_REAL %{p}frac : f64 to !pme_real
%{p}u = arith.mulf %{p}fracr, %{p}kf : !pme_real
%{p}fu0 = math.floor %{p}u : !pme_real
// A coordinate that is not a number takes the point 0, so that the
// conversion to an integer is defined and every point is in the grid
// (#168); the fraction is in [0, 1] otherwise, and so is this.
%{p}nil = arith.constant 0.0 : !pme_real
%{p}fu = arith.maxnumf %{p}fu0, %{p}nil : !pme_real
%{p}w = arith.subf %{p}u, %{p}fu : !pme_real
%{p}bi32 = arith.fptosi %{p}fu : !pme_real to i32
%{p}bi = arith.extsi %{p}bi32 : i32 to i64
%{p}b = arith.index_cast %{p}bi : i64 to index
%{p}bk = arith.addi %{p}b, {k} : index
%{p}bkn = arith.subi %{p}bk, {n} : index
%{p}c1p = arith.constant 1 : index
%{p}start0 = arith.addi %{p}bkn, %{p}c1p : index
// The first point within the grid, so that the points of the particle need
// one subtraction at most to wrap around.
%{p}start = arith.remui %{p}start0, {k} : index
""")
    return f"%{p}start", f"%{p}w"


def fractions(body, x, y, z):
    """The fractional coordinates s = x H⁻¹ of a triclinic cell, with H⁻¹
    lower triangular, as places for `place`: each with one as its length."""
    body(f"""\
%fr_one = arith.constant 1.0 : f64
%fr_z = arith.mulf {z}, %h22 : f64
%fr_y1 = arith.mulf {y}, %h11 : f64
%fr_y2 = arith.mulf {z}, %h21 : f64
%fr_y = arith.addf %fr_y1, %fr_y2 : f64
%fr_x1 = arith.mulf {x}, %h00 : f64
%fr_x2 = arith.mulf {y}, %h10 : f64
%fr_x3 = arith.mulf {z}, %h20 : f64
%fr_x12 = arith.addf %fr_x1, %fr_x2 : f64
%fr_x = arith.addf %fr_x12, %fr_x3 : f64""")
    return (("%fr_x", "%fr_one"), ("%fr_y", "%fr_one"), ("%fr_z", "%fr_one"))


def particle_prologue(body, slopes):
    """The splines of particle %i along the three edges."""
    body("""\
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
// The order of the splines, a constant of the instance, so that the loops
// over it unroll and the splines are held in registers.
%order = arith.constant PME_ORDER : index
%wx = memref.alloca() : memref<8x!pme_real>
%wy = memref.alloca() : memref<8x!pme_real>
%wz = memref.alloca() : memref<8x!pme_real>""")
    if slopes:
        body("""\
%dx = memref.alloca() : memref<8x!pme_real>
%dy = memref.alloca() : memref<8x!pme_real>
%dz = memref.alloca() : memref<8x!pme_real>""")
    body("""\
%xs = memref.load %x[%i, %i0] : memref<?x3x!pme_pos, 1>
%ys = memref.load %x[%i, %i1] : memref<?x3x!pme_pos, 1>
%zs = memref.load %x[%i, %i2] : memref<?x3x!pme_pos, 1>
%qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
%xi = PME_EXTEND_POS %xs : !pme_pos to f64
%yi = PME_EXTEND_POS %ys : !pme_pos to f64
%zi = PME_EXTEND_POS %zs : !pme_pos to f64
%qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real""")
    places = (("%xi", "%ilx"), ("%yi", "%ily"), ("%zi", "%ilz"))
    if TILTED:
        places = fractions(body, "%xi", "%yi", "%zi")
    starts = []
    for axis, ((coordinate, length), k, w, d) in enumerate(
        zip(places, ("%k1", "%k2", "%k3"), ("%wx", "%wy", "%wz"),
            ("%dx", "%dy", "%dz"))):
        tag = "xyz"[axis]
        start, fraction = place(body, f"p{tag}_", coordinate, length, k, "%order")
        bspline(body, f"b{tag}_", fraction, "%order", w, d if slopes else None)
        starts.append(start)
    return starts


def pick(body, p, array, index):
    """The element `index` of the spline `array`, a value held in registers:
    compared with every place, so that no load has an index that is not a
    constant once the loop over the order unrolls."""
    body(f"""\
%{p}none = arith.constant 0.0 : !pme_real
%{p}c0 = arith.constant 0 : index
%{p}c1 = arith.constant 1 : index
%{p}value = scf.for %{p}e = %{p}c0 to %order step %{p}c1
    iter_args(%{p}acc = %{p}none) -> (!pme_real) {{
  %{p}at = memref.load {array}[%{p}e] : memref<8x!pme_real>
  %{p}here = arith.cmpi eq, %{p}e, {index} : index
  %{p}chosen = arith.select %{p}here, %{p}at, %{p}acc : !pme_real
  scf.yield %{p}chosen : !pme_real
}}""")
    return f"%{p}value"


def launch(body_text, count):
    return f"""\
  %blocks_{count[1:]} = func.call @mdrt_gpu_pme_blocks({count}) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_{count[1:]}, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
    %base = arith.muli %bx, %c128 : index
    %item = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item, {count} : index
    scf.if %inside {{
{body_text}    }}
    gpu.terminator
  }}
"""


def spread(fixed=True):
    body = Body("      ")
    # A thread for each particle and point of its splines along z, so that
    # the threads of a particle add to neighboring points of the grid at
    # once, as those of GROMACS do.
    body("""\
%lanes = arith.constant PME_ORDER : index
%i = arith.divui %item, %lanes : index
%j3 = arith.remui %item, %lanes : index""")
    sx, sy, sz = particle_prologue(body, slopes=False)
    w3 = pick(body, "w3p_", "%wz", "%j3")
    rounded_line = ("      %rounded = math.roundeven %value : !pme_real" if fixed else "")
    fixed_line = ("      %fixed = arith.fptosi %rounded : !pme_real to i64" if fixed else "")
    if fixed:
        atomic_line = ('      %old = llvm.atomicrmw add %pointer, %fixed syncscope("device") '
                       'monotonic : !llvm.ptr<1>, i64')
    else:
        atomic_line = ("      // An addition without a result: the instance chooses its op,\n"
                       "      // since the NVPTX backend of LLVM expands atomicrmw fadd of f32\n"
                       "      // into a loop of compare-and-swap.\n"
                       "      PME_ATOMIC_ADD %pointer, %value")
    body(f"""\
{"%scale = arith.constant 1099511627776.0 : !pme_real" if fixed else "%scale = arith.constant 1.0 : !pme_real"}
%qscaled = arith.mulf %qi, %scale : !pme_real
%eight = arith.constant {8 if fixed else "PME_REAL_BYTES"} : i64
%gridindex = memref.extract_aligned_pointer_as_index %grid : memref<?x{"i64" if fixed else "!pme_real"}, 1> -> index
// The grid is a buffer of its own, with no offset.
%gridbase = arith.index_cast %gridindex : index to i64
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
// The point of this thread along z; the threads of a particle add to
// points next to one another in memory.
%g3s = arith.addi {sz}, %j3 : index
%g3w = arith.subi %g3s, %k3 : index
%g3over = arith.cmpi uge, %g3s, %k3 : index
%g3 = arith.select %g3over, %g3w, %g3s : index
%q3 = arith.mulf %qscaled, {w3} : !pme_real
scf.for %j1 = %j0 to %order step %j1c {{
  %g1s = arith.addi {sx}, %j1 : index
  %g1w = arith.subi %g1s, %k1 : index
  %g1over = arith.cmpi uge, %g1s, %k1 : index
  %g1 = arith.select %g1over, %g1w, %g1s : index
  %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
  %q13 = arith.mulf %q3, %w1 : !pme_real
  scf.for %j2 = %j0 to %order step %j1c {{
    %g2s = arith.addi {sy}, %j2 : index
    %g2w = arith.subi %g2s, %k2 : index
    %g2over = arith.cmpi uge, %g2s, %k2 : index
    %g2 = arith.select %g2over, %g2w, %g2s : index
    %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
    %value = arith.mulf %q13, %w2 : !pme_real
    %row1 = arith.muli %g1, %k2 : index
    %row = arith.addi %row1, %g2 : index
    %gbase = arith.muli %row, %k3 : index
{rounded_line}
{fixed_line}
    %at = arith.addi %gbase, %g3 : index
    // A relaxed atomic at the scope of the device: the sum needs no
    // order, and one of the system would wait for the host.
    %ati = arith.index_cast %at : index to i64
    %offset = arith.muli %ati, %eight : i64
    %address = arith.addi %gridbase, %offset : i64
    %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
{atomic_line}
  }}
}}""")

    zero = Body("      ")
    zero(f"""\
%none = arith.constant {"0 : i64" if fixed else "0.0 : !pme_real"}
memref.store %none, %grid[%item] : memref<?x{"i64" if fixed else "!pme_real"}, 1>""")
    name = "spread" if fixed else "spread_float"
    what = ("in fixed point, so that the sum does not depend on the order of\n"
            "// the threads (D70; the deterministic mode, D84)") if fixed else (
            "in !pme_real, with floating-point atomics, whose sum depends on\n"
            "// the order of the threads (the default mode, D84)")
    grid_type = "i64" if fixed else "!pme_real"
    return f"""
// Spreads the charges to `grid`, {what}.
func.func private @mdrt_gpu_pme_{name}(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %box: vector<3xf64>, %grid: memref<?x{grid_type}, 1>,
                                       %k1: index, %k2: index, %k3: index, %n: index) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %points = memref.dim %grid, %c0 : memref<?x{grid_type}, 1>
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %spread_lanes = arith.constant PME_ORDER : index
  %spread = arith.muli %count, %spread_lanes : index
{launch(zero.text(), "%points")}{launch(body.text(), "%spread")}  return
}}
"""


def real():
    body = Body("      ")
    body("""\
%inverse = arith.constant 9.094947017729282e-13 : !pme_real
%fixed = memref.load %grid[%item] : memref<?xi64, 1>
%value = arith.sitofp %fixed : i64 to !pme_real
%scaled = arith.mulf %value, %inverse : !pme_real
memref.store %scaled, %real[%item] : memref<?x!pme_real, 1>""")
    return f"""
// The grid in !pme_real, from fixed point.
func.func private @mdrt_gpu_pme_real(%grid: memref<?xi64, 1>, %real: memref<?x!pme_real, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %points = memref.dim %grid, %c0 : memref<?xi64, 1>
{launch(body.text(), "%points")}  return
}}
"""


def wave(body, p, k, count, length, real="f64"):
    """The wave number of the point `k` of `count` along an edge, signed,
    over the edge; `length` is one over the edge, of the type `real`."""
    body(f"""\
%{p}half = arith.divui {count}, %cc2 : index
%{p}ki = arith.index_cast {k} : index to i64
%{p}ni = arith.index_cast {count} : index to i64
%{p}beyond = arith.cmpi ugt, {k}, %{p}half : index
%{p}shifted = arith.subi %{p}ki, %{p}ni : i64
%{p}signed = arith.select %{p}beyond, %{p}shifted, %{p}ki : i64
%{p}sf = arith.sitofp %{p}signed : i64 to {real}
%{p}m = arith.mulf %{p}sf, {length} : {real}""")
    return f"%{p}m"


INFLUENCE_ORTHORHOMBIC = """\
%tbx1 = arith.addi %a, %k1 : index
%tbx2 = arith.addi %tbx1, %k1 : index
%m1 = memref.load %tables[%a] : memref<?x!pme_real, 1>
%m1s = memref.load %tables[%tbx1] : memref<?x!pme_real, 1>
%t1 = memref.load %tables[%tbx2] : memref<?x!pme_real, 1>
%tby0 = arith.addi %ty0, %b : index
%tby1 = arith.addi %tby0, %k2 : index
%tby2 = arith.addi %tby1, %k2 : index
%m2 = memref.load %tables[%tby0] : memref<?x!pme_real, 1>
%m2s = memref.load %tables[%tby1] : memref<?x!pme_real, 1>
%t2 = memref.load %tables[%tby2] : memref<?x!pme_real, 1>
%tbz0 = arith.addi %tz0, %z : index
%tbz1 = arith.addi %tbz0, %k3 : index
%tbz2 = arith.addi %tbz1, %k3 : index
%m3 = memref.load %tables[%tbz0] : memref<?x!pme_real, 1>
%m3s = memref.load %tables[%tbz1] : memref<?x!pme_real, 1>
%t3 = memref.load %tables[%tbz2] : memref<?x!pme_real, 1>
%m12 = arith.addf %m1s, %m2s : !pme_real
%msqr = arith.addf %m12, %m3s : !pme_real
%origin = arith.cmpf oeq, %msqr, %rzero : !pme_real
%safe = arith.select %origin, %rone, %msqr : !pme_real
%inverse = arith.divf %rone, %safe : !pme_real
// The influence function from the tables of the edges (D104): each factor
// computed in f64 and rounded once.
%tt12 = arith.mulf %t1, %t2 : !pme_real
%tt123 = arith.mulf %tt12, %t3 : !pme_real
%bc0 = arith.mulf %tt123, %inverse : !pme_real
%bc = arith.select %origin, %rzero, %bc0 : !pme_real
"""

# A triclinic cell: the tables hold the signed numbers n of the points and
# the factors of the B-splines; k = H⁻¹ n, and the Gaussian is computed at
# each point, since k² is not a sum of a term for each axis.
INFLUENCE_TRICLINIC = """\
%tbx2 = arith.addi %a, %k1 : index
%tbx2b = arith.addi %tbx2, %k1 : index
%n1 = memref.load %tables[%a] : memref<?x!pme_real, 1>
%t1 = memref.load %tables[%tbx2b] : memref<?x!pme_real, 1>
%tby0 = arith.addi %ty0, %b : index
%tby1 = arith.addi %tby0, %k2 : index
%tby2 = arith.addi %tby1, %k2 : index
%n2 = memref.load %tables[%tby0] : memref<?x!pme_real, 1>
%t2 = memref.load %tables[%tby2] : memref<?x!pme_real, 1>
%tbz0 = arith.addi %tz0, %z : index
%tbz1 = arith.addi %tbz0, %k3 : index
%tbz2 = arith.addi %tbz1, %k3 : index
%n3 = memref.load %tables[%tbz0] : memref<?x!pme_real, 1>
%t3 = memref.load %tables[%tbz2] : memref<?x!pme_real, 1>
%m1 = arith.mulf %h00r, %n1 : !pme_real
%m2a = arith.mulf %h10r, %n1 : !pme_real
%m2b = arith.mulf %h11r, %n2 : !pme_real
%m2 = arith.addf %m2a, %m2b : !pme_real
%m3a = arith.mulf %h20r, %n1 : !pme_real
%m3b = arith.mulf %h21r, %n2 : !pme_real
%m3c = arith.mulf %h22r, %n3 : !pme_real
%m3ab = arith.addf %m3a, %m3b : !pme_real
%m3 = arith.addf %m3ab, %m3c : !pme_real
%m1s = arith.mulf %m1, %m1 : !pme_real
%m2s = arith.mulf %m2, %m2 : !pme_real
%m3s = arith.mulf %m3, %m3 : !pme_real
%m12 = arith.addf %m1s, %m2s : !pme_real
%msqr = arith.addf %m12, %m3s : !pme_real
%origin = arith.cmpf oeq, %msqr, %rzero : !pme_real
%safe = arith.select %origin, %rone, %msqr : !pme_real
%inverse = arith.divf %rone, %safe : !pme_real
%gk = arith.mulf %gaussr, %msqr : !pme_real
%ngk = arith.negf %gk : !pme_real
%ek = math.exp %ngk : !pme_real
%tt12 = arith.mulf %t1, %t2 : !pme_real
%tt123 = arith.mulf %tt12, %t3 : !pme_real
%tte = arith.mulf %tt123, %ek : !pme_real
%bc0 = arith.mulf %tte, %inverse : !pme_real
%bc = arith.select %origin, %rzero, %bc0 : !pme_real
"""


# The influence function of the dispersion from the square of the wave
# vector (D162): the factors of the axes times
#   F(b) = (1 - 2b^2) exp(-b^2) + 2 sqrt(pi) b^3 erfc(b),  b = pi |m| / beta,
# [Essmann1995], m = 0 included, and %vb, which the virial takes:
# the factors times 6 pi^2 / beta^2 (exp(-b^2) - sqrt(pi) b erfc(b)).
INFLUENCE_DISPERSION = """\
%dmabs = math.sqrt %msqr : !pme_real
%dbd = arith.mulf %pibr, %dmabs : !pme_real
%dbd2 = arith.mulf %dbd, %dbd : !pme_real
%dnbd2 = arith.negf %dbd2 : !pme_real
%debd = math.exp %dnbd2 : !pme_real
%derfc = math.erfc %dbd : !pme_real
%dspb = arith.mulf %sqrtpir, %dbd : !pme_real
%dsbd = arith.mulf %dspb, %derfc : !pme_real
%dtwo = arith.constant 2.0 : !pme_real
%dtwob2 = arith.mulf %dtwo, %dbd2 : !pme_real
%domt = arith.subf %rone, %dtwob2 : !pme_real
%dfa = arith.mulf %domt, %debd : !pme_real
%dfb = arith.mulf %dtwob2, %dsbd : !pme_real
%dfd = arith.addf %dfa, %dfb : !pme_real
%tt12 = arith.mulf %t1, %t2 : !pme_real
%tt123 = arith.mulf %tt12, %t3 : !pme_real
%bc = arith.mulf %tt123, %dfd : !pme_real
%dvd0 = arith.subf %debd, %dsbd : !pme_real
%dvd1 = arith.mulf %sixgaussr, %dvd0 : !pme_real
%vb = arith.mulf %tt123, %dvd1 : !pme_real
"""


def influence():
    """The influence function at the point (%a, %b, %z) of the half-complex
    transform, %bc, and the wave vector %m1, %m2, %m3 with its square %msqr
    and its inverse %inverse, which the virial takes; of the dispersion,
    %vb instead of the inverse."""
    text = INFLUENCE_TRICLINIC if TILTED else INFLUENCE_ORTHORHOMBIC
    if DISPERSION:
        text = text[:text.index("%origin = ")] + INFLUENCE_DISPERSION
    return text.rstrip("\n")


def dispersion_constants():
    """The constants of the influence function of the dispersion, after
    %beta, %pi, and %gauss: pi / beta, sqrt(pi), and 6 pi^2 / beta^2."""
    if not DISPERSION:
        return ""
    return """\
  %pib = arith.divf %pi, %beta : f64
  %pibr = PME_F64_TO_REAL %pib : f64 to !pme_real
  %sqrtpi = arith.constant 1.7724538509055159 : f64
  %sqrtpir = PME_F64_TO_REAL %sqrtpi : f64 to !pme_real
  %six = arith.constant 6.0 : f64
  %sixgauss = arith.mulf %six, %gauss : f64
  %sixgaussr = PME_F64_TO_REAL %sixgauss : f64 to !pme_real
"""


# The prefactor of the energy: f / (pi V) of the Coulomb sum, and
# -f pi^{3/2} beta^3 / (3V) of the dispersion (D162).
PREFACTOR_COULOMB = "  %prefactor = arith.divf %coulomb, %piv : f64\n"
PREFACTOR_DISPERSION = """\
  %pi32 = arith.constant 5.568327996831708 : f64
  %beta3 = arith.mulf %beta2, %beta : f64
  %pb3 = arith.mulf %pi32, %beta3 : f64
  %three = arith.constant 3.0 : f64
  %v3 = arith.mulf %three, %volume : f64
  %pd0 = arith.divf %pb3, %v3 : f64
  %pdc = arith.mulf %pd0, %coulomb : f64
  %prefactor = arith.negf %pdc : f64
"""


def prefactor():
    return (PREFACTOR_DISPERSION if DISPERSION else PREFACTOR_COULOMB) + dispersion_constants()


def named(text):
    """The functions of the dispersion are named with `_dispersion`."""
    if not DISPERSION:
        return text
    return re.sub(r"func\.func private @mdrt_gpu_pme_(\w+)\(",
                  r"func.func private @mdrt_gpu_pme_\1_dispersion(", text)


VIRIAL_COULOMB = """\
%sum = arith.addf %inverse, %gaussr : !pme_real
%factor0 = arith.mulf %rtwo, %sum : !pme_real
%factor = arith.select %origin, %rzero, %factor0 : !pme_real
%ef = arith.mulf %em, %factor : !pme_real
"""
VIRIAL_DISPERSION = """\
%hwv = arith.mulf %hw, %vb : !pme_real
%ef = arith.mulf %hwv, %g2 : !pme_real
"""


def convolve():
    """The product with the influence function where the energy and the
    virial are needed (D104): a thread for points of the grid, as `scale`
    has them, computing the influence function in !pme_real as `scale`
    does, so that the forces are those of the steps without the virial.
    A block of 128 threads takes a run of points, `per` a thread, 128
    apart, sums the energy and the six elements of the virial of its
    threads by the tree of gpu.all_reduce in !pme_real, and stores them in
    f64; one block adds the blocks in f64, a thread every 128th block and
    then the tree, and the host copies the seven sums. The order of every
    sum is fixed by the size of the grid alone."""
    body = Body("    ")
    body("""\
%cc0 = arith.constant 0 : index
%cc1 = arith.constant 1 : index
%cc2 = arith.constant 2 : index
%rzero = arith.constant 0.0 : !pme_real
%rone = arith.constant 1.0 : !pme_real
%rhalf = arith.constant 0.5 : !pme_real
%rtwo = arith.constant 2.0 : !pme_real
%run = arith.muli %bx, %span : index
%e, %v00, %v01, %v02, %v11, %v12, %v22 = scf.for %c_ = %cc0 to %per step %cc1
    iter_args(%e0 = %rzero, %a00 = %rzero, %a01 = %rzero, %a02 = %rzero,
              %a11 = %rzero, %a12 = %rzero, %a22 = %rzero)
    -> (!pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real) {
  %c128_ = arith.muli %c_, %c128 : index
  %run_c = arith.addi %run, %c128_ : index
  %item = arith.addi %run_c, %tx : index
  %inside = arith.cmpi ult, %item, %points : index
  %sums:7 = scf.if %inside -> (!pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real) {
    %item32 = arith.index_cast %item : index to i32
    %row32 = arith.divui %item32, %depth32 : i32
    %z32 = arith.remui %item32, %depth32 : i32
    %a32 = arith.divui %row32, %k2_32 : i32
    %b32 = arith.remui %row32, %k2_32 : i32
    %z = arith.index_cast %z32 : i32 to index
    %a = arith.index_cast %a32 : i32 to index
    %b = arith.index_cast %b32 : i32 to index""")
    inner = Body("    ")
    inner(f"""\
{influence()}
""")
    m1, m2 = "%m1", "%m2"
    inner(f"""\
%re_at = arith.muli %item, %cc2 : index
%im_at = arith.addi %re_at, %cc1 : index
%re = memref.load %c[%re_at] : memref<?x!pme_real, 1>
%im = memref.load %c[%im_at] : memref<?x!pme_real, 1>
// The energy and the virial of the point: the points of the half-complex
// transform stand for two but at z = 0 and, for an even k3, at k3 / 2.
%re2 = arith.mulf %re, %re : !pme_real
%im2 = arith.mulf %im, %im : !pme_real
%g2 = arith.addf %re2, %im2 : !pme_real
%first = arith.cmpi eq, %z, %cc0 : index
%middle = arith.cmpi eq, %z, %half : index
%middle_even = arith.andi %middle, %even : i1
%single = arith.ori %first, %middle_even : i1
%hw = arith.select %single, %rhalf, %rone : !pme_real
%hwb = arith.mulf %hw, %bc : !pme_real
%em = arith.mulf %hwb, %g2 : !pme_real
{VIRIAL_DISPERSION if DISPERSION else VIRIAL_COULOMB}%p11 = arith.mulf {m1}, {m1} : !pme_real
%p12 = arith.mulf {m1}, {m2} : !pme_real
%p13 = arith.mulf {m1}, %m3 : !pme_real
%p22 = arith.mulf {m2}, {m2} : !pme_real
%p23 = arith.mulf {m2}, %m3 : !pme_real
%p33 = arith.mulf %m3, %m3 : !pme_real
%t11 = arith.mulf %ef, %p11 : !pme_real
%t12 = arith.mulf %ef, %p12 : !pme_real
%t13 = arith.mulf %ef, %p13 : !pme_real
%t22 = arith.mulf %ef, %p22 : !pme_real
%t23 = arith.mulf %ef, %p23 : !pme_real
%t33 = arith.mulf %ef, %p33 : !pme_real
%d11 = arith.subf %em, %t11 : !pme_real
%d22 = arith.subf %em, %t22 : !pme_real
%d33 = arith.subf %em, %t33 : !pme_real
%n00 = arith.addf %a00, %d11 : !pme_real
%n01 = arith.subf %a01, %t12 : !pme_real
%n02 = arith.subf %a02, %t13 : !pme_real
%n11 = arith.addf %a11, %d22 : !pme_real
%n12 = arith.subf %a12, %t23 : !pme_real
%n22 = arith.addf %a22, %d33 : !pme_real
%ne = arith.addf %e0, %em : !pme_real
%reb = arith.mulf %re, %bc : !pme_real
%imb = arith.mulf %im, %bc : !pme_real
memref.store %reb, %c[%re_at] : memref<?x!pme_real, 1>
memref.store %imb, %c[%im_at] : memref<?x!pme_real, 1>
scf.yield %ne, %n00, %n01, %n02, %n11, %n12, %n22
    : !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real""")
    body(inner.text().rstrip("\n"))
    body("""\
  } else {
    scf.yield %e0, %a00, %a01, %a02, %a11, %a12, %a22
        : !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real
  }
  scf.yield %sums#0, %sums#1, %sums#2, %sums#3, %sums#4, %sums#5, %sums#6
      : !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real, !pme_real
}
%out = arith.muli %bx, %c10 : index
%lead = arith.cmpi eq, %tx, %cc0 : index""")
    for index, name in enumerate(["%e", "%v00", "%v01", "%v02", "%v11", "%v12", "%v22"]):
        body(f"""\
%r{index} = gpu.all_reduce add {name} uniform {{
}} : (!pme_real) -> !pme_real
%r{index}w = PME_REAL_TO_F64 %r{index} : !pme_real to f64""")
    body("scf.if %lead {")
    for index in range(7):
        body(f"""\
  %oc{index} = arith.constant {index} : index
  %o{index} = arith.addi %out, %oc{index} : index
  memref.store %r{index}w, %rows[%o{index}] : memref<?xf64, 1>""")
    body("}")

    total = Body("    ")
    total("""\
%zero_d = arith.constant 0.0 : f64
%cc0 = arith.constant 0 : index
%s:7 = scf.for %blk = %tx to %blocks step %c128
    iter_args(%q0 = %zero_d, %q1 = %zero_d, %q2 = %zero_d, %q3 = %zero_d,
              %q4 = %zero_d, %q5 = %zero_d, %q6 = %zero_d)
    -> (f64, f64, f64, f64, f64, f64, f64) {
  %at = arith.muli %blk, %c10 : index""")
    for index in range(7):
        total(f"""\
  %tc{index} = arith.constant {index} : index
  %ta{index} = arith.addi %at, %tc{index} : index
  %tv{index} = memref.load %rows[%ta{index}] : memref<?xf64, 1>
  %tn{index} = arith.addf %q{index}, %tv{index} : f64""")
    total("""\
  scf.yield %tn0, %tn1, %tn2, %tn3, %tn4, %tn5, %tn6 : f64, f64, f64, f64, f64, f64, f64
}
%lead = arith.cmpi eq, %tx, %cc0 : index""")
    for index in range(7):
        total(f"""\
%u{index} = gpu.all_reduce add %s#{index} uniform {{
}} : (f64) -> f64""")
    total("scf.if %lead {")
    for index in range(7):
        total(f"""\
  %uc{index} = arith.constant {index} : index
  memref.store %u{index}, %rows[%uc{index}] : memref<?xf64, 1>""")
    total("}")
    return f"""
// Multiplies the half-complex transform `c` by the influence function, which
// it computes from the factors of the edges in `moduli` and the cell, and
// returns the energy and the virial, as @mdrt.pme_convolve does: see
// convolve in the script (D104). `rows` holds the sums of the blocks, ten
// slots each, then the seven sums at its start.
func.func private @mdrt_gpu_pme_convolve(%c: memref<?x!pme_real, 1>, %tables: memref<?x!pme_real, 1>,
                                         %rows: memref<?xf64, 1>, %box: vector<3xf64>,
                                         %beta: f64, %coulomb: f64,
                                         %k1: index, %k2: index, %k3: index)
    -> (f64, vector<9xf64>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  %c3t = arith.constant 3 : index
  %c10 = arith.constant 10 : index
  %c127 = arith.constant 127 : index
  %c128 = arith.constant 128 : index
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
{prefactor()}  %gaussr = PME_F64_TO_REAL %gauss : f64 to !pme_real
  %prefactorr = PME_F64_TO_REAL %prefactor : f64 to !pme_real
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %ilxr = PME_F64_TO_REAL %ilx : f64 to !pme_real
  %ilyr = PME_F64_TO_REAL %ily : f64 to !pme_real
  %ilzr = PME_F64_TO_REAL %ilz : f64 to !pme_real
  %count = arith.muli %k1, %k2 : index
  %ty0 = arith.muli %k1, %c3t : index
  %k2_3 = arith.muli %k2, %c3t : index
  %tz0 = arith.addi %ty0, %k2_3 : index
  %half = arith.divui %k3, %c2 : index
  %depth = arith.addi %half, %c1 : index
  %odd = arith.remui %k3, %c2 : index
  %even = arith.cmpi eq, %odd, %c0 : index
  %points = arith.muli %count, %depth : index
  %depth32 = arith.index_cast %depth : index to i32
  %k2_32 = arith.index_cast %k2 : index to i32
  // Points a thread: as many as keep the blocks within the rows, at most
  // one for each row of the grid.
  %depth127 = arith.addi %depth, %c127 : index
  %per = arith.divui %depth127, %c128 : index
  %span = arith.muli %per, %c128 : index
  %points_up = arith.addi %points, %span : index
  %points_up1 = arith.subi %points_up, %c1 : index
  %blocks = arith.divui %points_up1, %span : index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
{body.text()}    gpu.terminator
  }}
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %c1, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
{total.text()}    gpu.terminator
  }}
  // The energy and the six components of the virial that the total wrote:
  // a longer copy read values that no kernel wrote (initcheck).
  %host = memref.alloc() : memref<7xf64>
  %rows7 = memref.subview %rows[0] [7] [1] : memref<?xf64, 1> to memref<7xf64, strided<[1]>, 1>
  %t0 = gpu.wait async
  %t1 = gpu.memcpy async [%t0] %host, %rows7 : memref<7xf64>, memref<7xf64, strided<[1]>, 1>
  gpu.wait [%t1]
  %e = memref.load %host[%c0] : memref<7xf64>
  %c3 = arith.constant 3 : index
  %c4 = arith.constant 4 : index
  %c5 = arith.constant 5 : index
  %c6 = arith.constant 6 : index
  %w00 = memref.load %host[%c1] : memref<7xf64>
  %w01 = memref.load %host[%c2] : memref<7xf64>
  %w02 = memref.load %host[%c3] : memref<7xf64>
  %w11 = memref.load %host[%c4] : memref<7xf64>
  %w12 = memref.load %host[%c5] : memref<7xf64>
  %w22 = memref.load %host[%c6] : memref<7xf64>
  memref.dealloc %host : memref<7xf64>
  %virial = vector.from_elements %w00, %w01, %w02, %w01, %w11, %w12, %w02, %w12, %w22 : vector<9xf64>
  return %e, %virial : f64, vector<9xf64>
}}
"""


TABLE_LENGTH_ORTHORHOMBIC = """\
%l0 = arith.select %on_y, %ily, %ilx : f64
%l = arith.select %on_z, %ilz, %l0 : f64
"""
TABLE_LENGTH_TRICLINIC = """\
%l = arith.constant 1.0 : f64
"""
TABLE_FACTOR_ORTHORHOMBIC = """\
%gm = arith.mulf %gauss, %m2 : f64
%ngm = arith.negf %gm : f64
%ex = math.exp %ngm : f64
%mod = memref.load %moduli[%axis, %k] : memref<?x?xf64, 1>
%factor0 = arith.mulf %ex, %mod : f64
"""
TABLE_FACTOR_TRICLINIC = """\
%mod = memref.load %moduli[%axis, %k] : memref<?x?xf64, 1>
%fzero = arith.constant 0.0 : f64
%factor0 = arith.addf %mod, %fzero : f64
"""


def tables():
    """The factors of the influence function along each edge (D104), for
    `scale` and `convolve`: for each point k of an edge of K points, the
    wave number m (signed, over the edge), m^2, and exp(-pi^2 m^2 /
    beta^2) times the factor of the B-splines of the edge, with the
    prefactor of the energy along x; computed in f64 and rounded once to
    !pme_real. Edge a holds 3 K_a values from 3 times the points of the
    edges before it: m, then m^2, then the factor."""
    body = Body("      ")
    body(f"""\
%c0t = arith.constant 0 : index
%c1t = arith.constant 1 : index
%c2t = arith.constant 2 : index
%k12 = arith.addi %k1, %k2 : index
%on_y = arith.cmpi uge, %item, %k1 : index
%on_z = arith.cmpi uge, %item, %k12 : index
%axis0 = arith.select %on_y, %c1t, %c0t : index
%axis = arith.select %on_z, %c2t, %axis0 : index
%from0 = arith.select %on_y, %k1, %c0t : index
%from = arith.select %on_z, %k12, %from0 : index
%kk0 = arith.select %on_y, %k2, %k1 : index
%kk = arith.select %on_z, %k3, %kk0 : index
{TABLE_LENGTH_TRICLINIC if TILTED else TABLE_LENGTH_ORTHORHOMBIC}%k = arith.subi %item, %from : index
%half = arith.divui %kk, %c2t : index
%ki = arith.index_cast %k : index to i64
%ni = arith.index_cast %kk : index to i64
%beyond = arith.cmpi ugt, %k, %half : index
%shifted = arith.subi %ki, %ni : i64
%signed = arith.select %beyond, %shifted, %ki : i64
%sf = arith.sitofp %signed : i64 to f64
%m = arith.mulf %sf, %l : f64
%m2 = arith.mulf %m, %m : f64
{TABLE_FACTOR_TRICLINIC if TILTED or DISPERSION else TABLE_FACTOR_ORTHORHOMBIC}%first_axis = arith.cmpi eq, %axis, %c0t : index
%scaled = arith.mulf %factor0, %prefactor : f64
%factor = arith.select %first_axis, %scaled, %factor0 : f64
%tstart = arith.muli %from, %c3 : index
%at0 = arith.addi %tstart, %k : index
%at1 = arith.addi %at0, %kk : index
%at2 = arith.addi %at1, %kk : index
%mr = PME_F64_TO_REAL %m : f64 to !pme_real
%m2r = PME_F64_TO_REAL %m2 : f64 to !pme_real
%fr = PME_F64_TO_REAL %factor : f64 to !pme_real
memref.store %mr, %tables[%at0] : memref<?x!pme_real, 1>
memref.store %m2r, %tables[%at1] : memref<?x!pme_real, 1>
memref.store %fr, %tables[%at2] : memref<?x!pme_real, 1>""")
    return f"""
// The factors of the influence function along the edges, for
// @mdrt_gpu_pme_scale and @mdrt_gpu_pme_convolve: see tables in the script.
func.func private @mdrt_gpu_pme_tables(%moduli: memref<?x?xf64, 1>, %tables: memref<?x!pme_real, 1>,
                                       %box: vector<3xf64>, %beta: f64, %coulomb: f64,
                                       %k1: index, %k2: index, %k3: index) {{
  %c1 = arith.constant 1 : index
  %c3 = arith.constant 3 : index
  %c128 = arith.constant 128 : index
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
{prefactor()}  %k12a = arith.addi %k1, %k2 : index
  %entries = arith.addi %k12a, %k3 : index
{launch(body.text(), "%entries")}  return
}}
"""


def scale():
    body = Body("      ")
    body("""\
%cc0 = arith.constant 0 : index
%cc1 = arith.constant 1 : index
%cc2 = arith.constant 2 : index
%kzero = arith.constant 0.0 : f64
%kone = arith.constant 1.0 : f64
// The point, in i32 (D85): a division of 64-bit integers is a long
// sequence of instructions on a device.
%item32 = arith.index_cast %item : index to i32
%row32 = arith.divui %item32, %depth32 : i32
%z32 = arith.remui %item32, %depth32 : i32
%a32 = arith.divui %row32, %k2_32 : i32
%b32 = arith.remui %row32, %k2_32 : i32
%z = arith.index_cast %z32 : i32 to index
%a = arith.index_cast %a32 : i32 to index
%b = arith.index_cast %b32 : i32 to index""")
    body(f"""\
%rzero = arith.constant 0.0 : !pme_real
%rone = arith.constant 1.0 : !pme_real
{influence()}
%re_at = arith.muli %item, %cc2 : index
%im_at = arith.addi %re_at, %cc1 : index
%re = memref.load %c[%re_at] : memref<?x!pme_real, 1>
%im = memref.load %c[%im_at] : memref<?x!pme_real, 1>
%reb = arith.mulf %re, %bc : !pme_real
%imb = arith.mulf %im, %bc : !pme_real
memref.store %reb, %c[%re_at] : memref<?x!pme_real, 1>
memref.store %imb, %c[%im_at] : memref<?x!pme_real, 1>""")
    return f"""
// Multiplies the half-complex transform `c` by the influence function, as
// @mdrt_gpu_pme_convolve does, where neither the energy nor the virial is
// needed: a thread for each point, and nothing for the host to wait for.
func.func private @mdrt_gpu_pme_scale(%c: memref<?x!pme_real, 1>, %tables: memref<?x!pme_real, 1>,
                                      %box: vector<3xf64>, %beta: f64, %coulomb: f64,
                                      %k1: index, %k2: index, %k3: index) {{
  %c1 = arith.constant 1 : index
  %c2 = arith.constant 2 : index
  %c128 = arith.constant 128 : index
  %pi2 = arith.constant 9.869604401089358 : f64
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %beta2 = arith.mulf %beta, %beta : f64
  %gauss = arith.divf %pi2, %beta2 : f64
  %pi = arith.constant 3.141592653589793 : f64
  %lxy = arith.mulf %lx, %ly : f64
  %volume = arith.mulf %lxy, %lz : f64
  %piv = arith.mulf %pi, %volume : f64
{prefactor()}  %gaussr = PME_F64_TO_REAL %gauss : f64 to !pme_real
  %prefactorr = PME_F64_TO_REAL %prefactor : f64 to !pme_real
  %rows = arith.muli %k1, %k2 : index
  %c3t = arith.constant 3 : index
  %ty0 = arith.muli %k1, %c3t : index
  %k2_3 = arith.muli %k2, %c3t : index
  %tz0 = arith.addi %ty0, %k2_3 : index
  %half = arith.divui %k3, %c2 : index
  %depth = arith.addi %half, %c1 : index
  %points = arith.muli %rows, %depth : index
  %depth32 = arith.index_cast %depth : index to i32
  %k2_32 = arith.index_cast %k2 : index to i32
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %ilxr = PME_F64_TO_REAL %ilx : f64 to !pme_real
  %ilyr = PME_F64_TO_REAL %ily : f64 to !pme_real
  %ilzr = PME_F64_TO_REAL %ilz : f64 to !pme_real
{launch(body.text(), "%points")}  return
}}
"""


COMPONENTS = 6  # the first points (3), the fractions (3)


def weights_kernels():
    """The spreading of order 4 from the places of the particles, as
    scripts/experiments/neighbor-structures/spread.cu measured it: a kernel
    places each particle, a thread a particle, into arrays by component
    (component c of particle i at c n + i: the first points along x, y, z
    as values, then the fractions along x, y, z; the weights of the splines
    come from the fractions in closed form where they are used, D109, so
    that 6 values a particle are written and read, not 18); the charges
    are added with a warp a particle into a grid of bricks of
    4 x 4 points in x-y, z inside them, so that the points of a particle
    at one z are 16 consecutive values of at most 4 bricks; a kernel copies
    the bricks into the grid of the transform. The gathering computes its
    splines again: read from 27 arrays with their slopes, it took 155 to
    158 us on Cellulose against 127 to 134 (2026-10-01); from the first
    points and the fractions, see gather_weights."""
    # The weights.
    w = Body("      ")
    w("""\
%i = arith.addi %item, %c0 : index
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
%order = arith.constant 4 : index""")
    places = [(f"%{t}p", length) for t, length in zip("xyz", ("%ilx", "%ily", "%ilz"))]
    if TILTED:
        for axis, t in enumerate("xyz"):
            w(f"""\
%{t}c = arith.constant {axis} : index
%{t}s = memref.load %x[%i, %{t}c] : memref<?x3x!pme_pos, 1>
%{t}p = PME_EXTEND_POS %{t}s : !pme_pos to f64""")
        places = fractions(w, "%xp", "%yp", "%zp")
    for axis, ((coordinate, length), k) in enumerate(zip(places, ("%k1", "%k2", "%k3"))):
        t = "xyz"[axis]
        if not TILTED:
            w(f"""\
%{t}c = arith.constant {axis} : index
%{t}s = memref.load %x[%i, %{t}c] : memref<?x3x!pme_pos, 1>
%{t}p = PME_EXTEND_POS %{t}s : !pme_pos to f64
""")
        start, frac = place(w, f"p{t}_", coordinate, length, k, "%order")
        w(f"""\
%{t}fc = arith.constant {3 + axis} : index
%{t}fn = arith.muli %n_all, %{t}fc : index
%{t}fat = arith.addi %{t}fn, %i : index
memref.store {frac}, %weights[%{t}fat] : memref<?x!pme_real, 1>
%{t}start_i = arith.index_cast {start} : index to i32
%{t}start_r = arith.sitofp %{t}start_i : i32 to !pme_real
%{t}sn = arith.muli %n_all, %{t}c : index
%{t}sat = arith.addi %{t}sn, %i : index
memref.store %{t}start_r, %weights[%{t}sat] : memref<?x!pme_real, 1>""")


    # The additions into the bricks, counting in i32 (D85): a particle, a
    # point, and a brick of the grid are numbered in 32 bits, and the
    # address in bytes in 64.
    a = Body("      ")
    a("""\
%c32i = arith.constant 32 : index
%i = arith.divui %item, %c32i : index
%item32 = arith.index_cast %item : index to i32
%n32 = arith.index_cast %n_all : index to i32
%i32 = arith.index_cast %i : index to i32
%t32 = arith.constant 32 : i32
%t2 = arith.constant 2 : i32
%t3 = arith.constant 3 : i32
%t4 = arith.constant 4 : i32
%t7 = arith.constant 7 : i32
%t11 = arith.constant 11 : i32
%t16 = arith.constant 16 : i32
%lane = arith.remui %item32, %t32 : i32
%xa = arith.remui %lane, %t4 : i32
%lane4 = arith.divui %lane, %t4 : i32
%yb = arith.remui %lane4, %t4 : i32
%zc = arith.divui %lane, %t16 : i32
%zc2 = arith.addi %zc, %t2 : i32
%k1t = arith.index_cast %k1 : index to i32
%k2t = arith.index_cast %k2 : index to i32
%k3t = arith.index_cast %k3 : index to i32
%b2t = arith.index_cast %b2 : index to i32
%qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
%qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real""")
    def load(name, component):
        a(f"""\
%{name}_n = arith.muli %n32, {component} : i32
%{name}_at32 = arith.addi %{name}_n, %i32 : i32
%{name}_at = arith.index_cast %{name}_at32 : i32 to index
%{name} = memref.load %weights[%{name}_at] : memref<?x!pme_real, 1>""")
    for axis, t in enumerate("xyz"):
        a(f"%t{axis}c = arith.constant {axis} : i32")
        load(f"st{t}_r", f"%t{axis}c")
        a(f"%st{t} = arith.fptosi %st{t}_r : !pme_real to i32")
    # The weights of order 4 from the fractions, in closed form (D109): the
    # recursion of the splines gives, for a fraction w, (1 - w)^3 / 6,
    # (3 w^3 - 6 w^2 + 4) / 6, (-3 w^3 + 3 w^2 + 3 w + 1) / 6, w^3 / 6 at
    # the points 0 to 3 from the first; a lane takes the one of its point.
    for axis, t in enumerate("xyz"):
        a(f"%f{axis}c = arith.constant {3 + axis} : i32")
        load(f"fr{t}", f"%f{axis}c")
    a("""\
%w_sixth = arith.constant 0.16666666666666666 : !pme_real
%w_one = arith.constant 1.0 : !pme_real
%w_three = arith.constant 3.0 : !pme_real
%w_four = arith.constant 4.0 : !pme_real
%w_six = arith.constant 6.0 : !pme_real
%w_zero32 = arith.constant 0 : i32
%w_one32 = arith.constant 1 : i32
%w_two32 = arith.constant 2 : i32""")
    def weight(name, frac, point):
        a(f"""\
%{name}_w2 = arith.mulf {frac}, {frac} : !pme_real
%{name}_w3 = arith.mulf %{name}_w2, {frac} : !pme_real
%{name}_omw = arith.subf %w_one, {frac} : !pme_real
%{name}_omw2 = arith.mulf %{name}_omw, %{name}_omw : !pme_real
%{name}_m0 = arith.mulf %{name}_omw2, %{name}_omw : !pme_real
%{name}_a1 = arith.mulf %w_three, %{name}_w3 : !pme_real
%{name}_b1 = arith.mulf %w_six, %{name}_w2 : !pme_real
%{name}_c1 = arith.subf %{name}_a1, %{name}_b1 : !pme_real
%{name}_m1 = arith.addf %{name}_c1, %w_four : !pme_real
%{name}_a2 = arith.mulf %w_three, %{name}_w2 : !pme_real
%{name}_b2 = arith.mulf %w_three, {frac} : !pme_real
%{name}_c2 = arith.subf %{name}_a2, %{name}_a1 : !pme_real
%{name}_d2 = arith.addf %{name}_c2, %{name}_b2 : !pme_real
%{name}_m2 = arith.addf %{name}_d2, %w_one : !pme_real
%{name}_is0 = arith.cmpi eq, {point}, %w_zero32 : i32
%{name}_is1 = arith.cmpi eq, {point}, %w_one32 : i32
%{name}_is2 = arith.cmpi eq, {point}, %w_two32 : i32
%{name}_s2 = arith.select %{name}_is2, %{name}_m2, %{name}_w3 : !pme_real
%{name}_s1 = arith.select %{name}_is1, %{name}_m1, %{name}_s2 : !pme_real
%{name}_s0 = arith.select %{name}_is0, %{name}_m0, %{name}_s1 : !pme_real
%{name} = arith.mulf %{name}_s0, %w_sixth : !pme_real""")
    weight("wxa", "%frx", "%xa")
    weight("wyb", "%fry", "%yb")
    weight("wz0", "%frz", "%zc")
    weight("wz1", "%frz", "%zc2")
    a("""\
%qx = arith.mulf %qi, %wxa : !pme_real
%qxy = arith.mulf %qx, %wyb : !pme_real
%g1s = arith.addi %stx, %xa : i32
%g1w = arith.subi %g1s, %k1t : i32
%g1over = arith.cmpi uge, %g1s, %k1t : i32
%g1 = arith.select %g1over, %g1w, %g1s : i32
%g2s = arith.addi %sty, %yb : i32
%g2w = arith.subi %g2s, %k2t : i32
%g2over = arith.cmpi uge, %g2s, %k2t : i32
%g2 = arith.select %g2over, %g2w, %g2s : i32
%bx1 = arith.divui %g1, %t4 : i32
%by1 = arith.divui %g2, %t4 : i32
%brow = arith.muli %bx1, %b2t : i32
%bxy = arith.addi %brow, %by1 : i32
%bxyz = arith.muli %bxy, %k3t : i32
%inx = arith.remui %g1, %t4 : i32
%iny = arith.remui %g2, %t4 : i32
%iny4 = arith.muli %iny, %t4 : i32
%inxy = arith.addi %iny4, %inx : i32
%bytes = arith.constant PME_REAL_BYTES : i64
%bindex = memref.extract_aligned_pointer_as_index %bricks : memref<?x!pme_real, 1> -> index
%bbase = arith.index_cast %bindex : index to i64
%h0 = arith.constant 0 : index
%h1 = arith.constant 1 : index
%h2 = arith.constant 2 : index
scf.for %h = %h0 to %h2 step %h1 {
  %second = arith.cmpi ne, %h, %h0 : index
  %c = arith.select %second, %zc2, %zc : i32
  %wz = arith.select %second, %wz1, %wz0 : !pme_real
  %g3s = arith.addi %stz, %c : i32
  %g3w = arith.subi %g3s, %k3t : i32
  %g3over = arith.cmpi uge, %g3s, %k3t : i32
  %g3 = arith.select %g3over, %g3w, %g3s : i32
  %slab = arith.addi %bxyz, %g3 : i32
  %slab16 = arith.muli %slab, %t16 : i32
  %at = arith.addi %slab16, %inxy : i32
  %ati = arith.extui %at : i32 to i64
  %offset = arith.muli %ati, %bytes : i64
  %address = arith.addi %bbase, %offset : i64
  %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
  %value = arith.mulf %qxy, %wz : !pme_real
  PME_ATOMIC_ADD %pointer, %value
}""")

    # The copy of the bricks into the grid of the transform, which leaves
    # them zero for the next spreading (D108): a block takes a brick and 32
    # of its slabs along z, reads its 512 values in order and writes zeros
    # back, and writes each of the 16 rows of the brick to the grid as 32
    # values along z in order, a warp a row, through a tile of the memory
    # of the block (rows of 17, so that the reads of a warp from the tile
    # hit different banks).
    copy = """\
  %c8 = arith.constant 8 : index
  %c17 = arith.constant 17 : index
  %c31 = arith.constant 31 : index
  %k3_31 = arith.addi %k3, %c31 : index
  %zchunks = arith.divui %k3_31, %c32 : index
  %copy_blocks = arith.muli %b12, %zchunks : index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %copy_blocks, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1)
             workgroup(%tile : memref<544x!pme_real, #gpu.address_space<workgroup>>) {
    %bxy = arith.divui %bx, %zchunks : index
    %zc = arith.remui %bx, %zchunks : index
    %z0 = arith.muli %zc, %c32 : index
    %bx1 = arith.divui %bxy, %b2 : index
    %by1 = arith.remui %bxy, %b2 : index
    %slab0 = arith.muli %bxy, %k3 : index
    %zero_r = arith.constant 0.0 : !pme_real
    %bytes = arith.constant PME_REAL_BYTES : i64
    %bindex = memref.extract_aligned_pointer_as_index %bricks : memref<?x!pme_real, 1> -> index
    %bbase = arith.index_cast %bindex : index to i64
    scf.for %j = %c0 to %c4 step %c1 {
      %j128 = arith.muli %j, %c128 : index
      %e = arith.addi %j128, %tx : index
      %zz = arith.divui %e, %c16 : index
      %inxy = arith.remui %e, %c16 : index
      %z = arith.addi %z0, %zz : index
      %in = arith.cmpi ult, %z, %k3 : index
      scf.if %in {
        %slab = arith.addi %slab0, %z : index
        %slab16 = arith.muli %slab, %c16 : index
        %at = arith.addi %slab16, %inxy : index
        %ati = arith.index_cast %at : index to i64
        %offset = arith.muli %ati, %bytes : i64
        %address = arith.addi %bbase, %offset : i64
        %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
        %value = llvm.load %pointer {alignment = PME_REAL_BYTES : i64} : !llvm.ptr<1> -> !pme_real
        %t17 = arith.muli %zz, %c17 : index
        %tat = arith.addi %t17, %inxy : index
        memref.store %value, %tile[%tat] : memref<544x!pme_real, #gpu.address_space<workgroup>>
      }
    }
    gpu.barrier
    // The slabs read are zero for the next spreading: written after every
    // read of the block, so that the reads are not held behind them.
    scf.for %j = %c0 to %c4 step %c1 {
      %j128 = arith.muli %j, %c128 : index
      %e = arith.addi %j128, %tx : index
      %zz = arith.divui %e, %c16 : index
      %inxy = arith.remui %e, %c16 : index
      %z = arith.addi %z0, %zz : index
      %in = arith.cmpi ult, %z, %k3 : index
      scf.if %in {
        %slab = arith.addi %slab0, %z : index
        %slab16 = arith.muli %slab, %c16 : index
        %at = arith.addi %slab16, %inxy : index
        %ati = arith.index_cast %at : index to i64
        %offset = arith.muli %ati, %bytes : i64
        %address = arith.addi %bbase, %offset : i64
        %pointer = llvm.inttoptr %address : i64 to !llvm.ptr<1>
        llvm.store %zero_r, %pointer {alignment = PME_REAL_BYTES : i64} : !pme_real, !llvm.ptr<1>
      }
    }
    // Each warp writes a row of the brick, its lanes the 32 values along
    // z in order; four rows a pass, four passes.
    %warp = arith.divui %tx, %c32 : index
    %lane = arith.remui %tx, %c32 : index
    %z = arith.addi %z0, %lane : index
    %in = arith.cmpi ult, %z, %k3 : index
    %t17 = arith.muli %lane, %c17 : index
    scf.for %pass = %c0 to %c4 step %c1 {
      %pass4 = arith.muli %pass, %c4 : index
      %r = arith.addi %pass4, %warp : index
      %inx = arith.remui %r, %c4 : index
      %iny = arith.divui %r, %c4 : index
      %g1a = arith.muli %bx1, %c4 : index
      %g1 = arith.addi %g1a, %inx : index
      %g2a = arith.muli %by1, %c4 : index
      %g2 = arith.addi %g2a, %iny : index
      %in1 = arith.cmpi ult, %g1, %k1 : index
      %in2 = arith.cmpi ult, %g2, %k2 : index
      %in12 = arith.andi %in1, %in2 : i1
      %writes = arith.andi %in12, %in : i1
      scf.if %writes {
        %row1 = arith.muli %g1, %k2 : index
        %row = arith.addi %row1, %g2 : index
        %gbase = arith.muli %row, %k3 : index
        %tat = arith.addi %t17, %r : index
        %value = memref.load %tile[%tat] : memref<544x!pme_real, #gpu.address_space<workgroup>>
        %gat = arith.addi %gbase, %z : index
        memref.store %value, %real[%gat] : memref<?x!pme_real, 1>
      }
    }
    gpu.terminator
  }
"""
    header = """\
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c3 = arith.constant 3 : index
  %c4 = arith.constant 4 : index
  %c16 = arith.constant 16 : index
  %c32 = arith.constant 32 : index
  %c128 = arith.constant 128 : index
  %n_all = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %k1u = arith.addi %k1, %c3 : index
  %b1 = arith.divui %k1u, %c4 : index
  %k2u = arith.addi %k2, %c3 : index
  %b2 = arith.divui %k2u, %c4 : index
  %b12 = arith.muli %b1, %b2 : index
  %b123 = arith.muli %b12, %k3 : index
  %brick_points = arith.muli %b123, %c16 : index
"""
    return f"""
// The weights of the particles for the spreading and the gathering of
// order 4: see weights_kernels in the script.
func.func private @mdrt_gpu_pme_weights(%x: memref<?x3x!pme_pos, 1>, %box: vector<3xf64>,
                                        %weights: memref<?x!pme_real, 1>,
                                        %k1: index, %k2: index, %k3: index) {{
{header}  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
{launch(w.text(), "%n_all")}  return
}}

// Adds the charges to `bricks`, which are zero, from the weights, and
// copies the bricks into `real`, the grid of the transform, leaving them
// zero again (D108; the buffer is zero when it is allocated).
func.func private @mdrt_gpu_pme_spread_bricks(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                              %weights: memref<?x!pme_real, 1>,
                                              %bricks: memref<?x!pme_real, 1>, %real: memref<?x!pme_real, 1>,
                                              %k1: index, %k2: index, %k3: index) {{
{header}  %lanes = arith.muli %n_all, %c32 : index
{launch(a.text(), "%lanes")}{copy}  return
}}
"""


def zero_text():
    zero = Body("      ")
    zero("""\
%none = arith.constant 0.0 : !pme_real
memref.store %none, %grid[%item] : memref<?x!pme_real, 1>""")
    return zero.text()


def gather(potential=False):
    """The forces; with `potential`, the potential of the grid at the
    particles in their place (the fourth result of md.reciprocal,
    D[tunable-gradient-pme]): the sum along x takes the weights of the
    splines, not their slopes, and the first thread of a particle stores
    it as one number."""
    body = Body("      ")
    # A thread for each particle and point of its splines along z, as the
    # spreading has them: the threads of a particle read neighboring points
    # of the grid at once, and their sums are added with shuffles.
    body("""\
%lanes = arith.constant PME_LANES : index
%i = arith.divui %item, %lanes : index
%j3 = arith.remui %item, %lanes : index""")
    sx, sy, sz = particle_prologue(body, slopes=True)
    w3 = pick(body, "w3p_", "%wz", "%j3")
    d3 = pick(body, "d3p_", "%dz", "%j3")
    body(f"""\
%gzero = arith.constant 0.0 : !pme_real
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
%g3s = arith.addi {sz}, %j3 : index
%g3w = arith.subi %g3s, %k3 : index
%g3over = arith.cmpi uge, %g3s, %k3 : index
%g3 = arith.select %g3over, %g3w, %g3s : index
%sumx, %sumy, %sumz = scf.for %j1 = %j0 to %order step %j1c
    iter_args(%ax = %gzero, %ay = %gzero, %az = %gzero) -> (!pme_real, !pme_real, !pme_real) {{
  %g1s = arith.addi {sx}, %j1 : index
  %g1w = arith.subi %g1s, %k1 : index
  %g1over = arith.cmpi uge, %g1s, %k1 : index
  %g1 = arith.select %g1over, %g1w, %g1s : index
  %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
  %d1 = memref.load %dx[%j1] : memref<8x!pme_real>
  %bx2, %by2, %bz2 = scf.for %j2 = %j0 to %order step %j1c
      iter_args(%cx = %ax, %cy = %ay, %cz = %az) -> (!pme_real, !pme_real, !pme_real) {{
    %g2s = arith.addi {sy}, %j2 : index
    %g2w = arith.subi %g2s, %k2 : index
    %g2over = arith.cmpi uge, %g2s, %k2 : index
    %g2 = arith.select %g2over, %g2w, %g2s : index
    %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
    %d2 = memref.load %dy[%j2] : memref<8x!pme_real>
    %row1 = arith.muli %g1, %k2 : index
    %row = arith.addi %row1, %g2 : index
    %gbase = arith.muli %row, %k3 : index
    %at = arith.addi %gbase, %g3 : index
    %p = memref.load %phi[%at] : memref<?x!pme_real, 1>
    %d1w2 = arith.mulf %d1, %w2 : !pme_real
    %w1d2 = arith.mulf %w1, %d2 : !pme_real
    %w1w2 = arith.mulf %w1, %w2 : !pme_real
    %px = arith.mulf {'%w1w2' if potential else '%d1w2'}, {w3} : !pme_real
    %py = arith.mulf %w1d2, {w3} : !pme_real
    %pz = arith.mulf %w1w2, {d3} : !pme_real
    %vx = arith.mulf %p, %px : !pme_real
    %vy = arith.mulf %p, %py : !pme_real
    %vz = arith.mulf %p, %pz : !pme_real
    %nx = arith.addf %cx, %vx : !pme_real
    %ny = arith.addf %cy, %vy : !pme_real
    %nz = arith.addf %cz, %vz : !pme_real
    scf.yield %nx, %ny, %nz : !pme_real, !pme_real, !pme_real
  }}
  scf.yield %bx2, %by2, %bz2 : !pme_real, !pme_real, !pme_real
}}""")
    if potential:
        comment = f"""
// The potential of the grid at the particles, as @mdrt.pme_potential gives
// it (the fourth result of md.reciprocal, D[tunable-gradient-pme]): the
// kernel of @mdrt_gpu_pme_gather{'_triclinic' if TILTED else ''} with the weights of the splines in place
// of their slopes along x, whose sum the first thread of a particle stores
// as one number. The sums along y and z of that kernel are computed and
// not used.
"""
    else:
        comment = """
// The forces, as @mdrt.pme_gather gives them: for each particle, a thread
// for each point of its splines along z (PME_LANES threads, the least power
// of 2 not below the order; those beyond it add zeros), and the first
// thread of a particle stores. The threads of a particle are consecutive
// and within a warp. The shuffles take every thread of the
// block, so the threads beyond the last particle compute too, from the
// last particle, and do not store.
"""
    name = "potential" if potential else "gather"
    shape = "?" if potential else "?x3"
    return comment + f"""\
func.func private @mdrt_gpu_pme_{name}(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                       %phi: memref<?x!pme_real, 1>, %box: vector<3xf64>,
                                       %k1: index, %k2: index, %k3: index, %n: index,
                                       %f: memref<{shape}x!pme_frc, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %k1i = arith.index_cast %k1 : index to i64
  %k2i = arith.index_cast %k2 : index to i64
  %k3i = arith.index_cast %k3 : index to i64
  %k1f = arith.sitofp %k1i : i64 to f64
  %k2f = arith.sitofp %k2i : i64 to f64
  %k3f = arith.sitofp %k3i : i64 to f64
  %rx = arith.divf %k1f, %lx : f64
  %ry = arith.divf %k2f, %ly : f64
  %rz = arith.divf %k3f, %lz : f64
  %rxr = PME_F64_TO_REAL %rx : f64 to !pme_real
  %ryr = PME_F64_TO_REAL %ry : f64 to !pme_real
  %rzr = PME_F64_TO_REAL %rz : f64 to !pme_real
  %unit = arith.constant 1.0 : f64
  %ilx = arith.divf %unit, %lx : f64
  %ily = arith.divf %unit, %ly : f64
  %ilz = arith.divf %unit, %lz : f64
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %lanes_all = arith.constant PME_LANES : index
  %points = arith.muli %count, %lanes_all : index
  %last = arith.subi %count, %c1 : index
{gather_launch(body.text(), potential)}  return
}}
"""


def gather_weights():
    """The gathering of order 4 where the weights kernel has placed the
    particles: the first points and the fractions are read from the
    weights (components 0 to 2 and 3 to 5, D109), the splines and their slopes
    computed again in !pme_real, and the points of the grid numbered in
    i32 (D102). The fractions are those that the spreading took, so the
    forces are those of the same splines."""
    body = Body("      ")
    body("""\
%lanes = arith.constant PME_LANES : index
%i = arith.divui %item, %lanes : index
%j3 = arith.remui %item, %lanes : index
%i0 = arith.constant 0 : index
%i1 = arith.constant 1 : index
%i2 = arith.constant 2 : index
%order = arith.constant 4 : index
%wx = memref.alloca() : memref<8x!pme_real>
%wy = memref.alloca() : memref<8x!pme_real>
%wz = memref.alloca() : memref<8x!pme_real>
%dx = memref.alloca() : memref<8x!pme_real>
%dy = memref.alloca() : memref<8x!pme_real>
%dz = memref.alloca() : memref<8x!pme_real>
%qs = memref.load %q[%i] : memref<?x!pme_chg, 1>
%qi = PME_CHG_TO_REAL %qs : !pme_chg to !pme_real""")
    starts = []
    for axis in range(3):
        t = "xyz"[axis]
        body(f"""\
%{t}sc = arith.constant {axis} : index
%{t}sn = arith.muli %count, %{t}sc : index
%{t}sat = arith.addi %{t}sn, %i : index
%{t}start_r = memref.load %weights[%{t}sat] : memref<?x!pme_real, 1>
%{t}start = arith.fptosi %{t}start_r : !pme_real to i32
%{t}fc = arith.constant {3 + axis} : index
%{t}fn = arith.muli %count, %{t}fc : index
%{t}fat = arith.addi %{t}fn, %i : index
%{t}frac = memref.load %weights[%{t}fat] : memref<?x!pme_real, 1>""")
        bspline(body, f"b{t}_", f"%{t}frac", "%order", f"%w{t}", f"%d{t}")
        starts.append(f"%{t}start")
    sx, sy, sz = starts
    w3 = pick(body, "w3p_", "%wz", "%j3")
    d3 = pick(body, "d3p_", "%dz", "%j3")
    body(f"""\
%gzero = arith.constant 0.0 : !pme_real
%j0 = arith.constant 0 : index
%j1c = arith.constant 1 : index
%k1t = arith.index_cast %k1 : index to i32
%k2t = arith.index_cast %k2 : index to i32
%k3t = arith.index_cast %k3 : index to i32
%j3t = arith.index_cast %j3 : index to i32
%g3s = arith.addi {sz}, %j3t : i32
%g3w = arith.subi %g3s, %k3t : i32
%g3over = arith.cmpi uge, %g3s, %k3t : i32
%g3 = arith.select %g3over, %g3w, %g3s : i32
%sumx, %sumy, %sumz = scf.for %j1 = %j0 to %order step %j1c
    iter_args(%ax = %gzero, %ay = %gzero, %az = %gzero) -> (!pme_real, !pme_real, !pme_real) {{
  %j1t = arith.index_cast %j1 : index to i32
  %g1s = arith.addi {sx}, %j1t : i32
  %g1w = arith.subi %g1s, %k1t : i32
  %g1over = arith.cmpi uge, %g1s, %k1t : i32
  %g1 = arith.select %g1over, %g1w, %g1s : i32
  %row1 = arith.muli %g1, %k2t : i32
  %w1 = memref.load %wx[%j1] : memref<8x!pme_real>
  %d1 = memref.load %dx[%j1] : memref<8x!pme_real>
  %bx2, %by2, %bz2 = scf.for %j2 = %j0 to %order step %j1c
      iter_args(%cx = %ax, %cy = %ay, %cz = %az) -> (!pme_real, !pme_real, !pme_real) {{
    %j2t = arith.index_cast %j2 : index to i32
    %g2s = arith.addi {sy}, %j2t : i32
    %g2w = arith.subi %g2s, %k2t : i32
    %g2over = arith.cmpi uge, %g2s, %k2t : i32
    %g2 = arith.select %g2over, %g2w, %g2s : i32
    %w2 = memref.load %wy[%j2] : memref<8x!pme_real>
    %d2 = memref.load %dy[%j2] : memref<8x!pme_real>
    %row = arith.addi %row1, %g2 : i32
    %gbase = arith.muli %row, %k3t : i32
    %at32 = arith.addi %gbase, %g3 : i32
    %at = arith.index_cast %at32 : i32 to index
    %p = memref.load %phi[%at] : memref<?x!pme_real, 1>
    %d1w2 = arith.mulf %d1, %w2 : !pme_real
    %w1d2 = arith.mulf %w1, %d2 : !pme_real
    %w1w2 = arith.mulf %w1, %w2 : !pme_real
    %px = arith.mulf %d1w2, {w3} : !pme_real
    %py = arith.mulf %w1d2, {w3} : !pme_real
    %pz = arith.mulf %w1w2, {d3} : !pme_real
    %vx = arith.mulf %p, %px : !pme_real
    %vy = arith.mulf %p, %py : !pme_real
    %vz = arith.mulf %p, %pz : !pme_real
    %nx = arith.addf %cx, %vx : !pme_real
    %ny = arith.addf %cy, %vy : !pme_real
    %nz = arith.addf %cz, %vz : !pme_real
    scf.yield %nx, %ny, %nz : !pme_real, !pme_real, !pme_real
  }}
  scf.yield %bx2, %by2, %bz2 : !pme_real, !pme_real, !pme_real
}}""")
    return f"""
// The forces from the weights of the particles, as @mdrt_gpu_pme_gather
// gives them, of order 4: see gather_weights in the script.
func.func private @mdrt_gpu_pme_gather_weights(%x: memref<?x3x!pme_pos, 1>, %q: memref<?x!pme_chg, 1>,
                                               %phi: memref<?x!pme_real, 1>, %box: vector<3xf64>,
                                               %weights: memref<?x!pme_real, 1>,
                                               %k1: index, %k2: index, %k3: index,
                                               %f: memref<?x3x!pme_frc, 1>) {{
  %c0 = arith.constant 0 : index
  %c1 = arith.constant 1 : index
  %c128 = arith.constant 128 : index
  %lx = vector.extract %box[0] : f64 from vector<3xf64>
  %ly = vector.extract %box[1] : f64 from vector<3xf64>
  %lz = vector.extract %box[2] : f64 from vector<3xf64>
  %k1i = arith.index_cast %k1 : index to i64
  %k2i = arith.index_cast %k2 : index to i64
  %k3i = arith.index_cast %k3 : index to i64
  %k1f = arith.sitofp %k1i : i64 to f64
  %k2f = arith.sitofp %k2i : i64 to f64
  %k3f = arith.sitofp %k3i : i64 to f64
  %rx = arith.divf %k1f, %lx : f64
  %ry = arith.divf %k2f, %ly : f64
  %rz = arith.divf %k3f, %lz : f64
  %rxr = PME_F64_TO_REAL %rx : f64 to !pme_real
  %ryr = PME_F64_TO_REAL %ry : f64 to !pme_real
  %rzr = PME_F64_TO_REAL %rz : f64 to !pme_real
  %count = memref.dim %x, %c0 : memref<?x3x!pme_pos, 1>
  %lanes_all = arith.constant PME_LANES : index
  %points = arith.muli %count, %lanes_all : index
  %last = arith.subi %count, %c1 : index
{gather_launch(body.text())}  return
}}
"""


def forces(tilted):
    """The forces of a particle from the sums of its derivatives along the
    three axes of the grid: -q K_a / L_a times each, or for a triclinic cell
    -q H⁻¹ (K_a times each), x from a alone, y from a and b, z from all."""
    if not tilted:
        return """\
        %sxq = arith.mulf %mq, %rxr : !pme_real
        %syq = arith.mulf %mq, %ryr : !pme_real
        %szq = arith.mulf %mq, %rzr : !pme_real
        %fx64 = arith.mulf %sxq, %allx : !pme_real
        %fy64 = arith.mulf %syq, %ally : !pme_real
        %fz64 = arith.mulf %szq, %allz : !pme_real
"""
    return """\
        %ka1 = arith.mulf %k1fr, %allx : !pme_real
        %ka2 = arith.mulf %k2fr, %ally : !pme_real
        %ka3 = arith.mulf %k3fr, %allz : !pme_real
        %fxh = arith.mulf %h00r, %ka1 : !pme_real
        %fyh1 = arith.mulf %h10r, %ka1 : !pme_real
        %fyh2 = arith.mulf %h11r, %ka2 : !pme_real
        %fyh = arith.addf %fyh1, %fyh2 : !pme_real
        %fzh1 = arith.mulf %h20r, %ka1 : !pme_real
        %fzh2 = arith.mulf %h21r, %ka2 : !pme_real
        %fzh3 = arith.mulf %h22r, %ka3 : !pme_real
        %fzh12 = arith.addf %fzh1, %fzh2 : !pme_real
        %fzh = arith.addf %fzh12, %fzh3 : !pme_real
        %fx64 = arith.mulf %mq, %fxh : !pme_real
        %fy64 = arith.mulf %mq, %fyh : !pme_real
        %fz64 = arith.mulf %mq, %fzh : !pme_real
"""


def gather_store(potential):
    """What the first thread of a particle stores: its force, or the
    potential of the grid at it."""
    if potential:
        return """\
        %pots = PME_REAL_TO_FRC %allx : !pme_real to !pme_frc
        memref.store %pots, %f[%i] : memref<?x!pme_frc, 1>
"""
    return """\
        %mq = arith.negf %qi : !pme_real
""" + forces(TILTED) + """\
        %fxs = PME_REAL_TO_FRC %fx64 : !pme_real to !pme_frc
        %fys = PME_REAL_TO_FRC %fy64 : !pme_real to !pme_frc
        %fzs = PME_REAL_TO_FRC %fz64 : !pme_real to !pme_frc
        memref.store %fxs, %f[%i, %i0] : memref<?x3x!pme_frc, 1>
        memref.store %fys, %f[%i, %i1] : memref<?x3x!pme_frc, 1>
        memref.store %fzs, %f[%i, %i2] : memref<?x3x!pme_frc, 1>
"""


def gather_launch(body_text, potential=False):
    """The launch of the gather: every thread of a block takes part in the
    shuffles, so the threads beyond the last point compute for the last
    particle."""
    return f"""\
  %blocks_points = func.call @mdrt_gpu_pme_blocks(%points) : (index) -> index
  gpu.launch blocks(%bx, %by, %bz) in (%gx = %blocks_points, %gy = %c1, %gz = %c1)
             threads(%tx, %ty, %tz) in (%sx = %c128, %sy = %c1, %sz = %c1) {{
    %base = arith.muli %bx, %c128 : index
    %item0 = arith.addi %base, %tx : index
    %inside = arith.cmpi ult, %item0, %points : index
    %lanes_l = arith.constant PME_LANES : index
    %c4l = arith.constant 4 : index
    %lane_of = arith.remui %item0, %lanes_l : index
    %last_first = arith.muli %last, %lanes_l : index
    %last_item = arith.addi %last_first, %lane_of : index
    %item = arith.select %inside, %item0, %last_item : index
{body_text}\
      %width = arith.constant 32 : i32
      %one32 = arith.constant 1 : i32
      %two32 = arith.constant 2 : i32
      %sx1, %vsx1 = gpu.shuffle xor %sumx, %one32, %width : !pme_real
      %sy1, %vsy1 = gpu.shuffle xor %sumy, %one32, %width : !pme_real
      %sz1, %vsz1 = gpu.shuffle xor %sumz, %one32, %width : !pme_real
      %tx1 = arith.addf %sumx, %sx1 : !pme_real
      %ty1 = arith.addf %sumy, %sy1 : !pme_real
      %tz1 = arith.addf %sumz, %sz1 : !pme_real
      %sx2, %vsx2 = gpu.shuffle xor %tx1, %two32, %width : !pme_real
      %sy2, %vsy2 = gpu.shuffle xor %ty1, %two32, %width : !pme_real
      %sz2, %vsz2 = gpu.shuffle xor %tz1, %two32, %width : !pme_real
      %ux = arith.addf %tx1, %sx2 : !pme_real
      %uy = arith.addf %ty1, %sy2 : !pme_real
      %uz = arith.addf %tz1, %sz2 : !pme_real
      // With 8 threads a particle, the halves are added too; with 4, the
      // other half of the shuffle is another particle.
      %four32 = arith.constant 4 : i32
      %eight_lanes = arith.cmpi ugt, %lanes_l, %c4l : index
      %sx4, %vsx4 = gpu.shuffle xor %ux, %four32, %width : !pme_real
      %sy4, %vsy4 = gpu.shuffle xor %uy, %four32, %width : !pme_real
      %sz4, %vsz4 = gpu.shuffle xor %uz, %four32, %width : !pme_real
      %zero_r = arith.constant 0.0 : !pme_real
      %hx = arith.select %eight_lanes, %sx4, %zero_r : !pme_real
      %hy = arith.select %eight_lanes, %sy4, %zero_r : !pme_real
      %hz = arith.select %eight_lanes, %sz4, %zero_r : !pme_real
      %allx = arith.addf %ux, %hx : !pme_real
      %ally = arith.addf %uy, %hy : !pme_real
      %allz = arith.addf %uz, %hz : !pme_real
      %first = arith.cmpi eq, %j3, %c0 : index
      %stores = arith.andi %inside, %first : i1
      scf.if %stores {{
{gather_store(potential)}      }}
    gpu.terminator
  }}
"""


HEADER_TRICLINIC = """\
// The kernels of the reciprocal sum of smooth particle mesh Ewald on a
// device [Essmann1995] for a triclinic cell (docs/triclinic-m2.md): those
// of PMEGPU.mlir that depend on the cell, with `box` the vector of six,
// a_x, b_y, c_z, b_x, c_x, c_y, of the lower-triangular cell H. The
// particles are placed by their fractional coordinates s = x H⁻¹; the
// forces are those of s taken through H⁻¹; the wave vector of the point n
// is k = H⁻¹ n, and the Gaussian exp(-π² k² / β²) is computed at each
// point, since k² is not a sum of a term for each axis. The kernels that
// do not depend on the cell, the conversion of the grid from fixed point
// and the spreading into bricks, are those of PMEGPU.mlir, which the
// compiler adds as well. The keys are those of docs/references.md.
//
// Generated by scripts/generate-pme-gpu-template.py. Do not edit.

!pme_pos = f64
!pme_chg = f64
!pme_frc = f64
!pme_real = f64

func.func private @mdrt_gpu_pme_blocks_triclinic(%count: index) -> index {
  %c127 = arith.constant 127 : index
  %c128 = arith.constant 128 : index
  %padded = arith.addi %count, %c127 : index
  %result = arith.divui %padded, %c128 : index
  return %result : index
}
"""

# H⁻¹ of the lower-triangular cell, also lower triangular, in f64 and in
# !pme_real: h00 = 1/a_x, h11 = 1/b_y, h22 = 1/c_z, h10 = -b_x/(a_x b_y),
# h21 = -c_y/(b_y c_z), h20 = (b_x c_y - b_y c_x)/(a_x b_y c_z).
INVERSE = """\
  %tbx = vector.extract %box[3] : f64 from vector<6xf64>
  %tcx = vector.extract %box[4] : f64 from vector<6xf64>
  %tcy = vector.extract %box[5] : f64 from vector<6xf64>
  %hunit = arith.constant 1.0 : f64
  %h00 = arith.divf %hunit, %lx : f64
  %h11 = arith.divf %hunit, %ly : f64
  %h22 = arith.divf %hunit, %lz : f64
  %h10a = arith.mulf %tbx, %h00 : f64
  %h10b = arith.mulf %h10a, %h11 : f64
  %h10 = arith.negf %h10b : f64
  %h21a = arith.mulf %tcy, %h11 : f64
  %h21b = arith.mulf %h21a, %h22 : f64
  %h21 = arith.negf %h21b : f64
  %h20a = arith.mulf %tbx, %tcy : f64
  %h20b = arith.mulf %ly, %tcx : f64
  %h20c = arith.subf %h20a, %h20b : f64
  %h20d = arith.mulf %h20c, %h00 : f64
  %h20e = arith.mulf %h20d, %h11 : f64
  %h20 = arith.mulf %h20e, %h22 : f64
  %h00r = PME_F64_TO_REAL %h00 : f64 to !pme_real
  %h10r = PME_F64_TO_REAL %h10 : f64 to !pme_real
  %h11r = PME_F64_TO_REAL %h11 : f64 to !pme_real
  %h20r = PME_F64_TO_REAL %h20 : f64 to !pme_real
  %h21r = PME_F64_TO_REAL %h21 : f64 to !pme_real
  %h22r = PME_F64_TO_REAL %h22 : f64 to !pme_real
"""


def triclinic():
    """The kernels of a triclinic cell, from those of an orthorhombic one
    written with TILTED: named with `_triclinic`, taking the cell of six,
    with H⁻¹ after its diagonal, and in the gathers the numbers of points
    of the axes in !pme_real."""
    global TILTED
    TILTED = True
    weights = weights_kernels()
    weights = weights[:weights.index("\n// Adds the charges to `bricks`")] + "\n"
    text = (spread() + spread(fixed=False) + weights + tables() + convolve() + scale() +
            dispersion() + gather() + gather_weights() + gather(potential=True))
    TILTED = False
    text = re.sub(r"func\.func private @mdrt_gpu_pme_(\w+)\(",
                  r"func.func private @mdrt_gpu_pme_\1_triclinic(", text)
    text = text.replace("@mdrt_gpu_pme_blocks(", "@mdrt_gpu_pme_blocks_triclinic(")
    text = text.replace("%box: vector<3xf64>", "%box: vector<6xf64>")
    text = text.replace(": f64 from vector<3xf64>", ": f64 from vector<6xf64>")
    last = "  %lz = vector.extract %box[2] : f64 from vector<6xf64>\n"
    text = text.replace(last, last + INVERSE)
    numbers = "  %rzr = PME_F64_TO_REAL %rz : f64 to !pme_real\n"
    text = text.replace(numbers, numbers + """\
  %k1fr = PME_F64_TO_REAL %k1f : f64 to !pme_real
  %k2fr = PME_F64_TO_REAL %k2f : f64 to !pme_real
  %k3fr = PME_F64_TO_REAL %k3f : f64 to !pme_real
""")
    return HEADER_TRICLINIC + text


def dispersion():
    """The product with the influence function of the sum of the
    dispersion (D162): tables, convolve, and scale, named with
    `_dispersion`; the spreading and the gathering are those of the
    charges, with the coefficients of the particles."""
    global DISPERSION
    DISPERSION = True
    text = named(tables() + convolve() + scale())
    DISPERSION = False
    return text


def main():
    # The templates of the repository, or with a directory as the argument
    # the same files there, which generated-templates.test compares with
    # them.
    here = os.path.dirname(os.path.abspath(__file__))
    templates = (sys.argv[1] if len(sys.argv) > 1 else
                 os.path.join(here, "..", "lib", "Runtime", "Templates"))
    with open(os.path.join(templates, "PMEGPU.mlir"), "w") as file:
        file.write(HEADER + spread() + spread(fixed=False) + weights_kernels() + real() +
                   tables() + convolve() + scale() + dispersion() + gather() +
                   gather_weights() + gather(potential=True))
    with open(os.path.join(templates, "PMEGPUTriclinic.mlir"), "w") as file:
        file.write(triclinic())


if __name__ == "__main__":
    main()
