# Writes a header with the commit of the source tree and whether the tree
# had changes, run at every build so that `mdir version` and the reports of
# defects name the source that was built. The header is rewritten only when
# its content changes.
#
# Inputs: SOURCE_DIR, OUTPUT.

find_package(Git QUIET)
set(commit "unknown")
set(dirty "unknown")
if(GIT_FOUND)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE out RESULT_VARIABLE result
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(result EQUAL 0)
    set(commit "${out}")
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
      WORKING_DIRECTORY "${SOURCE_DIR}"
      OUTPUT_VARIABLE out RESULT_VARIABLE result
      OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(result EQUAL 0)
      if(out STREQUAL "")
        set(dirty "no")
      else()
        set(dirty "yes")
      endif()
    endif()
  endif()
endif()

set(content "// Generated by cmake/BuildInfo.cmake.
#define MDIR_GIT_COMMIT \"${commit}\"
#define MDIR_GIT_DIRTY \"${dirty}\"
")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old)
else()
  set(old "")
endif()
if(NOT old STREQUAL content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
